settings:
  name: ONTAP tools for VMware vSphere 10.2
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
    - title: ONTAP tools for VMware vSphere 10.2 docs
      url: /index.html
    - title: Release notes
      url: /release-notes.html
      - title: What's new in this release
        url: /whats-new.html
      - title: Feature matrix
        url: /feature-matrix.html
    - section: concepts
    - section: deploy
    - section: configure
    - section: protect
    - section: manage
    - section: upgrade
    - section: migrate
    - section: automation
    - title: Legal notices
      url: /legal-notices.html
