settings:
  name: ONTAP tools for VMware vSphere 10.3
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
    - title: ONTAP tools for VMware vSphere 10.3 docs
      url: /index.html
    - section: release-notes
    - section: concepts
    - section: deploy
    - section: configure
    - section: protect
    - section: manage
    - section: upgrade
    - section: migrate
    - section: automation
    - title: Legal notices
      url: /legal-notices.html
