---
permalink: migrate/migrate-to-latest-ontaptools.html
sidebar: sidebar
keywords: migrate
summary: 'When migrating storage data, storage backends are onboarded manually using REST APIs. When migrating VASA Provider data, data is exported from existing Derby database and imported into the MongoDB database.'
---
= Migrate from ONTAP tools for VMware vSphere 9.x to 10.3
:icons: font
:imagesdir: ../media/

[.lead]
When migrating storage data, storage backends are onboarded manually using REST APIs. When migrating VASA Provider data, data is exported from the existing Derby database and imported into the MongoDB database.

[NOTE]
You should migrate ONTAP tools for VMware vSphere 9.xx setup only if the setup is servicing the VASA Provider feature alone.

[NOTE]
After migrating from ONTAP tools for VMware vSphere 9.x to 10.3, vVols datastores with the NVMe/FC protocol do not work because ONTAP tools 10.3 only supports NVMe-oF with VMFS datastores.

//updated for 10.3 jira OTVDOC-147

*About this task*

You can migrate from ONTAP tools for VMware vSphere 9.12D1 and 9.13D2 releases to 10.3. 

//updated for OTVDOC-175 - jani
[NOTE]
You must take the OVA backup from your current release before upgrading to the patch releases. 

== Common migration steps

. Deploy OVA for ONTAP tools for VMware vSphere 10.3 release. 
. Add the vCenter Server instance you want to migrate to ONTAP tools for VMware vSphere 10.3 release. See link:../configure/add-vcenter.html[Add vCenter Server instances]
. Onboard storage backend locally from the ONTAP tools for VMware vSphere plug-in vCenter server APIs. Add storage as a locally scoped storage for migration.
. The NFS and VMFS datastores migrated from ONTAP tools for VMware vSphere 9.xx is visible in ONTAP tools for VMware vSphere 10.3 only after the datastore discovery job is triggered, which might take up to 30 minutes to trigger. Verify if the datastores are visible on the Overview page of the ONTAP tools for the VMware vSphere Plugin UI page.  

// updated as per doc_feedback - jani

== SRA migration steps

*Before you begin*


Before migrating, ensure that one of the sites is in a protected state and the other is in a recovery state.

[NOTE]
Do not migrate if the failover has just been completed and re-protection is pending. Complete the re-protection and then Perform the migration. After completing the recovery plan testing, clean up the test recovery and start the migration.

. Perform the following steps to delete ONTAP tools for VMware vSphere 9.xx release SRA adapter in VMware Live Site Recovery UI:
.. Go to VMware Live Site Recovery Configuration management page
.. Go to the *Storage Replication Adapter* section 
.. Select the ellipsis menu and select *Reset configuration*
.. Select the ellipsis menu and select *Delete*
+
Perform these steps on both protection and recovery sites.
. Install ONTAP tools for VMware vSphere 10.3 SRA adapter on both protection and recovery sites using the steps in link:../protect/configure-on-srm-appliance.html[Configure SRA on VMware Live Site Recovery appliance]
. On the VMware Live Site Recovery UI page, perform *Discover Arrays* and *Discover Devices* operations and verify that the devices are showing as they were before the migration.

== VASA Provider migration steps

. Enable Derby PORT 1527 on the existing ONTAP tools for VMware vSphere. To enable the port, log in to CLI with the root user and run the following command:
+
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----

. Deploy OVA for ONTAP tools for VMware vSphere 10.3.
. Add the vCenter Server instance you want to migrate to ONTAP tools for VMware vSphere 10.3 release. See link:../configure/add-vcenter.html[Add a vCenter Server instance]. 
. Onboard storage backend locally from the remote plug-in vCenter server APIs. Add storage as local scoped for migration.
. Issue the following API call to migrate:
+
====

*HTTP method and endpoint*

This REST API call uses the following method and endpoint.

|===

|*HTTP method* |*Path*
|POST
|/api/v1

|===

*Processing type*

Asynchronous

*Curl example*

/api/v1/vcenters/{vcguid}/migration-jobs

*JSON input example*
Request body for migrating from 9.12 and 9.13:

{
  "otv_ip": "10.12.13.45",
  "vasa_provider_credentials": {
    "username": "vasauser",
    "password": "*******"
  }
  "database_password": "*******"
}

Request body for other release migration: 

{
  "otv_ip": "10.12.13.45",
  "vasa_provider_credentials": {
    "username": "vasauser",
    "password": "*******"
  }
}

*JSON output example*

A job object is returned. You should save the job identifier to use it in the next step.

{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
// URI <https://10.60.24.125:8443/virtualization/api/v1/migration/migrate>
====
. Use the following URI to check the status:
+
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
Once the job is completed, validate the migration report. The report is part of the job data and can be seen from the job response.
. Add ONTAP tools for VMware vSphere storage provider to the vCenter Server and link:../configure/registration-process.html[Register the VASA Provider with a vCenter Server instance].
. Stop ONTAP tools for VMware vSphere storage provider 9.10/9.11/9.12/9.13 VASA Provider service from the maintenance console.
+
[Note] 
Do not delete the VASA Provider.
+
Once the old VASA Provider is stopped, the vCenter Server fails over to ONTAP tools for VMware vSphere. All the datastores and VMs become accessible and are served from ONTAP tools for VMware vSphere.
. Perform the patch migration using the following API:
+
====

*HTTP method and endpoint*

This REST API call uses the following method and endpoint.

|===

|*HTTP method* |*Path*
|PATCH
|/api/v1

|===

*Processing type*

Asynchronous

*Curl example*

PATCH "/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43

*JSON input example*

{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}

*JSON output example*

A job object is returned. You should save the job identifier to use it in the next step.

{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
// URI <https://10.60.24.125:8443/virtualization/api/v1/migration/migrate>

The request body is empty for patch operation.

[NOTE]
uuid is the migration uuid returned in the response of post migrate API.

Once the patch migration API is run successfully, all the VMs comply with the storage policy.

====

. The delete API for migration is:
+
====
|===

|*HTTP method* |*Path*
|DELETE
|/api/v1

|===

*Processing type*

Asynchronous

*Curl example*

/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}

This API deletes migration by migration ID and deletes migration on the given vCenter Server.

====

After successful migration and after you register ONTAP tools 10.3 to the vCenter Server, do the following:

* Refresh the certificate on all the hosts.
* Wait for some time before performing Datastore (DS) and Virtual Machine (VM) operations. The waiting time depends on the number of hosts, DS, and VMs in the setup. When you don't wait, the operations may fail intermittently.

*After you finish*

After the upgrade, if the virtual machine compliance state is out of date, reapply the virtual machine storage policy using the following steps:

. Navigate to the datastore and select *Summary* > *VM Storage policies*.
+
Under *VM storage policy compliance*, you can see the compliance status. It shows as *Out-of-date*
. Select the Storage VM policy and the corresponding VM
. Select *Apply*
+
The compliance status under *VM storage policy compliance* is now shown as compliant.

// updated for OTVDOC-192
