---
permalink: migrate/migrate-to-latest-ontaptools.html
sidebar: sidebar
keywords: migrate
summary: 'Choose the supported migration path from ONTAP tools for VMware vSphere 9.xx to 10.6 based on whether your environment includes vVols datastores.'
---
= Migrate from ONTAP tools for VMware vSphere 9.xx to 10.6
:icons: font
:imagesdir: ../media/

[.lead]
Migrating from ONTAP tools for VMware vSphere 9.xx to 10.6 requires different steps based on your datastore types.

You can migrate from ONTAP tools for VMware vSphere 9.12D1, 9.13D2, and 9.13P2 releases to ONTAP tools for VMware vSphere 10.6.

// updated for OTVDOC-175 - jani
If your setup has NFS and VMFS datastores and no vVols datastores, uninstall ONTAP tools 9.xx and deploy ONTAP tools 10.6. If your setup contains vVols datastores, migrate the VASA Provider and SRA.

The following table outlines the migration process in these two different scenarios. 
|===
|*If the setup has vVols datastores* |*If the setup contains only NFS and VMFS datastores*

|
Steps:

1. link:../migrate/sra-vasa-migration.html[Migrate the VASA Provider] 

2. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html[Create VM storage policies]

|
Steps:

1. Remove ONTAP tools 9.xx from your environment. See https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment[How to remove OTV 9.xx from your environment] in the NetApp Knowledge Base.

2. link:../deploy/quick-start.html[Deploy and configure ONTAP tools for VMware vSphere 10.6] 

3. link:../migrate/sra-vasa-migration.html[Update the SRA]

4. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html[Create VM storage policies]

|===
[NOTE]
After migrating from ONTAP tools for VMware vSphere 9.xx to 10.6, vVols datastores using the NVMe/FC protocol become non-operational because ONTAP tools 10.6 supports the NVMe-oF protocol only with VMFS datastores.

== After migration

Verify the following:

* Datastores are accessible from vCenter Server.
* VM storage policies are mapped as expected.
* Protection and replication status shows healthy for configured datastores.

// updated for 10.3 jira OTVDOC-147
