---
permalink: migrate/migrate_to_ng.html
sidebar: sidebar
keywords: migrate
summary: 'When migrating storage data, storage backends are onboarded manually using REST APIs. When migrating VASA provider data, data is exported from existing Derby database and imported into the MongoDB database.'
---
= Migrate to the latest release of ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
When migrating storage data, storage backends are onboarded manually using REST APIs. When migrating VASA provider data, data is exported from existing Derby database and imported into the MongoDB database.

[NOTE]
It is recommended to migrate classic setup only if the setup is servicing the VASA provider feature alone. If you have features like traditional/NVMe datastores, vVol replication, and if SRA is enabled on classic, it is not recommended to migrate the setup to ONTAP tools for VMware vSphere 10.0.

*About this task* 

Migration is supported from ONTAP tools for VMware vSphere 9.10P1 and 9.11P1 releases to 10.0 release. To migrate from:

* ONTAP tools for VMware vSphere 9.10 release, first upgrade to 9.10P1 release then migrate to 10.0 release.
* ONTAP tools for VMware vSphere 9.11 release, first upgrade to 9.11P1 release then migrate to 10.0 release.

ONTAP tools use certificate based authentication with ONTAP irrespective of the migration path.

*Steps*

. Enable Derby PORT 1527 on the existing ONTAP tools for VMware vSphere 9.10P1 and 9.11P1. To enable the port, login to CLI with root user and run the following command:
+
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Deploy OVA for ONTAP tools for VMware vSphere 10.0 release. See link:../qsg_10.html[ONTAP tools Quick start]
. Add the vCenter that you want to migrate to ONTAP tools for VMware vSphere 10.0 release. See link:../configure/add_vcenter.html[Add vCenter]
. Onboard storage backend from the remote plugin vCenter APIs. See link:../configure/onboard_svm.html[ Onboard storage backend]
. Use the following API to migrate:
+
----
/api/v1/vcenters/{vcguid}/migration-jobs

{
  "otv_ip": "10.10.10.10",
  "vasa_provider_credentials": {
    "username": "Administrator",
    "password": "password"
  }
}
----
+
Above API call gives the jobid, which can be used for status check.
// URI <https://10.60.24.125:8443/virtualization/api/v1/migration/migrate>
. Use the following URI to check the status:
+
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
. Once the job is completed, validate the migration report 
// available at: <TBD> for any failure.
. Add ONTAP tools storage provider 10.0 to the vCenter and link:../configure/register_vasa.html[Register VASA Provider to vCenter].
. Disable ONTAP tools for VMware vSphere 9.11P1 or 9.10P1 VASA provider.
.. Select ONTAP tools in the vSphere client home page.
.. Select *Settings* > *Manage capabilities* > *Disable VASA provider* from the ONTAP tools.
+
Note: NetApp recommends you not to delete the VASA provider.
+
Once the old VASA provider is disabled, vCenter will failover to ONTAP tools for VMware vSphere 10.0. All the datastores and VMs become accessible and will be served from ONTAP tools for VMware vSphere 10.0.
. Perform the patch migrate using the following API:
+
----
/virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
+
Request body is empty  for patch operation.
+
[NOTE]
uuid is the migration uuid returned in the response of post migrate API.
+
Once the patch migrate API is successful, all the VMs will be compliant with the storage policy.

The delete API for migration is:

----
Delete /virtualization/api/v1/vcenters/{vcguid}/migration-jobs/{migration_id}
----
This API deletes migration by Migration Id and deletes migration on the given vCenter.
