---
permalink: deploy/deployment-error-codes.html
sidebar: sidebar
keywords: upgrade
summary: 'This page outlines the error codes for the deployment, reboot, and recovery operations of ONTAP tools for VMware vSphere system.'
---
= Troubleshoot deployment errors
:icons: font
:imagesdir: ../media/

[.lead]
If you experience deployment issues, review the logs and error codes to diagnose and resolve problems. Starting with ONTAP tools for VMware vSphere 10.5, log bundles collected from the pods include logs from MongoDB, RabbitMQ, and Vault, along with the status and descriptions of all pods. These are provided in addition to the existing ONTAP tools service logs, enhancing supportability and troubleshooting.

== Collect the log files

You can collect log files for ONTAP tools for VMware vSphere from the options available in ONTAP tools Manager user interface. Technical support might ask you to collect the log files to help troubleshoot a problem.

[NOTE]
Generating logs from the ONTAP tools Manager includes all logs for all vCenter Server instances. Generating logs from the vCenter client user interface are scoped for the selected vCenter Server.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Log Bundles* from the sidebar.
+
This operation can take several minutes.
. Select *Generate* to generate the log files.
. Enter the label for the Log Bundle and select *Generate*.
+
Download the tar.gz file and send it to technical support. 

Follow the steps below to generate log bundle using the vCenter client user interface:

.Steps

. Log in to the vSphere client.
. From the vSphere Client home page, go to *Support* > *Log bundle* > *Generate*.
. Provide the log bundle label and generate the log bundle.
You can see the download option when the files are generated. Downloading might take some time.

[NOTE]
The log bundle generated replaces the log bundle that was generated within the last 3 days or 72 hrs.

== Deployment error codes
You might encounter error codes during ONTAP tools for VMware vSphere deployment, reboot, and recovery operations. 
The error codes are five digits long, where the first two digits represent the script that encountered the issue, and the last three digits represent the specific workflow within that script.

All error logs are recorded in the ansible-perl-errors.log file under the /var/log directory to facilitate easy tracking and resolution of issues. This log file contains the error code and the failed Ansible task.
[NOTE]
The error codes provided on this page are for reference only. Contact the support team if error persists or if there's no resolution mentioned.

The following table lists the error codes and the corresponding file names.

|===

|*Error code*| *Script name*
|00 |firstboot-network-config.pl, mode deploy
|01 |firstboot-network-config.pl, mode upgrade
|02 |firstboot-inputs-validation.pl
|03 |firstboot-deploy-otv-ng.pl, deploy, HA
|04 |firstboot-deploy-otv-ng.pl, deploy, non-HA
|05 |firstboot-deploy-otv-ng.pl, reboot
|06 |firstboot-deploy-otv-ng.pl, upgrade, HA
|07 |firstboot-deploy-otv-ng.pl, upgrade, non-HA
|08 |firstboot-otv-recovery.pl
|09 |post-deploy-upgrade.pl

|===

The last three digits of the error code indicate the specific workflow error within the script:

|===
|*Deployment error code*|*Workflow* |*Resolution*
|049 |For network and validation perl script will assign them as well shortly |-
|050 |Ssh Key generation failed |Restart the primary virtual machine (VM).
|053 |Failed installing RKE2 |Either run the following and restart the primary VM or redeploy:
sudo rke2-killall.sh (all VMs)
sudo rke2-uninstall.sh (all VMs).
|054 |Failed setting kubeconfig |Redeploy
|055 |Failed deploying registry |If the registry pod is present, wait for the pod to be ready then restart the primary VM or else redeploy.
|059 |KubeVip deployment has failed | Ensure virtual IP address for Kubernetes control plane and ONTAP tools IP address provided during deployment belong to same VLAN and are free IP addresses. Restart if all the previous points are correct. Else, redeploy.
|060 |Operator deployment has failed |Restart
|061 |Services deployment has failed |Perform basic Kubernetes debugging like get pods, get rs, get svc, and so on in ntv-system namespace for more details and error logs at /var/log/ansible-perl-errors.log and /var/log/ansible-run.log and redeploy.
|062 |ONTAP tools Services deployment has failed |Refer to the error logs at /var/log/ansible-perl-errors.log for more details and redeploy.
|065 |Swagger page URL is not reachable |Redeploy
|066 |Post deployment steps for gateway certificate has failed |Do the following to recover/complete the upgrade:
* Enable diagnostic shell.
* Run 'sudo perl /home/maint/scripts/post-deploy-upgrade.pl --postDeploy' command.
* Check the logs at /var/log/post-deploy-upgrade.log.
|088 |Configuring log rotate for journald has failed |Check the VM network settings that is compatible with the host on which the VM is hosted. You can try to migrate to another host and restart the VM.
|089 |Changing ownership of summary log rotate config file has failed |Restart the primary VM.
|096 |Install dynamic storage provisioner |-
|108 |Seeding script failed |-
|===

|===
|*Reboot error code*|*Workflow* |*Resolution*
|067
|Waiting for rke2-server timed out. |-
|101
|Failed to Reset Maint/Console user password. |-
|102
|Failed to Delete password file during reset Maint/Console user password. |-
|103
|Failed to Update New Maint/Console user password in vault. |-
|088 |Configuring log rotate for journald has failed. |Check the VM network settings that is compatible with the host on which the VM is hosted. You can try to migrate to another host and restart the VM.
|089 |Changing ownership of summary log rotate config file has failed. |Restart the VM.

|===
