---
permalink: deploy/download-ontap-tools.html
sidebar: sidebar
keywords:
summary: 'You can download the .ova file for ONTAP tools for VMware vSphere from the NetApp Support Site.'
---
= Download ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
You can download the `.zip` file that contains  binaries (_.ova_) and signed certificates for ONTAP tools for VMware vSphere from the https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site^].

The _.ova_ file includes ONTAP tools. When the deployment is complete, ONTAP tools and VASA products are installed in your environment. By default, ONTAP tools for VMware vSphere starts working as soon as you decide on the subsequent deployment model and choose whether to enable VASA Provider based on your requirements. See link:../configure/registration-process.html[Register the VASA Provider with vCenter] for details.

== Content library

Content library in VMware is a container object which stores VM templates, vApp templates, and other types of files. Deployment with content library provides you with a seamless experience as it is not dependent on the network connectivity.
[NOTE]
It is recommended to store the content library on shared datastore, such that all hosts in a cluster can access it.
You need to create a content library to store the OVA before deploying them in HA configuration.
Create the content library using the following steps:

*Steps*

. Log in to the vSphere client using `\https://vcenterip/ui`
. Select the horizontal ellipses next to vSphere client and select *Content library*.
. Select *Create* button on the right side of the page.
. Provide a name for the library and create the content library.
. Navigate to the content library you created.
. Select *Actions* in the right side of the page and select *Import item* and import the OVA file.

// updated for 10.0 release