---
permalink: deploy/ontap-tools-deployment.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere appliance is always deployed as small sized single node with core services to support NFS/VMFS datastores.'
---
= Deploy ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere appliance is deployed as small-sized single node with core services to support NFS and VMFS datastores.

*Before you begin*

A content library in VMware is a container object which stores VM templates, vApp templates, and other types of files. Deployment with content library provides you with a seamless experience as it is not dependent on the network connectivity.
[NOTE]
You should store the content library on a shared datastore so that all hosts within a cluster can access it.
Create a content library to store the OVA before configuring the appliance to HA configuration. Do not delete the content library template after deployment.

[NOTE]
To enable HA deployment later, do not deploy the virtual machine hosting the ONTAP tools directly on an ESXi host. Deploy it on a cluster or resource pool instead.

If you don't have a content library, follow these steps to create one:

*Create content library*
In you plan to use only a small single node deployment, creating a content library is not necessary.

. Download the `.zip` file that contains binaries (_.ova_) and signed certificates for ONTAP tools for VMware vSphere from the https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab[NetApp Support Site^].
. Log in to the vSphere client using `\https://<vcenterip>/<ui>`
. Select the horizontal ellipses next to vSphere client and select *Content library*.
. Select *Create* on the right of the page.
. Provide a name for the library and create the content library.
. Navigate to the content library you created.
. Select *Actions* in the right of the page and select *Import item* and import the OVA file.

[NOTE]
For more information, refer to https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html[Creating and Using Content Library] blog.

[NOTE]
Before proceeding with the deployment, set the cluster's Distributed Resource Scheduler (DRS) on the inventory to 'Conservative'. This ensures that VMs are not migrated during the installation.

.Steps

. Download the `.zip` file that contains binaries (_.ova_) and signed certificates for ONTAP tools for VMware vSphere from the https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab[NetApp Support Site^]. If you have imported the OVA into the content library, you can skip this step and proceed with the next step.
. Log in to the vSphere server.
. Navigate to the resource pool, cluster, or host where you intend to deploy the OVA.
. Right-click the required location and select *Deploy OVF template...*.
[NOTE]
Never store ONTAP tools for VMware vSphere virtual machine on vVols datastores that it manages.
. Choose the OVA file from the URL or browse to its location, then select *Next*.
. To deploy ONTAP tools for VMware vSphere from the content library:
.. Go to your content library and select the library item that you want to deploy. 
.. Select *Actions* > *New VM from this template*
. In the *Select a name and folder* field, enter the virtual machine name and choose its location. If you select the checkbox labeled *Customize this virtual machine's hardware*, an additional step called *Customize hardware* will be enabled before reaching the *Ready to complete* window.
. Select a computer resource and select *Next*. Optionally, check the box to *Automatically power on deployed VM*.
. Review the details of the template and select *Next*.
. Read and accept the license agreement and select *Next*.
. Select the storage for the configuration and the disk files and select *Next*.
. Select the destination network for each source network and select *Next*.
. In the *Customize template* window, fill in the required fields and select *Next*. 
[NOTE] 
+
* The information is validated during installation. If there is a discrepancy, an error message appears on the web console, and you are prompted to correct it.
* Host names must include letters (A-Z, a-z), digits (0-9), and hyphens (-). To configure dual stack, specify the host name mapped to the IPv6 address.
[NOTE]
Pure IPv6 is not supported. Mixed mode is supported with VLAN containing both IPv6 and IPv4 addresses.
. In the *Customize hardware* window, enable CPU hot add and memory hot plugin.
. Review the details in the *Ready to complete* window, select *Finish*.
+
As the deployment task gets created, the progress is shown in the vSphere task bar.
. Power on the VM after the completion of the task.

You can track the progress of the installation within the VM's web console.

If there are discrepancies in the OVF form, a dialog box will prompt corrective action. Use the tab button to navigate, make the necessary changes, and select "OK.You have three attempts to resolve any issues. If problems continue after three attempts, the installation process will stop, and it is advised to retry the installation on a new virtual machine.