---
permalink: deploy/ontap-tools-deployment.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere appliance is always deployed as small sized single node with core services to support NFS/VMFS datastores.'
---
= Deploy ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere appliance is always deployed as small sized single node with core services to support NFS/VMFS datastores.

*Before you begin*

A content library in VMware is a container object which stores VM templates, vApp templates, and other types of files. Deployment with content library provides you with a seamless experience as it is not dependent on the network connectivity.
[NOTE]
You should store the content library on a shared datastore, such that all hosts in a cluster can access it.
You need to create a content library to store the OVA before changing the appliance settings to HA configuration. Content library template once uploaded should not be deleted post deployment.

[NOTE]
To enabling HA deployment later, virtual machine that is hosting the ONTAP tools should not be directly deployed on an ESXi host. Instead, it should be deployed either on a cluster or a resource pool.

If you do not already have a suitable content library, create one using the following steps:

*Create content library*
If you only intend to use a small single node deployment, you do not need to create a content library.

. Download the `.zip` file that contains binaries (_.ova_) and signed certificates for ONTAP tools for VMware vSphere from the https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site^].
. Log in to the vSphere client using `\https://<vcenterip>/<ui>`
. Select the horizontal ellipses next to vSphere client and select *Content library*.
. Select *Create* on the right of the page.
. Provide a name for the library and create the content library.
. Navigate to the content library you created.
. Select *Actions* in the right of the page and select *Import item* and import the OVA file.

[NOTE]
For more information, refer to https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html[Creating and Using Content Library] blog.

Make sure you have imported the OVA into your content library.

[NOTE]
Before proceeding with the deployment, set the cluster's Distributed Resource Scheduler (DRS) on the inventory to 'Conservative' during the installation of ONTAP tools. This ensures that VM's do not migrate during the installation.


.Steps

. Download the `.zip` file that contains binaries (_.ova_) and signed certificates for ONTAP tools for VMware vSphere from the https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site^]. If you have imported the OVA into the content library, you can skip this step and proceed with the next step as you can deploy directly from the content library.
. Log in to the vSphere server.
. Navigate to the resource pool that you have created or to the cluster or to the host where you want to deploy the OVA.
. Right-click the required location and select *Deploy OVF template...*.
[NOTE]
Never store ONTAP tools for VMware vSphere virtual machines on vVols datastores that they manage.
. Select the OVA file either through the URL for the _.ova_ file or browse to the folder where the _.ova_ file is saved, and then select *Next*.
. To deploy ONTAP tools for VMware vSphere from content library:
.. Go to your content library and select the library item that you want to deploy. 
.. Select *Actions* > *New VM from this template*
. In the *Select a name and folder* for the virtual machine window, enter the virtual machine name and select the location for the virtual machine. If you check the checkbox that says *Customize this virtual machine's hardware*, a step called *Customize hardware* is enabled before you reach the *Ready to complete* window.
. Select a computer resource and select *Next*. You can choose to check the checkbox to *Automatically power on deployed VM*.
. Review the details of the template and select *Next*.
. Read and accept the license agreement and select *Next*.
. Select the storage for the configuration and the disk files and select *Next*.
. Select the destination network for each source network and select *Next*.
. In the *Customize template* window, fill in the required fields and select *Next*. 
[NOTE] 

* The information provided here is validated for proper patterns during installation process. In case of discrepancy, an error message is displayed on the web console, and you are prompted to correct any incorrect information provided.
* Host names must consist of uppercase letters (A-Z), lowercase letters (a-z), digits (0-9), or the hyphen (-) special character. If you want to configure dual stack, specify the host name mapped to IPv6 address.
[NOTE]
Pure IPv6 is not supported. Mixed mode is supported with VLAN having both IPv6 and IPv4 addresses.
. In *Customize hardware* window you should enable CPU hot add and memory hot plug.
. Review the details in the *Ready to complete* window, select *Finish*.
+
As the deployment task gets created, the progress is shown in the vSphere task bar.
. Power on the VM after the completion of the task.
+
[NOTE]
Before powering on, make sure the VM has hot plugins enabled for both CPU and memory.

You can track the progress of the installation within the VM's web console.

In case of any discrepancies in the values entered in the OVF form, a dialog box will prompt you to take corrective action. Make the necessary changes within the dialog box, utilizing the tab button to navigate and select "OK." You have three attempts to rectify any issues. If issues persist after three attempts, the installation process will cease, and it is recommended that you retry the installation on a fresh VM.