---
permalink: deploy/pre-deploy-checks.html
sidebar: sidebar
keywords: ONTAP tools,Storage Replication Adapter
summary: 'Before deploying ONTAP tools for VMware vSphere, you should be familiar with the space requirements for the deployment package and some basic host system requirements.'
---
= Pre-deployment checks
:icons: font
:imagesdir: ../media/

[.lead]
Ensure the following items are in place before you proceed with the deployment:

* vCenter Server environment is set up and configured.

* Parent vCenter Server credentials to deploy the OVA are in place.

* You have the login credentials for your vCenter Server instance, to which the ONTAP tools for VMware vSphere will connect post-deployment for registration.

* Browser cache is deleted.

* Ensure that you have three free IP addresses available for non-HA deployment—one free IP address for the load balancer, one free IP address for the Kubernetes control plane, and one IP address for each node. For HA deployment, you'll need two more IP addresses for the second and third nodes.
Host names should be mapped to the free IP addresses on the DNS before assigning. All five IP addresses should be on the same VLAN that is selected for deployment.

* Ensure that the domain name on which the certificate is issued is mapped to the Virtual IP address in a multi-vCenter deployment where custom CA certificates are mandatory. Run the nslookup check on the domain name to check if the domain is getting resolved to the intended IP address. The certificates should be created with the domain name and the load balancer IP address.

* Determine if you will use multi-tenant SVMs or allow full cluster access. If using multi-tenant SVMs, you will need an SVM management LIF on each SVM. ONTAP tools must be able to reach this LIF over port 443.

* Determine if you will be using the ONTAP tools Storage Replication Adapter (SRA) for VMware Site Recovery Manager (SRM) or Live Site Recovery (VLSR). If so, you must access the SRM/VLSR server management interface to install the SRA.

* If you are using SnapMirror replication managed by ONTAP tools (including, but not limited to, SnapMirror active sync), then your ONTAP administrator must https://docs.netapp.com/us-en/ontap/peering/create-cluster-relationship-93-later-task.html[create a cluster peer relationship in ONTAP] and https://docs.netapp.com/us-en/ontap/peering/create-intercluster-svm-peer-relationship-93-later-task.html[create an intercluster SVM peer relationship in ONTAP] before you can use ONTAP tools with SnapMirror.

== Provision IP Addresses and DNS records
Request the following IP information from your network team. The first three IP addresses are required; node two and node three are used for scale-out high availability (HA) deployments. DNS host records are required and all IP addresses should be on the same VLAN.

❏ ONTAP tools application address

❏ Internal Services address

❏ Node one's DNS hostname

❏ Node one's IP address

❏ Subnet mask

❏ Default gateway

❏ DNS server 1

❏ DNS server 2

❏ DNS search domain

❏ Node two's DNS hostname(optional)

❏ Node two's IP address(optional)  

❏ Node three's DNS hostname(optional) 

❏ Node three's IP address(optional)  

❏ Create DNS records for all IP addresses above.

== Network firewall configuration
Open the required ports for the above IP addresses in your network firewall. Refer to link:../deploy/prerequisites.html[Port requirements] for the latest update.
