---
permalink: deploy/prepare_deployment.html
sidebar: sidebar
keywords:
summary: 'You should deploy ONTAP tools in your environment, and specify the required parameters, to be able to use the appliance.'
---
= Prepare to deploy ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the basic storage backend requirements, application requirements, and license requirements before you begin deploying ONTAP tools for VMware vSphere. 
Before you deploy ONTAP tools for VMware vSphere, it is good practice to plan your deployment and decide how you want to configure ONTAP tools in your environment. 

== Preparing for deployment 

Following are ONTAP tools requirements before proceeding with the deployment: 

* Configure and set up your vCenter Server environment. 
* Download the _.ova_ file. 
* Gather the Postman collections JSON file provided by NetApp. 
* Parent vCenter Server Credentials to deploy the OVA. 
* Make sure the host or the resource pool where the OVA is deployed has the minimum resources mentioned in the *Requirements to deploy ONTAP tools* section.  
* The login credentials for your vCenter Server instance to which the ONTAP tools will connect to post deployment for registration. 
* Delete the browser cache.
* You need five free IPs in the vlan(used for deployment),  in which three IPs will be used as the VM IPs, one for API server IP, and last one for Load Balancer IP which is used to access the services post deployment.
* In the case of multi-vCenter deployment where Custom CA certificates are mandatory, map the *Domain Name* on which the certificate is issued to the *Virtual IP*. Perform a ping check on the domain name to check whether the domain is getting resolved to the intended IP. The certificates should be created with domain name and IPAddress of the LoadBalancer IP.
* IPv4/IPv6 supported VLAN 
* NTP Server which is provided to the vCenter for time Sync.
* Static IP Configuration details for the Node or VM where the OVA is being deployed (Mandatory) and other details. 
.. vCenter hostname (venter where the OVA is deployed)
.. vCenter username (venter where the OVA is deployed)
.. vCenter password (venter where the OVA is deployed)
.. Resource pool
.. Data lif (IPv4/IPv6)
.. Management lif
.. ONTAP username
.. ONTAP password
.. SVM name
.. Protocol
.. API Server IP
.. Kobe VIP IP address
.. HA / NON-HA drop down
.. Hostnames(list of hostnames)
.. IpAddresses (string)(list of ipaddresses)
.. Content library name
.. OVF template name
.. IPv6 gateway (optional)