---
permalink: deploy/prepare_deployment.html
sidebar: sidebar
keywords:
summary: 'You should deploy ONTAP tools in your environment, and specify the required parameters, to be able to use the appliance.'
---
= Prepare to deploy ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of the basic storage backend requirements, application requirements, and license requirements before you begin deploying ONTAP tools for VMware vSphere. 
Before you deploy ONTAP tools for VMware vSphere, it is good practice to plan your deployment and decide how you want to configure ONTAP tools in your environment. 

== Preparing for deployment 

Following are ONTAP tools requirements before proceeding with the deployment: 

. Configure and set up your vCenter Server environment. 
. Download the _.ova_ file. 
. (Optional) Used for automation user - Gather the Postman collections JSON file provided by NetApp. 
. Parent vCenter Server Credentials to deploy the OVA. 
. Make sure the host or the resource pool where the OVA is deployed has the minimum resources mentioned in the *Requirements to deploy ONTAP tools* section.  
. The login credentials for your vCenter Server instance to which the ONTAP tools will connect to post deployment for registration. 
. Delete the browser cache.
. For non-HA deployment, you need three free IPs - one free IP for load balancer and one free IP for K8s control plane and one IP for node. For HA deployment, along with these three IPs you'll need two more IPs for second and third nodes.
Host names should be mapped to the free IP addresses on the DNS before assigning. All the five IPs should be on the same VLAN that is selected for deployment. 
. Content library template once uploaded should not be deleted post deployment as it will be used during reboots.
. In the case of multi-vCenter deployment where Custom CA certificates are mandatory, map the *Domain Name* on which the certificate is issued to the *Virtual IP*. Perform a ping check on the domain name to check whether the domain is getting resolved to the intended IP. The certificates should be created with domain name and IPAddress of the LoadBalancer IP.
. IPv4/IPv6 supported VLAN - Pure IPV6 is not supported. Mixed mode is supported with VLAN having both IPv6 and IPv4 addresses.
. NTP Server which is provided to the vCenter for time Sync.
. Static IP Configuration details for the Node or VM where the OVA is being deployed (Mandatory) and other details. 
.. vCenter hostname (vCenter where the OVA is deployed)
.. vCenter username (vCenter where the OVA is deployed)
.. vCenter password (vCenter where the OVA is deployed)
.. Resource pool
.. Data LIF (IPv4/IPv6)
.. Management LIF
.. ONTAP username
.. ONTAP password
.. SVM name
.. Protocol
.. virtual IPs for K8s control plane. 
.. HA / NON-HA drop down
.. Hostnames(list of hostnames)
.. IPAddresses (string)
.. Content library name
.. OVF template name
.. IPv6 gateway (optional)