---
permalink: deploy/sizing-requirements.html
sidebar: sidebar
keywords: ONTAP tools,Storage Replication Adapter
summary: 'Before deploying ONTAP tools for VMware vSphere, you should be familiar with the space requirements for the deployment package and some basic host system requirements.'
---
= Prerequisites for deploying ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying ONTAP tools for VMware vSphere, you should be familiar with the space requirements for the deployment package and some basic host system requirements.

You can use ONTAP tools for VMware vSphere with VMware vCenter Server Virtual Appliance (vCSA). You should deploy ONTAP tools for VMware vSphere on a supported vSphere client that includes ESXi system.

* *Installation package space requirements per node*
** 10 GB for thin provisioned installations
** 248 GB for thick provisioned installations

* *Host system sizing requirements per node*
Recommended memory as per the size of deployment and per node is as shown in the table below:

|===
|*Type of deployment*|*CPUs* |*Memory (GB)*
|Small (S)
|8
|16
|Medium (M)
|12
|24
|Large (L)
|16
|32
|===

== Deployment size guidelines for vVols datastore
 
|===

|*Deployment* | *Type* | *Number of vVols* |*Number of hosts* | *Number of VMs (8vVols per VM)* |*Number of vVols datastores* | *Protocol type*

|Easy Deployment |Small (S) |~12K| 32| ~1500  |4|NFS, iSCSI
|Easy Deployment |Medium (M) |~24K| 64| ~3000  |4|NFS, iSCSI
|High-Availability |Small (S) |~24K| 64| ~3000  |4|NFS, iSCSI
|High-Availability |Medium (M) |~50k| 128| ~6200 |6|NFS, iSCSI
|High-Availability |Large (L) |~100k| 256 (Total number of hosts from 5 vCenters) | ~12000 |12|NFS, iSCSI
|===

== Deployment size guidelines for NFS and VMFS datastore

|===

|*Deployment* |*Type* |*Number of hosts* |*Number of NFS/VMFS datastores (NFS3, NFS 4.1 , VMFS)* |*Recommended host settings* |*VAAI Plugin Installation*
|Easy Deployment 
|Medium (M) 
|64
|-  
|64 hosts concurrently 
|-

|High-Availability 
|Small (S) 
|64
|650 datastores mounted on 32 hosts: ~400 (NFS3), ~200(VMFS), ~50(NFS4.1 -No Kerberos)   
|64 hosts concurrently 
|64 hosts concurrently 

|High-Availability 
|Large (L) 
|350 
|970 datastores 
|128 hosts concurrently 
|200 hosts concurrently from single vCenter

|===

== Minimum storage and application requirements

|===
|Storage, host, and applications|Minimum version requirements

|ONTAP
|Latest patch release of ONTAP 9.12.1, 9.13.1, or 9.14.1

|ESXi hosts
|ESXi 7.0.3

|vCenter server
|vCenter 7.0U3

|VASA provider 
|3.0

|OVA Application 
|10.1

|===


The Interoperability Matrix Tool (IMT) contains the latest information about the supported versions of ONTAP, vCenter Server, ESXi hosts, and plug-in applications.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT[Interoperability Matrix Tool^]

== Additional deployment considerations
You should consider a few requirements while customizing the deployment of ONTAP tools.

=== Application user password

This is the password assigned to the administrator account. For security reasons, it is recommended that the password length is eight to thirty characters long and contains a minimum of one upper, one lower, one digit, and one special character.

=== Appliance maintenance console credentials

You should access the maintenance console by using the "`maint`" username. You can set the password for the "`maint`" user during deployment. You can use the Restart guest OS option available during VM restart in vCenter Server to change the password.

=== Appliance network properties

Specify a valid DNS hostname (unqualified) as well as the static IP address for ONTAP tools for VMware vSphere and the other network parameters. The IP addresses provided should be accessible from the VLAN network that you select during the deployment. DHCP is not supported for ONTAP tools for VMware vSphere 10.1 release. All these parameters are required for proper installation and operation.

