---
permalink: deploy/sizing-requirements.html
sidebar: sidebar
keywords: ONTAP tools,Storage Replication Adapter
summary: 'Before deploying ONTAP tools for VMware vSphere, you should be familiar with the space requirements for the deployment package and some basic host system requirements.'
---
= Prerequisites for deploying ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
Before deploying ONTAP tools for VMware vSphere, you should be familiar with the space requirements for the deployment package and some basic host system requirements.

You can use ONTAP tools for VMware vSphere with VMware vCenter Server Virtual Appliance (vCSA). You should deploy ONTAP tools for VMware vSphere on a supported vSphere client that includes ESXi system.

* *Installation package space requirements per node*
** 10 GB for thin provisioned installations
** 248 GB for thick provisioned installations

* *Host system sizing requirements per node*
Recommended memory as per the size of deployment and per node is as shown in the table below:

|===

|*Type of deployment*|*CPUs*|*Memory (GB)*
|Small (S)
|8
|16
|Medium (M)
|12
|24
|Large (L)
|16
|32
|===

Refer to link:../deploy/config-limits.html[Configuration limits to deploy ONTAP tools for VMware vSphere] for more details.

== Minimum storage and application requirements

|===
|Storage, host, and applications|Minimum version requirements

|ONTAP
|Latest patch release of ONTAP 9.12.1, 9.13.1, 9.14.1, and 9.15.1. 

|ESXi hosts
|ESXi 7.0.3

|vCenter server
|vCenter 7.0U3

|VASA provider 
|3.0

|OVA Application 
|10.2

|===

The Interoperability Matrix Tool (IMT) contains the latest information about the supported versions of ONTAP, vCenter Server, ESXi hosts, and plug-in applications.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT[Interoperability Matrix Tool^]
