---
permalink: protect/configure-placeholder-datastores.html
sidebar: sidebar
keywords:
summary: 'Configure a placeholder datastore to reserve space in the vCenter inventory at the recovery site for protected virtual machines (VMs). Placeholder datastores require minimal capacity, because placeholder VMs are small and typically use only a few hundred kilobytes.'
---
= Configure placeholder datastores
:icons: font
:imagesdir: ../media/

[.lead]
Configure a placeholder datastore to reserve space in the vCenter inventory at the recovery site for protected virtual machines (VMs). Placeholder datastores require minimal capacity, because placeholder VMs are small and typically use only a few hundred kilobytes.

.Before you begin

* Ensure that the protected and recovery sites are connected.
* Verify that resource mappings have been configured.

.Steps

. Log in to vCenter Server and select *Site Recovery* > *Sites*.
. Select your protected site and select *Manage*.
. Select *Placeholder Datastores* > *New* in the manage tab to create a new placeholder datastore.
. Select the appropriate datastore and select *OK*.
+
[NOTE]
Placeholder datastores may reside on local or remote storage, but they do not require replication.
. Repeat steps 3 to 5 to configure a placeholder datastore for the recovery site.
