---
permalink: protect/configure-on-srm-appliance.html
sidebar: sidebar
keywords:
summary: 'After deploying the VMware Live Site Recovery appliance, configure the Storage Replication Adapter (SRA) to enable disaster recovery management.'
---
= Configure SRA on the VMware Live Site Recovery appliance
:icons: font
:imagesdir: ../media/

[.lead]
After deploying the VMware Live Site Recovery appliance, configure the Storage Replication Adapter (SRA) to enable disaster recovery management.

Configuring SRA on the VMware Live Site Recovery appliance saves the ONTAP tools for VMware vSphere credentials within the appliance, enabling communication between VMware Live Site Recovery and SRA.

.Before you begin

* Ensure you have downloaded the _.tar.gz_ file from the https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab[NetApp Support Site].
* Ensure you have enabled SRA services in ONTAP tools Manager. For more information, refer the link:../manage/enable-service.html[Enable ONTAP tools for VMware vSphere services] section.
* Ensure you have added vCenter Servers to the ONTATP tools for VMware vSphere appliance. For more information, refer the link:../configure/add-vcenter.html[Add vCenter Servers] section.
* Ensure you have added storage backends to ONTAP tools for VMware vSphere. For more information, refer the link:../configure/add-storage-backend.html[Add storage backends] section.

.Steps
//On vSphere client menu, select NetApp ONTAP tools > Settings > Administrative Settings > Manage Capabilities > Enable Storage Replication Adapter (SRA) 
//Github issue 54

. On the VMware Live Site Recovery appliance screen, select *Storage Replication Adapter* > *New Adapter*.
. Upload the _.tar.gz_ file to VMware Live Site Recovery.
. Log in to the VMware Live Site Recovery appliance using an administrator account through an SSH client such as PuTTY.
. Switch to the root user using the command: `su root`
. Run the command `cd /var/log/vmware/srm` to navigate to the log directory.
. At the log location, enter the command to get the docker ID used by SRA: `docker ps -l`
. To log in to the container ID, enter the command: `docker exec -it -u srm <container id> sh`
. Configure VMware Live Site Recovery with ONTAP tools for VMware vSphere IP address and password using the command: `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <Application username> --otv-password <Application password> --vcenter-guid <VCENTER_GUID>`
[NOTE]
You need to provide the password value within single quotes to ensure that the Perl script does not read the special characters in the password as a delimiter of the input.
[NOTE]
You can set the application (VASA Provider/SRA) username and password in ONTAP tools Manager when enabling these services for the first time. These credentials are needed to register SRA with the VMware Live Site Recovery appliance.
// Github issue 100
. Rescan the adapters to confirm that the updated details appear on the VMware Live Site Recovery Storage Replication Adapters page.

*Results*
A confirmation message appears indicating that the storage credentials have been saved. SRA can now communicate with the SRA server using the specified IP address, port, and credentials.
