---
permalink: protect/enable-storage-replication-adapter.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.'
---
= Configure SRA to protect datastores
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.

.Before you begin

* You should have set up your vCenter Server instance and configured ESXi host.
* You should have deployed ONTAP tools for VMware vSphere.
* You should have downloaded the SRA Adapter `.tar.gz` file from the https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab[NetApp Support Site^].
* You should have the same custom SnapMirror schedules on both source and destination ONTAP clusters before you run the SRA workflows.
* link:../manage/enable-services.html[Enable ONTAP tools for VMware vSphere services] to enable the SRA capability.
// updated for [OTVDOC-181] - jani

.Steps

. Log in to the VMware Live Site Recovery appliance management interface using the URL: `\https://:<srm_ip>:5480`, and then go to Storage Replication Adapters in VMware VMware Live Site Recovery appliance management interface.
. Select *New Adapter*.
. Upload the _.tar.gz_ installer for the SRA plug-in to VMware Live Site Recovery.
. Rescan the adapters to verify that the details are updated on the VMware Live Site Recovery Storage Replication Adapters
page.

[NOTE]
After a failover, actions such as expand, mount, and delete might not be available for datastores. Perform datastore discovery to refresh and display the appropriate context menu actions.
//updated for OTVDOC-304 - jani

[NOTE]
After each reprotect operation, you must perform storage discovery on both sites.
// OTVDOC-315 - Jani
// In a new setup with SRA protection, reprotect workflow fails with a timeout error after an unplanned failover. You should run a test failover before doing an unplanned failover. This way, the system has the latest replication information. The same rule applies to fan-out scenarios. If ONTAP cluster A goes down and cluster B becomes the source for Automated Failover Duplex (AFD) and asynchronous, run a test between B and C to make sure the latest replication information is available.

// OTVDOC-316 - Jani
In a new setup with SRA protection, if you encounter issues with the reprotect workflow, ensure that all relevant replication information is up to date by performing test failovers as needed.  

In a fan-out scenario, after switching the AFD and asynchronous policies to site B, perform a test failover between B and C to update and verify the latest replication information.