---
permalink: protect/enable-storage-replication-adapter.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.'
---
= Configure SRA to protect datastores
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere provides the option to enable the SRA capability to configure disaster recovery.

.Before you begin

* You should have set up your vCenter Server instance and configured ESXi host.
* You should have deployed ONTAP tools for VMware vSphere.
* You should have downloaded the SRA Adapter `.tar.gz` file from the https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab[NetApp Support Site^].
* You should have the same custom SnapMirror schedules on both source and destination ONTAP clusters before you run the SRA workflows.
* link:../manage/enable-services.html[Enable ONTAP tools for VMware vSphere services] to enable the SRA capability.
// updated for [OTVDOC-181] - jani

.Steps

. Log in to the VMware Live Site Recovery appliance management interface using the URL: `\https://:<srm_ip>:5480`, and then go to Storage Replication Adapters in VMware VMware Live Site Recovery appliance management interface.
. Select *New Adapter*.
. Upload the _.tar.gz_ installer for the SRA plug-in to VMware Live Site Recovery.
. Rescan the adapters to verify that the details are updated on the VMware Live Site Recovery Storage Replication Adapters
page.

[NOTE]
After a failover, actions such as expand, mount, and delete might not be available for datastores. Perform datastore discovery to refresh and display the appropriate context menu actions.
//updated for OTVDOC-304 - jani

[NOTE]
After each reprotect operation, you must perform storage discovery on both sites.
// OTVDOC-315 - Jani
// OTVDOC-316 - Jani

In a new setup with SRA protection, always run a test failover before performing an unplanned failover. Skipping the test failover might cause the reprotect operation to fail.

In a fan-out configuration, after a SnapMirror Active Sync failover where the SnapMirror source changes to site B for Automated Failover Duplex and Asynchronous policies, run a test failover between sites B and C. Skipping this step may result in a failed reprotect operation.