---
permalink: protect/protect-multiple-ds.html
sidebar: sidebar
keywords:
summary: 'Granular datastore protection lets you select and group specific datastores for flexible protection. You can organize datastores from different storage virtual machines (SVMs) into separate protection groups, and a host cluster may include datastores from multiple SVMs.'
---
= Protect datastores in a cluster with ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can protect only certain datastores within a host cluster, rather than all datastores. With granular datastore protection, you can select and group specific datastores into separate protection groups. This approach gives you flexibility to tailor protection policies to your environment, even when a host cluster contains datastores from multiple SVMs.
// Configure granular datastore protection - this can be the heading of the main topic
.Before you begin
Make sure you meet these requirements before you protect a host cluster:

* Only VMFS datastores using iSCSI or FC protocols are eligible. vVols, NFS, NVMe/FC, and NVMe/TCP datastores are not supported.

##datastore eligibility criteria ##

.Steps

. Log in to the vSphere client.
. Right-click on a host cluster and select *NetApp ONTAP tools* > *Protect datastores*.
. Select the *Storage VM* in the cluster.
+
Datastores from the selected SVM are displayed. Only datastores provisioned on ONTAP 9.15.1 with iSCSI or FC protocols and mounted on the host cluster are shown.
. Select the datastores you want to protect and click *Next*.
. In the protection settings window, choose whether to protect the selected datastores in a new or existing protection group.
. If you want to create a new protection group for the selected datastores, select *Create new*.
.. Provide a name for the protection group. 
.. Select *Add Relationship*. 
.. In the *Add SnapMirror Relationship* window, select the *Target storage VM* and the *Policy* type.
+
The policy type can be Asynchronous or AutomatedFailOverDuplex. 
+
When you add the SnapMirror relationship as an AutomatedFailOverDuplex type policy, you must add the target storage VM as storage backend to the same vCenter where ONTAP tools for VMware vSphere is deployed.
+
In the AutomatedFailOverDuplex policy type, there are uniform and non-uniform host configurations. 
When you select the *uniform host configuration* toggle button, the host initiator group configuration is implicitly replicated on the target site. For more information, refer to link:../concepts/ontap-tools-concepts-terms.html[Key concepts and terms].
. If you choose to have a non-uniform host configuration, select the host access (source/target) for each host inside that cluster.
.. Select *Add*.
. Review the configuration in the *Summary* window and select *Protect*.
. To view the details of all the available protection groups, go to *NetApp ONTAP tools* > *Protection* > *Protection groups*.

A new protection group is created with the selected datastores and the SnapMirror relationship is added to that protection group. The system creates a vCenter task with job ID details and shows its progress in the recent tasks panel. This is an asynchronous task; the user interface shows only the request submission status and does not wait for the task to complete.

[NOTE]
====
To remove protection within one hour of creation, run storage discovery first.
====
//OTVDOC-312 update - Jani

//10.6 topic