---
permalink: protect/update-credentials.html
sidebar: sidebar
keywords: SRA credentials, updating
summary: 'For VMware Live Site Recovery to communicate with SRA, you should update SRA credentials on the VMware Live Site Recovery server if you have modified the credentials.'
---
= Update SRA credentials in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
For VMware Live Site Recovery to communicate with SRA, you should update SRA credentials on the VMware Live Site Recovery server if you have modified the credentials.

.Before you begin

You should have executed the steps mentioned in the topic link:../protect/configure-on-srm-appliance.html[Configuring SRA on VMware Live Site Recovery appliance].

.Steps

. Run the following commands to delete the cached ONTAP tools credentials from the VMware Live Site Recovery machine:
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
// updated for OTVDOC-207 - jani
.. `rm -rf *`
. Run the Perl command to configure SRA with the new credentials:
 .. `cd ..`
 .. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` You need to have a single quote around the password value. 
+
A success message confirming that the storage credentials are stored is displayed. SRA can communicate with the SRA server using the provided IP address, port, and credentials.

== Reconfigure vCenter in the VMware Live Site Recovery appliance after a certificate change

If the vCenter certificate changes, for example after a vCenter upgrade, you may encounter a thumbprint mismatch error on the Site Recovery extension. Perform the following steps to resolve it.

.Steps

. Reconfigure vCenter in the VMware Live Site Recovery appliance
.. Open the VMware Live Site Recovery appliance management interface in a browser: `\https://<SRM_IP>:5480`
.. Select the *Summary* tab.
.. Select *Reconfigure* for the vCenter Server connection.
+
This fetches and accepts the latest certificate thumbprint from vCenter.
. Reconnect site pairing (if the error persists)
+
If the thumbprint mismatch error persists after reconfiguration:

.. Log in to the vCenter user interface.
.. Navigate to the *Site Recovery* extension.
.. Locate the *Site Pairing* section.
.. Select *Reconnect* to re-establish the site pairing with the updated certificate.

// OTVDOC-361 for P2