---
permalink: protect/verify-the-replicated-storage-environment.html
sidebar: sidebar
keywords: SRA, storage replication adapter, storage discovery, SnapMirror, custom policy, array pairing, VMware Live Site Recovery
summary: 'You should verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter \(SRA\). The replicated storage system should be discoverable by both the protected site and the recovery site.'
---
= Verify replicated storage systems in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You should verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter (SRA). The replicated storage system should be discoverable by both the protected site and the recovery site.

.Before you begin

* You should have configured your storage system.
* You should have paired the protected site and recovery site by using the VMware Live Site Recovery array manager.
* You should have enabled FlexClone license and SnapMirror license before performing the test failover operation and failover operation for SRA.
* You should have the same SnapMirror policies and schedules on source and destination sites.
// updated for OTVDOC-186 - Jani
* If you are using custom SnapMirror policies with a custom schedule, you must configure the same schedule and policy on both the protected and recovery sites.
// OTVDOC-360 for P2
* If you are using custom SnapMirror policies (with either a default or custom schedule), you must perform storage discovery from ONTAP tools so that the new policy is recognized. Without this, SRA workflows, including test failover and failover, will fail. Perform storage discovery at the following points:
** After creating the custom policy on the recovery site.
** After a reprotect operation, which recreates the policy on the protected site.

.Steps

. Log in to your vCenter Server.
. Go to *Site Recovery* > *Array Based Replication*.
. Select the required Array Pair and verify the corresponding details.
+
The storage systems should be discovered at the protected site and recovery site with the status as *Enabled*.
