---
permalink: protect/verify-the-replicated-storage-environment.html
sidebar: sidebar
keywords:
summary: 'You should verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter \(SRA\). The replicated storage system should be discoverable by both the protected site and the recovery site.'
---
= Verify replicated storage systems in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You should verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter (SRA). The replicated storage system should be discoverable by both the protected site and the recovery site.

.Before you begin

* You should have configured your storage system.
* You should have paired the protected site and recovery site by using the VMware Live Site Recovery array manager.
* You should have enabled FlexClone license and SnapMirror license before performing the test failover operation and failover operation for SRA.
* You should have the same SnapMirror policies and schedules on source and destination sites.
// updated for OTVDOC-186 - Jani
* You should have performed storage discovery from ONTAP tools after creating a custom policy with a default schedule, and again after a reprotect operation creates the same policy on the recovery site, before running any SRA workflow.
* You should have the same custom schedule and policy configured on both the protected and recovery sites when using custom policies with a custom schedule.
// OTVDOC-360 for P2

.Steps

. Log in to your vCenter Server.
. Go to *Site Recovery* > *Array Based Replication*.
. Select the required Array Pair and verify the corresponding details.
+
The storage systems should be discovered at the protected site and recovery site with the Status as "`Enabled`".
