---
permalink: concepts/concept_ontap_tools_overview.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere is a collection of tools for lifecycle management of virtual machines. It integrates with VMware ecosystem and helps in provisioning, basic protection and disaster recovery of virtual machines.'
---
= ONTAP tools overview
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere is a collection of tools for lifecycle management of virtual machines. It integrates with VMware ecosystem and helps in provisioning, basic protection and disaster recovery of virtual machines.

ONTAP tools for VMware vSphere 10.1 release is a collection of horizontally scalable, event driven,
microservices deployed as an Open Virtual Appliance (OVA). It is packaged in various deployment form factors like OVA and Software as a service (SaaS) for on-prem. This release has REST API integration with ONTAP.

ONTAP tools for VMware vSphere consists of:

* Virtual machine functionality like basic protection and disaster recovery
* VASA Provider for VM granular management
* Storage policy-based management
