---
permalink: automation/reference_workflows.html
sidebar: sidebar
keywords: REST API categories
summary: 'The resources available through ONTAP tools REST API are organized in categories, as displayed on ONTAP tools API documentation page.'
---
= Workflows
:icons: font
:imagesdir: ../media/

[.lead]
A workflow is a sequence of one or more steps needed to accomplish a specific administrative task or goal.
The ONTAP tools workflows include the core steps and parameters you need to accomplish each task. They provide a starting point for customizing your ONTAP tools automation environment.

== Manage Storage threshold
// Need to add procedure from ontap tools shortcut Settings> Threshold Settings > Modify. Move this API to API section

Use the following Get threshold API to retrieve the configured storage threshold limits for volume and aggregate.

----
GET​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----

Examples:
Get the Storage thresholds per vCenter by vCenter guid
----
GET "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
----

Use the following PATCH configure alarm for volume and aggregate to generate notification when configured threshold limits are reached. 
----
PATCH​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----

Examples:
Update the Storage thresholds per vCenter by vCenter guid. Default limits are 80% for nearly-full and 90% for full.
Modifying all threshold settings
----
{{{}PATCH "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
Request Body
{
"volume":

{ "nearly_full_percent": 80, "full_percent": 90 }
,
"aggregate": {
"nearly_full_percent": 80,
"full_percent": 90
}
}{}}}{}
----

== Manage network access

Use the following API to add IP addresses for whitelisting:

----
patch /api/v1/vcenters/{vcguid}/settings/ip-whitelist
 
{
    value: string
}

GET /api/v1/vcenters/{vcguid}/settings/ip-whitelist
 
{
    value: string
}
---- 

== Delete vVols datastore


A vVols datastore exists as long as at least one FlexVol volume is available on the datastore. If you want to delete a vVols datastore in a HA cluster, you should first unmount the datastore from all hosts within the HA cluster, and then delete the residing _.vsphere-HA_ folder manually using the vCenter server user interface. 

*Steps*

Use the following API to delete vVols datastore. 
----
DELETE
​/virtualization​/api​/v1​/vcenters​/{vcguid}​/vvols​/datastores​/{moref}
----
Examples

* Delete vVols datastore and delete volumes from storage
----
  DELETE /api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-28?delete_volumes=true
----
[NOTE]
Delete vVols Datastore workflow deletes datastore-volumes if you have passed the delete_volume flag as true irrespective of if the datastore-volume is managed or not managed.

* Delete vVols datastore and do not delete volumes from storage
----  
  DELETE /api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-28?delete_volumes=false
----

Response:
----
{

    "id": "1889"

}
----

== Storage discovery

Discovery interval can be configured as part of the configuration map. Scheduled discovery runs for every 60 mins. The API given here is to run the discovery on demand for a given storage backend which is added in the local scope. 

Use the following API to run discovery:
----
POST
/virtualization/api/v1/vcenters/{vcguid}/storage-backends/{id}/discovery-jobs
----

[NOTE]
--
See link:../configure/onboard_svm.html[Onboard storage backend (SVM or Cluster)] section and get ID from post storage backend API response.
--

Discovery from this API endpoint is supported only for local scoped storage backends and not for the global scoped storage backends.
If the storage backend type is cluster, discovery implicitly runs for the child svms.
If the storage backend type is svm, discovery only runs for the selected svm.

Example:

To run discovery on a storage backend specified by ID
----
POST
/api/v1/vcenters/3fa85f64-5717-4562-b3fc-2c963f66afa6/storage-backends/74e85f64-5717-4562-b3fc-2c963f669dde/discovery-jobs
----

You need to pass x-auth for the API. You can generate this x-auth from the new API added under Auth in Swagger.
----
/virtualization/api/v1/auth/vcenter-login
----


== SVM aggregate mapping requirements

To use direct SVM credentials for provisioning datastores, internally ONTAP tools create volumes on the
aggregate specified in the datastores POST API. The ONTAP does not allow the creation of volumes on
unmapped aggregates on an SVM using direct SVM credentials. To resolve this, you need to map the SVMs
with the aggregates using the REST API or CLI as described here.
REST API:
----
PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485"
'{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}'
----

ONTAP CLI:
----
sti115_vsim_ucs630f_aggr1 vserver show-aggregates
AvailableVserver Aggregate State Size Type SnapLock
Type
svm_test sti115_vsim_ucs630f_aggr1
online 10.11GB vmdisk non-snaplock
----

== Onboard storage backend (SVM or Cluster) with vCenter

Use the following API to onboard the storage backends and map the SVM to vCenter locally.  See link:../configure/task_configure_user_role_and_privileges.html[Configure user roles and privileges] section for the ONTAP SVM user privileges. 

----
POST /virtualization/api/v1/vcenters/<vcguid>/storage-backends

{
     "hostname_or_ip": "172.21.103.107",
     "username": "svm11",
     "password": "xxxxxx"
   }
----
[NOTE]
The ID from the above API response is used in discovery.

You need to pass x-auth for the API. You can generate this x-auth from the new API added under Auth in Swagger.
----
/virtualization/api/v1/auth/vcenter-login
----

== Create vVols datastore

You can create vVols datastore with new volumes or with existing volumes. You can also create vVols datastore with the combination of existing volumes and new volumes.
[NOTE]
Check to ensure root aggregates are not mapped to SVM.

You need to pass x-auth for the API. You can generate this x-auth from the new API added under Auth in Swagger.
----
/virtualization/api/v1/auth/vcenter-login
----
. Create vVols datastore with new volume.
  Get Aggregate id, storage_id(SVM uuid) using ONTAP REST API. 
+
----
POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
----
+
Use the following URI to check the status:
+
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Request Body for NFS datastore
+
----    
{
   "name":"nfsds1",
   "protocol":"nfs",
   "platform_type":"aff",
   "moref":"domain-c8",
   "volumes":[
      {
         "is_existing":false,
         "name":"vol_nfs_pvt",
         "size_in_mb":2048000,
         "space_efficiency":"thin",
         "aggregate":{
            "id":"d7078b3c-3827-4ac9-9273-0a32909455c2"
         },
         "qos":{
            "min_iops":200,
            "max_iops":5000
         }
      }
   ],
   "storage_backend":{
      "storage_id":"654c67bc-0f75-11ee-8a8c-00a09860a3ff"
   }
}
----
+
Request body for iSCSI datastore:
----
{
   "name" : "iscsi_custom",
   "protocol" : "iscsi",
   "platform_type": "aff",
   "moref" : "domain-c8",
   "volumes" : [
       {
           "is_existing" : false,
           "name" : "iscsi_custom",
           "size_in_mb" : 8034,
           "space_efficiency" : "thin",
           "aggregate" : {
               "id" : "54fe5dd4-e461-49c8-bb2d-6d62c5d75af2"
           }
       }
   ],
   "custom_igroup_name": "igroup1",
   "storage_backend": {
                       "storage_id": "eb9d33ab-1960-11ee-9506-00a0985c6d9b"    }
}
----
. Create vVols datastore with existing volumes. 
+
Get aggregate_id and volume_id using ONTAP REST API. 
+
----
     POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
----
Request Body
----
     {
    "name" : "nfsds2",
    "protocol" : "nfs",
    "platform_type": "aff",
    "moref" : "domain-c8",
    "volumes" : [
        {
              "is_existing": true,
              "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
            }
    ],
    "storage_backend": {
                        "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
 
}
----
== Mount and unmount vVols datastore
You can mount a VMware Virtual Volumes (vVols) datastore to one or more additional hosts by using the Mount vVols Datastore dialog box. Mounting the datastore provides storage access to additional hosts. You can also unmount vVols datastore.

Use the following API to mount or unmount a vVols datastore.
You need to pass x-auth for the API. You can generate this x-auth from the new API added under Auth in Swagger.
----
/virtualization/api/v1/auth/vcenter-login
----
----
PATCH
/virtualization/api/v1/vcenters/{vcguid}/vvols/datastores/{moref}/hosts
----
Get vVol datastore moref from vCenter.

Request Body
----
{
  "operation": "mount",
  "morefs": [
    "host-7044"
  ],
}
----

Examples:
* Mount on additional host

Use the following API to mount on additional host:

----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body 
     {
      "operation": "mount",
      "morefs": ["host-13"],
     }
----

* Unmount on additional host

Use the following API to unmount on additional host:

----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body 
     {
      "operation": "unmount",
      "morefs": ["host-13"],
     }
----

== Expand or shrink Storage of vVol Datastore
There are APIs to increase or decrease the available storage.

*Steps*

Use the following API to expand or shrink the vVols datastore:
----
PATCH
​/virtualization​/api​/v1​/vcenters​/{vcguid}​/vvols​/datastores​/{moref}​/volumes
----

Examples

* Modify vVols datastore for add new volume
----  
  PATCH virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/volumes

    Request Body
   {
    "operation": "grow",
    "volumes": [{
        "is_existing": false,
        "name": "exp3",
        "size_in_mb": 51200,
        "space_efficiency": "thin",
        "aggregate": {
            "id": "1466e4bf-c6d6-411a-91d5-c4f56210e1ab"
        },
        "storage_backend": {
            "storage_id": "13d86e4f-1fb1-11ee-9509-005056a75778"
        },
        "qos": {
            "max_iops": 5000
        }
    }]
}
----
* Modify vVols datastore for add existing volume
----
  PATCH virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/volumes

    Request Body
    {
      "operation": "grow",
      "volumes": [{
        "is_existing": true,
        "id": "vfded9ad-6bsd-4c9e-b44g-691250bfe2sd"
      }]
    }
----
* Modify vVols datastore for remove volume and delete volume from storage
----
  PATCH virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/volumes?delete_volumes=true

    Request Body
    {
      "operation": "shrink",
      "volumes": [{
        "is_existing": true,
        "id": "vfded9ad-6bsd-4c9e-b44g-691250bfe2sd"
      }]
    }
----
* Modify vVols datastore for remove volume and do not delete volume from storage
----
  PATCH virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/volumes?delete_volumes=false

    Request Body
    {
      "operation": "shrink",
      "volumes": [{
        "is_existing": true,
        "id": "vfded9ad-6bsd-4c9e-b44g-691250bfe2sd"
      }]
    }
----