---
permalink: sc-automation/reference_supported_rest_apis.html
sidebar: sidebar
keywords: REST API categories
summary: 'The resources available through the SnapCenter REST API are organized in categories, as displayed on the SnapCenter API documentation page.'
---
= REST APIs supported for ONTAP tools plug-in
:icons: font
:imagesdir: ../media/

[.lead]
The resources available through the ONTAP tools REST API are organized in categories, as displayed on the ONTAP tools API documentation page. A brief description of each of the resources with the base resource paths is presented below, along with additional usage considerations where appropriate.

== Manage Storage threshold
// Need to add procedure from ontap tools shortcut Settings> Threshold Settings > Modify. Move this API to API section

Use the following Get threshold API to retrieve the configured storage threshold limits for volume and aggregate.

----
GET​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----

Examples:
Get the Storage thresholds per vcenter by vcenter guid
----
GET "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
----

Use the following PATCH configure alarm for volume and aggregate to generate notification when configured threshold limits are reached. 
----
PATCH​/virtualization​/api​/v1​/vcenters​/{vcguid}​/storage-thresholds
----

Examples:
Update the Storage thresholds per vcenter by vcenter guid. Default limits are 80% for nearly-full and 90% for full.
Modifying all threshold settings
----
{{{}PATCH "/api/v1/vcenters/beded9ad-6bbb-4c9e-b4c6-691250bfe2da/storage-thresholds"
Request Body
{
"volume":

{ "nearly_full_percent": 80, "full_percent": 90 }
,
"aggregate": {
"nearly_full_percent": 80,
"full_percent": 90
}
}{}}}{}
----

== Manage network access

Use the following API to add IP addresses for whitelisting:

----
patch /api/v1/vcenters/{vcguid}/settings/ip-whitelist
 
{
    value: string
}
 
GET /api/v1/vcenters/{vcguid}/settings/ip-whitelist
 
{
    value: string
}
---- 
