---
permalink: configure/add-storage-backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Add a storage backend
:icons: font
:imagesdir: ../media/

[.lead]

Adding a storage backend enables you to onboard an ONTAP cluster.

*About this task*

In a multitenant setup where vCenter acts as the tenant with an associated SVM, use ONTAP tools Manager to add the cluster. Associate the storage backend with the vCenter Server to map the storage backend globally. First, onboard the desired Storage Virtual Machines (SVMs) in vCenter tenant. This allows the SVM user to provision vVols datastores. You can then add storage in vCenter using the SVM.

To add local storage backends, use cluster or SVM credentials through the ONTAP tools user interface. These storage backends are limited to a single vCenter.  When using cluster credentials, the associated SVMs automatically map to the vCenter to manage vVols or VMFS datastores.  For VMFS workflows, including SRA, ONTAP tools supports SVM credentials without requiring a globally mapped cluster.

When MetroCluster support is enabled in the ONTAP system, onboard both source and destination clusters configured with MetroCluster as local or global storage backends.

// 10.5 updates -Jani rewrote the intro and added the last para. Added before you begin section.
.Before you begin
Before adding the storage backend, obtain the certificate from the ONTAP administrator. Ensure it is a valid certificate with the updated Subject Alternative Name (SAN) field. ONTAP systems require SAN fields in the certificate to identify the cluster and SVM management LIFs.

[role="tabbed-block"]
====

.Using ONTAP tools Manager
--

[NOTE]
In a multi-tenant setup, you can add a storage backend cluster globally and SVM locally to use SVM user credentials.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address or FQDN, username, and password details.
[NOTE]
IPv4 and IPv6 address management LIFs are supported.
. In the advanced options, you can fetch the ONTAP cluster certificates automatically, which requires you to authorize the certificate or manually upload the certificate by browsing to its location.
. If the added storage backend is part of the MetroCluster configuration, *Add MetroCluster peer* screen appears. Select *Add peer* to add the peer storage backend.
[NOTE]
When ONTAP systems perform a switchover, run the ONTAP tools discovery manually.

// 10.5 updates -Jani.
--

.Using vSphere client user interface
--

[NOTE]
When configuring a storage backend through the vSphere client user interface, it is important to note that the vVols datastores don't support the direct addition of an SVM user.

. Log in to the vSphere client.
. In the shortcuts page, select *NetApp ONTAP tools* under the plug-ins section.
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address, username, password, and port details.
[NOTE]
To add an SVM user directly, you can add cluster-based credentials and IPv4 and IPv6 address management LIFs or provide SVM-based credentials with an SVM management LIF.
. In the advanced options, you can fetch the ONTAP cluster certificates automatically, which requires you to authorize the certificate or manually upload the certificate by browsing to its location. 
. If the added storage backend is part of the MetroCluster configuration, *Add MetroCluster peer* screen appears. Select *Add peer* to add the peer storage backend.
[NOTE]
When ONTAP systems perform a switchover, run the ONTAP tools discovery manually.

// 10.5 updates -Jani. For MCC and certificate feature updates.
.What’s next?

The list gets refreshed, and you can see the newly added storage backend in the list.

--
====
In the *Storage backends* page, you can see the newly added storage backend in the list. The certificate expiry date column shows a warning if the certificate is about to expire in 30 days or less. After the certificate expiry date is reached, the storage backend is marked as unknown as ONTAP tools looses communication with storage backends. 

.Related information

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html[Configuring the clusters into a MetroCluster configuration]
