---
permalink: configure/add-vcenter.html
sidebar: sidebar
keywords:
summary: 'Add vCenter Server instances to ONTAP tools for VMware vSphere to configure, manage, and protect your virtual datastores in your vCenter Server environment.'
---
= Add vCenter Server instances to ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Add vCenter Server instances to ONTAP tools for VMware vSphere to configure, manage, and protect your virtual datastores in your vCenter Server environment. When you add multiple vCenter Server instances, Custom CA certificates are required for secure communication between ONTAP tools and each vCenter Server.
//OTVDOC-271 updates -Jani

.About this task

ONTAP tools integrates with vCenter Server to perform storage tasks like provisioning, snapshots, and data protection directly from the vSphere client.

.Before you begin

* Ensure the vCenter Server certificate includes a valid Subject Alternative Name (SAN) extension with both DNS and IP address entries. For example:
+
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
If the certificate does not include a SAN extension, or if the SAN extension does not contain the correct DNS or IP address values, ONTAP tools operations may fail due to certificate validation errors.
* The Primary Network Identifier (PNID) of the vCenter Server must be included in the SAN details. The PNID and DNS name should be identical and resolvable in DNS.
* It is recommended to deploy vCenter Server using its fully qualified domain name (FQDN), ensuring the SAN in the certificate includes DNS Name=machine_FQDN for optimal compatibility and support.
* For more information, refer to VMware documentation:
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html[vSphere Certificate Requirements for Different Solution Paths]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html[Replace vCenter Machine SSL certificate Custom Certificate Authority Signed Certificate]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html[Error: Subject Alternate Name (SAN) field does not contain the PNID. Please provide a valid certificate]

[NOTE]
====
If FQDN is not available, you can set the PNID to the IP address and include the IP address in the SAN. However, this is not recommended by VMware.
====

.Steps

. Open a web browser and go to the URL: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *vCenters* > *Add* to onboard the vCenter Server instances. Provide your vCenter IP address or hostname, username, password, and port details.
// 10.5 updates -Jani
. In advanced options, fetch the vCenter Server certificate automatically (authorize it) or upload it manually. 
+
[NOTE]
You don’t need an admin account to add vCenter instances to ONTAP tools. You can create a custom role without the admin account with limited permissions. Refer to link:../concepts/rbac-vcenter-use.html[Use vCenter Server RBAC with ONTAP tools for VMware vSphere 10] for details.
// updated for OTVDOC-265

Adding a vCenter Server instance to ONTAP tools automatically triggers the following actions:

* ONTAP tools registers the vCenter client plug-in as a remote plug-in.
* Custom privileges for the plug-ins and APIs are applied to the vCenter Server instance.
* Custom roles are created to manage the users.
* The plug-in appears as a shortcut on the vSphere user interface.
