---
permalink: configure/add-storage-backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Add a storage backend
:icons: font
:imagesdir: ../media/

[.lead]

Adding a storage backend enables you to onboard an ONTAP cluster.

*About this task*

To add a storage backend to a globally scoped cluster in a multi-tenant architecture, add the storage backend using the ONTAP tools Manager. After adding the storage backend to the global cluster, you must associate the cluster with the desired vCenter tenants. The vCenter tenant must onboard the desired Storage Virtual Machines (SVMs). This enables an SVM user to provision vVols datastore. You can add storage in vCenter using the SVM.

To add a storage backend to a locally scoped cluster, add your ONTAP systems directly using the ONTAP tools plug-in on the vCenter server.

[role="tabbed-block"]
====

.Using ONTAP tools Manager
--

[NOTE]
In a multi-tenant setup, you can add a storage backend cluster globally and SVM locally to use SVM user credentials.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address or FQDN, username, and password details.
[NOTE]
IPv4 and IPv6 address management LIFs are supported.

--

.Using vSphere client user interface
--

[NOTE]
When you add a storage backend using the vSphere client user interface, the vVols datastore does not support directly adding an SVM user.

. Log in to the vSphere client.
. In the shortcuts page, select *NetApp ONTAP tools* under the plug-ins section.
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address, username, password, and port details.
[NOTE]
To add an SVM user directly, you can add cluster-based credentials and IPv4 and IPv6 address management LIFs or provide SVM-based credentials with an SVM management LIF.

.What’s next?

The list gets refreshed, and you can see the newly added storage backend in the list.

--
====