---
permalink: configure/add-storage-backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Add a storage backend
:icons: font
:imagesdir: ../media/

[.lead]

Adding a storage backend enables you to onboard an ONTAP cluster.

*About this task*

Add storage backend to an ONTAP cluster. For multitenancy setups where vCenter acts as the tenant with associated SVM, use ONTAP tools Manager to add the cluster.  After adding the storage backend to the global cluster, you must associate the cluster with the desired vCenter tenants. The vCenter tenant must onboard the desired Storage Virtual Machines (SVMs). This enables an SVM user to provision vVols datastore. You can add storage in vCenter using the SVM.

To add a storage backend to a local cluster, use the ONTAP tools plug-in on the vCenter server.

link:../concepts/ontap-tools-concepts-terms.html[Key concepts and terms] provides more information about the terms used in this section.

[role="tabbed-block"]
====

.Using ONTAP tools Manager
--

[NOTE]
In a multi-tenant setup, you can add a storage backend cluster globally and SVM locally to use SVM user credentials.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address or FQDN, username, and password details.
[NOTE]
IPv4 and IPv6 address management LIFs are supported.

--

.Using vSphere client user interface
--

[NOTE]
When configuring a storage backend through the vSphere client user interface, it is important to note that the vVols datastore does not support the direct addition of an SVM user.

. Log in to the vSphere client.
. In the shortcuts page, select *NetApp ONTAP tools* under the plug-ins section.
. Select *Storage Backends* from the sidebar.
. Add the storage backend and provide the server IP address, username, password, and port details.
[NOTE]
To add an SVM user directly, you can add cluster-based credentials and IPv4 and IPv6 address management LIFs or provide SVM-based credentials with an SVM management LIF.

.What’s next?

The list gets refreshed, and you can see the newly added storage backend in the list.

--
====