---
permalink: configure/add_storage_backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Add storage backend
:icons: font
:imagesdir: ../media/

[.lead]

Storage backends are systems that the ESXi hosts use for data storage.

*About this task*

This task helps you to onboard the ONTAP cluster. When you add storage backend using the ONTAP tools Manager UI, the storage backend is added to the global cluster. Associate the global cluster with vCenter to enable direct SVM for vVol provisioning.

When you add storage backend using the vCenter UI, direct SVM does not support vVols.

== Add storage backend using ONTAP tools Manager UI
*Steps*

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Select *Add*. 
. Provide the Server IP Address or FQDN, Username, and Password details and select *Add*.
[NOTE]
IPV4 and IPV6 management LIFs are supported. Direct SVM based credential with management LIFs are also supported.

== Add storage backend using vCenter UI:
. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment.
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select *ADD*.
. In the *Add Storage Backend* window, provide the Server IP Address, Username, Password, and Port details and click *ADD*
[NOTE]
You can add either cluster based credentials and IPV4 and IPV6 management LIFs or you can provide SVM based credentials with management LIF of SVM to add direct SVM.

The list gets refreshed and you can see the newly added storage backend in the list.
You can check the status of the operation in the Recent Tasks pane.
