---
permalink: configure/add_storage_backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Add storage backend
:icons: font
:imagesdir: ../media/

[.lead]

Storage backends are systems that the ESXi hosts use for data storage.

*About this task*

This task helps you to onboard the ONTAP cluster. When you add storage backend using ONTAP tools Manager UI, the storage backend is added to the global cluster. Associate the global cluster with vCenter to enable direct SVM for vVols datastore provisioning.

[NOTE]
When you add storage backend using the vSphere client  UI, vVols datastore does not support direct SVM.

== Add storage backend using ONTAP tools Manager UI

[NOTE]
Storage backend is global when added from ONTAP tools Manager or commons APIs and they are local when added from the vCenter APIs.
Example: For multi-tenant setup, you can add storage backend (cluster) globally and SVM locally to use direct SVM credentials.

*Steps*

. Launch ONTAP tools Manager UI using `\https://loadBalanceIP:8443/virtualization/ui/` from the browser. 
. Log in with ONTAP tools administrator credentials provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Select *Add*. 
. Provide the Server IP Address or FQDN, Username, and Password details and select *Add*.
[NOTE]
IPV4 and IPV6 management LIFs are supported. Direct SVM based credential with management LIFs are also supported.

== Add storage backend using vSphere client UI:
. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select *ADD*.
. In the *Add Storage Backend* window, provide the Server IP Address, Username, Password, and Port details and click *ADD*
[NOTE]
You can add either cluster based credentials and IPV4 and IPV6 management LIFs or you can provide SVM based credentials with management LIF of SVM to add direct SVM.

The list gets refreshed and you can see the newly added storage backend in the list.
