---
permalink: configure/add_vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are the central management platforms that allow you to control hosts, virtual machines (VM), and storage backends.'
---
= Add vCenter
:icons: font
:imagesdir: ../media/

[.lead]
vCenters are the central management platforms that allow you to control hosts, virtual machines (VM), and storage backends.

*About this task*

You can add and manage multiple vCenters with one instance of ONTAP tools for VMware vSphere.

*Steps*

. Launch `\https://loadBalanceIP:8443/virtualization/ui/` from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Select *ADD* to onboard vCenters with vCenter IP Address/Hostname, username, password, and port. 

When you add vCenters, the following actions are performed automatically:
* Plug-in is registered
* Custom privileges for the plug-ins and APIs are pushed to the vCenter
* Custom roles are created to manage the users.  

See link:../configure/task_configure_user_role_and_privileges.html[List of minimum privileges required for non-admin global scoped cluster user].  


