---
permalink: configure/configure-user-role-and-privileges.html
sidebar: sidebar
keywords: user roles
summary: 'You can configure new user roles for managing storage backends using the JSON file provided with ONTAP tools for VMware vSphere and ONTAP System Manager.'
---
= Configure ONTAP user roles and privileges
:icons: font
:imagesdir: ../media/

[.lead]
You can configure new user roles and privileges for managing storage backends using the JSON file provided with ONTAP tools for VMware vSphere and ONTAP System Manager.

*What you'll need*

* You should have downloaded the ONTAP privileges file from ONTAP tools for VMware vSphere using _\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip_.
* You should have downloaded the ONTAP Privileges file from ONTAP tools using `\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip`.
+
[NOTE]
You can create users at cluster or directly at storage virtual machines (SVMs) level. You can also create users without using the user_roles.json file and if done so, you need to have a minimum set of privileges at SVM level.

* You should have logged in with administrator privileges for the storage backend.

*Steps*

. Extract the downloaded _\https://<loadbalancerIP>:8443/virtualization/user-privileges/users_roles.zip_ file.
. Access ONTAP System Manager using the cluster management IP address of the cluster.
. Log in as the cluster or SVM user.
. Select *Cluster* > *Settings* > *Users and Roles* pane.
. Select *Add* under Users.
. In the *Add User* dialog box, select *Virtualization products*.
. *Browse* to select and upload the ONTAP Privileges JSON file.
+
The Product field is auto populated.

. Select the required capability from the product capability drop-down menu.
+
The *Role* field is auto populated based on the product capability selected.

. Enter the required username and password.
. Select the privileges (Discovery, Create Storage, Modify Storage, Destroy Storage, NAS/SAN Role) required for the user, and then click *Add*.

The new role and user are added, and you can see the detailed privileges under the role that you have configured.
// edited for 10.0 release

NOTE: The uninstall operation does not remove ONTAP tools roles but removes the localized names for the ONTAP tools specific privileges and appends the prefix `XXX missing privilege` to them. When you reinstall ONTAP tools for VMware vSphere or upgrade to a newer version, all the standard ONTAP tools for VMware vSphere roles and ONTAP tools-specific privileges are restored.

== SVM aggregate mapping requirements

To use SVM user credentials for provisioning datastores, internally ONTAP tools for VMware vSphere creates volumes on the aggregate specified in the datastores POST API. The ONTAP does not allow the creation of volumes on unmapped aggregates on an SVM using SVM user credentials. To resolve this, you need to map the SVMs with the aggregates using the ONTAP REST API or CLI as described here.

REST API:

----
PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}' 
----

ONTAP CLI:

----
sti115_vsim_ucs630f_aggr1 vserver show-aggregates                                        AvailableVserver        Aggregate      State         Size Type    SnapLock Type-------------- -------------- ------- ---------- ------- --------------svm_test       sti115_vsim_ucs630f_aggr1                               online     10.11GB vmdisk  non-snaplock
----

== Create ONTAP user and role manually

Follow the instructions in this section to create the user and roles manually without using the JSON file.

. Access ONTAP System Manager using the cluster management IP address of the cluster.
. Log in as the cluster or SVM user.
. Select *Cluster* > *Settings* > *Users and Roles* pane.
. Create Roles:
.. Select *Add* under *Roles* table.
.. Enter the *Role name* and *Role Attributes* details. 
+
Add the *REST API Path* and the respective access from the drop down.
.. Add all the needed APIs and save the changes.
. Create Users:
.. Select *Add* under *Users* table.
.. In the *Add User* dialog box, select *System Manager*.
.. Enter the *Username*.
.. Select *Role* from the options created in the *Create Roles* step above.
.. Enter the applications to give access to and the authentication method. ONTAPI and HTTP are the required applications, and the authentication type is *Password*. 
.. Set the *Password for the User* and *Save* the user.
 

=== List of minimum privileges required for non-admin global scoped cluster user

The minimum privileges required for non-admin global scoped cluster user created without using the users JSON file are listed in this section. 
If a cluster is added in local scope, it is recommended to use the JSON file to create the users, as ONTAP tools for VMware vSphere requires more than just the Read privileges for provisioning on ONTAP.

Using APIs:

|===

|API|Access level| Used for

|/api/cluster |Read-Only |Cluster Configuration Discovery
|/api/cluster/licensing/licenses |Read-Only |License Check for Protocol specific licenses
|/api/cluster/nodes	|Read-Only	|Platform type discovery
|/api/storage/aggregates	|Read-Only	|Aggregate space check during Datastore/Volume provisioning
|/api/storage/cluster	|Read-Only	|To get the Cluster level Space and Efficiency Data
|/api/storage/disks	|Read-Only	|To get the Disks associated in an Aggregate
|/api/storage/qos/policies	|Read/Create/Modify	|QoS and VM Policy management
|/api/svm/svms	|Read-Only	|To get SVM configuration in the case the Cluster is added locally.
|/api/network/ip/interfaces |Read-Only |Add Storage Backend - To identify the management LIF scope is Cluster/SVM
|/api |Read-Only | Cluster users should have this privilege to get the correct storage backend status. Otherwise, ONTAP tools Manager shows "unknown" storage backend status.
|===
 

=== Create ONTAP tools for VMware vSphere ONTAP API based cluster scoped user

// 10.3 updates OTVDOC-163 - jani
[NOTE]
You need discovery, create, modify, and destroy Privileges to perform PATCH operations and automatic rollback in case of failure on datastores. Lack of these all these privileges together leads to workflow disruptions and cleanup issues.

Creating ONTAP tools for VMware vSphere ONTAP API based user with discovery, create storage, modify storage, destroy storage privileges enables initiating discoveries and manage ONTAP tools workflows.

To create a cluster scoped user with all privileges mentioned above, run the following commands:

_security login rest-role create -role <role-name> -api /api/application/consistency-groups -access all_

_security login rest-role create -role <role-name> -api /api/private/cli/snapmirror -access all_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/export-policies -access all_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystem-maps -access all_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystems -access all_

_security login rest-role create -role <role-name> -api /api/protocols/san/igroups -access all_

_security login rest-role create -role <role-name> -api /api/protocols/san/lun-maps -access all_

_security login rest-role create -role <role-name> -api /api/protocols/san/vvol-bindings -access all_

_security login rest-role create -role <role-name> -api /api/snapmirror/relationships -access all_

_security login rest-role create -role <role-name> -api /api/storage/volumes -access all_

_security login rest-role create -role <role-name> -api "/api/storage/volumes/*/snapshots" -access all_

_security login rest-role create -role <role-name> -api /api/storage/luns -access all_

_security login rest-role create -role <role-name> -api /api/storage/namespaces -access all_

_security login rest-role create -role <role-name> -api /api/storage/qos/policies -access all_

_security login rest-role create -role <role-name> -api /api/cluster/schedules -access read_create_

_security login rest-role create -role <role-name> -api /api/snapmirror/policies -access read_create_

_security login rest-role create -role <role-name> -api /api/storage/file/clone -access read_create_

_security login rest-role create -role <role-name> -api /api/storage/file/copy -access read_create_

_security login rest-role create -role <role-name> -api /api/support/ems/application-logs -access read_create_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/services -access read_modify_

_security login rest-role create -role <role-name> -api /api/cluster -access readonly_

_security login rest-role create -role <role-name> -api /api/cluster/jobs -access readonly_

_security login rest-role create -role <role-name> -api /api/cluster/licensing/licenses -access readonly_

_security login rest-role create -role <role-name> -api /api/cluster/nodes -access readonly_

_security login rest-role create -role <role-name> -api /api/cluster/peers -access readonly_

_security login rest-role create -role <role-name> -api /api/name-services/name-mappings -access readonly_

_security login rest-role create -role <role-name> -api /api/network/ethernet/ports -access readonly_

_security login rest-role create -role <role-name> -api /api/network/fc/interfaces -access readonly_

_security login rest-role create -role <role-name> -api /api/network/fc/logins -access readonly_

_security login rest-role create -role <role-name> -api /api/network/fc/ports -access readonly_

_security login rest-role create -role <role-name> -api /api/network/ip/interfaces -access readonly_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/kerberos/interfaces -access readonly_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/interfaces -access readonly_

_security login rest-role create -role <role-name> -api /api/protocols/san/fcp/services -access readonly_

_security login rest-role create -role <role-name> -api /api/protocols/san/iscsi/services -access readonly_

_security login rest-role create -role <role-name> -api /api/security/accounts -access readonly_

_security login rest-role create -role <role-name> -api /api/security/roles -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/aggregates -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/cluster -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/disks -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/qtrees -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/quota/reports -access readonly_

_security login rest-role create -role <role-name> -api /api/storage/snapshot-policies -access readonly_

_security login rest-role create -role <role-name> -api /api/svm/peers -access readonly_

_security login rest-role create -role <role-name> -api /api/svm/svms -access readonly_

Additionally, for ONTAP Versions 9.16.0 and above run the following command:

_security login rest-role create -role <role-name> -api /api/storage/storage-units -access all_

=== Create ONTAP tools for VMware vSphere ONTAP API based SVM scoped user

To create a SVM scoped user with all the privileges, run the following commands:

_security login rest-role create -role <role-name> -api /api/application/consistency-groups -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/private/cli/snapmirror -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/export-policies -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystem-maps -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/subsystems -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/san/igroups -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/san/lun-maps -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/san/vvol-bindings -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/snapmirror/relationships -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/volumes -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api "/api/storage/volumes/*/snapshots" -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/luns -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/namespaces -access all -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/cluster/schedules -access read_create -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/snapmirror/policies -access read_create -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/file/clone -access read_create -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/file/copy -access read_create -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/support/ems/application-logs -access read_create -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/services -access read_modify -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/cluster -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/cluster/jobs -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/cluster/peers -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/name-services/name-mappings -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/network/ethernet/ports -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/network/fc/interfaces -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/network/fc/logins -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/network/ip/interfaces -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nfs/kerberos/interfaces -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/nvme/interfaces -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/san/fcp/services -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/protocols/san/iscsi/services -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/security/accounts -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/security/roles -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/qtrees -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/quota/reports -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/storage/snapshot-policies -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/svm/peers -access readonly -vserver <vserver-name>_

_security login rest-role create -role <role-name> -api /api/svm/svms -access readonly -vserver <vserver-name>_

Additionally, for ONTAP Versions 9.16.0 and above run the following command:

_security login rest-role create -role <role-name> -api /api/storage/storage-units -access all -vserver <vserver-name>_

To create a new API based user using the above created API based roles, run the following command:

_security login create -user-or-group-name <user-name> -application http -authentication-method password -role <role-name> -vserver <cluster-or-vserver-name>_

Example: 

_security login create -user-or-group-name testvpsraall -application http -authentication-method password -role OTV_10_VP_SRA_Discovery_Create_Modify_Destroy -vserver C1_sti160-cluster_

To unlock the account, to enable access to the management interface run the following command:

_security login unlock -user <user-name> -vserver <cluster-or-vserver-name>_

Example: 

_security login unlock -username testvpsraall -vserver C1_sti160-cluster_