---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere checks and sets the ESXi host multipathing settings and HBA timeout settings that work best with NetApp storage systems.'
---
= Configure ESXi server multipath and timeout settings
:icons: font
:imagesdir: ../media/

[.lead]
Configuring ESXi server multipath and timeout settings ensures high availability and data integrity by allowing to seamlessly switch to a backup storage path if a primary path fails. 

ONTAP tools for VMware vSphere checks and sets the ESXi host multipath settings and HBA timeout settings that work best with NetApp storage systems.


*About this task*

Depending on your configuration and system load, this process might take a long time. The task progress is displayed in the Recent Tasks panel. 

.Steps

. From the VMware vSphere Web client home page, select *Hosts and Clusters*.
. Right-click a host and select *NetApp ONTAP tools* > *Update host data*.
. On the shortcuts page of the VMware vSphere Web client, select *NetApp ONTAP tools* under the plug-ins section.
. Go to the *ESXi Host compliance* card in the overview (dashboard) of the ONTAP tools for VMware vSphere plug-in.
. Select *Apply Recommended Settings* link.
. In the *Apply recommended host settings* window, select the hosts you want to update to comply with NetApp recommended settings and select *Next*.
+
[NOTE]
You can expand the ESXi host to see the current values.
. In the settings page, select the recommended values as required.
. In the summary pane, check the values and select *Finish*. You can track the progress in the recent task panel.