---
permalink: configure/create_vvols_datastore.html
sidebar: sidebar
keywords:
summary: 'You can create vVols datastore with new volumes or with existing volumes. You can also create vVols datastore with the combination of existing volumes and new volumes.'
---
= Create datastore
:icons: font
:imagesdir: ../media/

[.lead]

Depending on the destination chosen for action, the datastore is created and mounted on all the hosts of the destination and the action is enabled only if the current user had privilege to execute.

Create Datastore action wizard supports creation of NFS, VMFS, and vVols datastore.
 
== Create vVols datastore

You can create vVols datastore with new volumes or with existing volumes. You can also create vVols datastore with the combination of existing volumes and new volumes.
[NOTE]
Check to ensure root aggregates are not mapped to SVM.
The user interface is self explanatory, use these steps as guidelines. 

.Steps
. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment.
. Right-click a Host System or a Host Cluster or a Datastore, and then select *NetApp ONTAP tools* > *Create Datastore*
. Select vVols in *Type* and click Next
. Provide datastore name and protocol information and click NEXT
. Select Platform and storage VM in the Storage pane. You can select the custom Export Policy in the advanced options.
. You can either Create new volumes or Use existing volumes in the Storage attributes Pane and click NEXT.
. Review the summary and click  FINISH.
Datastore gets created and mounted on all the host 


== Create NFS datastore

.Steps
. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment.
. Right-click a Host System or a Host Cluster or a Datastore, and then select *NetApp ONTAP tools* > *Create Datastore*
. Select vVols in *Type* and click Next
. Provide datastore name and protocol information and click NEXT
. Select Platform and storage VM in the Storage pane. You can select the custom Export Policy in the advanced options.
. You can either Create new volumes or Use existing volumes in the Storage attributes Pane and click NEXT.
. Review the summary and click  FINISH.
Datastore gets created and mounted on all the host 
== Create VMFS datastore