---
permalink: configure/create_vvols_datastore.html
sidebar: sidebar
keywords:
summary: 'You can create vVols datastore with new volumes or with existing volumes. You can also create vVols datastore with the combination of existing volumes and new volumes.'
---
= Create datastore
:icons: font
:imagesdir: ../media/

[.lead]

Depending on the destination chosen for action, the datastore is created and mounted on all the hosts of the destination and the action is enabled only if the current user has privilege to execute.

Create Datastore action wizard supports creation of NFS, VMFS, and vVols datastore. The user interface is self explanatory, use these steps as guidelines.
 
== Create vVols datastore

You can create vVols datastore with new volumes or with existing volumes. You can not create vVols datastore with the combination of existing volumes and new volumes.
[NOTE]
Check to ensure root aggregates are not mapped to SVM.

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a host system or a host cluster or a datastore, and then select *NetApp ONTAP tools* > *Create Datastore*
. In the *Type* pane, select vVols in *Datastore Type*.
+
[NOTE]
You get vVols option only if the VASA provider is registered with the selected vCenter.
. In the *Name and Protocol* pane, provide *Datastore name* and *Protocol* information.
. In the *Storage* pane, select *Platform* and *storage VM*. In the *Advanced options* section, depending on your choice, select custom export policy (for NFS protocol) or custom initiator group name (for iSCSI protocol).
[NOTE]
* Platform and asymmetric options help you to filter out the SVMs dropdown options. You should select the SVM to create or use the volume(s) for datastore creation. 
* *Asymmetric* toggle button is visible only if iSCSI/FC was selected in the previous step and performance or capacity is selected in the platform drop-down.
* Asymmetric is true for AFF platform and false for ASA platform.
. In the *Storage attributes* pane, you can either create new volumes or use the existing volumes. When creating new volume you can enable QoS on the datastore.
. Review your selection in the *Summary* pane and click *FINISH*.
Datastore is created and mounted on all the hosts.

== Create NFS datastore
//10.1 addition
VMware Network File System (NFS) datastore is a type of storage that uses the NFS protocol to connect ESXi hosts to a shared storage device over a network. NFS datastores are commonly used in VMware vSphere environments and offer several advantages, such as simplicity and flexibility.

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a Host System or a Host Cluster or a Datastore, and then select *NetApp ONTAP tools* > *Create Datastore*
. In the *Type* pane, select NFS in *Datastore Type*.
. In the *Name and Protocol* pane, enter datastore name, size, and protocol information. In the advanced options, select the *Datastore cluster* and Kerberos Authentication.
[NOTE]
Kerberos Authentication is available only when NFS 4.1 protocol is selected. 
. In the *Storage* pane, select *Platform* and *Storage VM*. You can select *custom Export Policy* in the *Advanced Option* section.
[NOTE]
* *Asymmetric* toggle button is visible only if performance or capacity is selected in the platform drop-down.
* *Any* option in the platform dropdown enables you to see all the SVMs that are part of the vCenter irrespective of the platform or asymmetric flag. 
. In the *Storage Attributes* pane, select the aggregate for creation of volume. In the advanced options choose *Space Reserve* and *Enable QoS* as required.
. Review the selections in the *Summary* pane and click *FINISH*.

Datastore is created and mounted on all the hosts.

== Create VMFS datastore

Virtual Machine File System (VMFS) is a clustered file system specifically designed for storing virtual machine files in VMware vSphere environments. It allows multiple ESXi hosts to access the same virtual machine files concurrently, enabling features like vMotion and High Availability.

*About this task*

Check the following items before proceeding: 

* Check if all target hosts are healthy and check if host supports protocol.
* Create new volume (min size 2GB)
* Set Volume options with QOS
* Create LUN of type VMware
* Get initiators for all target hosts
* Create/reuse igroup based on matching initiators
* Map Lun to igroup
* Add iSCSI targets to ESXi hosts
* Rescan Host Bus Adapter(HBA's) on all hosts
* Mount volume as VMFS6 datastore(for 6.5+ hosts)
* Rescan VMFS storage on ESXi hosts
* Move datastore to datastore-cluster
* Rebalance iSCSI paths

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a Host System or a Host Cluster or a Datastore, and then select *NetApp ONTAP tools* > *Create Datastore*
. In the *Type* pane, select VMFS in *Datastore Type*.
. In the *Name and Protocol* pane, enter the datastore name, size, and protocol information. 
. In the *Advanced options* section of the pane, select the Datastore cluster you want to add this datastore to. 
. Select Platform and storage VM in the Storage pane. Select Asymmetric toggle button. Provide the *Custom initiator group name* in the *Advanced options* section of the pane. You can either choose an exiting igroup for the datastore or create new igroup with custom name.
+
If you choose *Any* option in the platform dropdown you can see all the SVMs that are part of the vCenter irrespective of the platform or asymmetric flag.
. Select the *Aggregate* from the drop-down. Select the *Space Reserve*, *Use existing volume*, and *Enable QoS* options as required from the *Advanced options* section and provide the details as required.
. Review the datastore details in the *Summary* pane and click *FINISH*.
Datastore is created and mounted on all the hosts.
