---
permalink: configure/create-datastore.html
sidebar: sidebar
keywords:
summary: 'When you create a datastore at host cluster level, the datastore is created and mounted on all the hosts of the destination and the action is enabled only if the current user has privilege to execute.'
---
= Create a datastore
:icons: font
:imagesdir: ../media/

[.lead]

When you create a datastore at the host cluster level, the datastore is created and mounted on all the destination hosts. You can see this option only if you have the required privileges.


[role="tabbed-block"]
====

.Create a vVols datastore
--

You can create a vVols datastore with either new volumes or existing volumes. You cannot create vVols datastore with the mix of existing and new volumes. 
[NOTE]
Check to ensure root aggregates are not mapped to SVM.

Beginning with ONTAP tools for VMware vSphere 10.3, you can create a vVols datastore using ASA r2 storage systems. The vVols datastore created on ASA r2 systems is created with space-efficiency as thin.vVol. VASA Provider creates a container and the desired protocol endpoints during the vVols datastore creation workflow. This container will not have any backing volumes.

.Before you begin

* Ensure that the VASA Provider is registered with the selected vCenter.
* SVM should be mapped to aggregate for SVM user in the ASA r2 storage system.
// https://jira.ngage.netapp.com/browse/OTVDOC-189 updates jani

.Steps
. Log in to the vSphere client.
. Right-click a host system, host cluster, or data center and select *NetApp ONTAP tools* > *Create Datastore*.
. Select vVols datastore Type.
. Enter the *Datastore name* and *Protocol* information.
[NOTE]
The ASA r2 storage system supports only iSCSI and FC protocol for vVols datastore.
. Select the storage VM where you want to create the datastore. 
. Select a custom export policy for the NFS protocol or a custom initiator group name for the iSCSI and FC protocols in the *Advanced options*.
[NOTE]
In ASA r2 storage system type SVM, storage units(LUN/namespace) are not created as the datastore is only a logical container.
//10.3 update for ASA r2
. In the *Storage attributes* pane, you can create new volumes or use the existing volumes. When creating a new volume, you can enable QoS on the datastore. One volume is created for every LUN-created request by default. This step is not applicable for vVols datastores using ASA r2 storage systems as vVols datastore does not have backing volumes. 
. Review your selection in the *Summary* pane and select *Finish*.
--

.Create an NFS datastore

--
A VMware Network File System (NFS) datastore uses the NFS protocol to connect ESXi hosts to a shared storage device over a network. NFS datastores are commonly used in VMware vSphere environments and offer several advantages, such as simplicity and flexibility.

.Steps
. Log in to the vSphere client.
. Right-click a host system, host cluster, or data center and select *NetApp ONTAP tools* > *Create Datastore*.
. Select NFS in the *Datastore Type* field.
. Enter the datastore name, size, and protocol information in the *Name and Protocol* pane. In the advanced options, select *Datastore cluster* and *Kerberos Authentication*.
[NOTE]
Kerberos authentication is available only when the NFS 4.1 protocol is selected. 
. Select *Platform* and *Storage VM* in the *Storage* pane. In the advanced option, Select *custom Export Policy*.
[NOTE]
* *Asymmetric* toggle button is visible only if performance or capacity is selected in the platform drop-down.
* *Any* option in the platform dropdown lets you see all the SVMs that are part of the vCenter irrespective of the platform or asymmetric flag. 
. Select the aggregate for volume creation in the *Storage Attributes* pane. In the advanced options, choose *Space Reserve* and *Enable QoS* as required.
. Review the selections in the *Summary* pane and select *Finish*.

The NFS datastore is created and mounted on all the hosts.

--

.Create a VMFS datastore

--
Virtual Machine File System (VMFS) is a clustered file system specifically designed to store virtual machine files in VMware vSphere environments. VMFS allows multiple ESXi hosts to access the same virtual machine files concurrently, enabling features like vMotion and High Availability.

[NOTE]
* You can only create a VMFS datastores on a protected cluster. When you add a VMFS datastore to a protected cluster, the datastore becomes protected automatically. 
* You cannot create a datastore on a data center with one or more protected host clusters.
* You cannot create a datastore at the ESXi host if the parent host cluster is protected with a relationship of "Automated Failover Duplex policy" type (uniform/non-uniform config).
* You can create a VMFS datastore on a ESXi host, only when it has an asynchronous relationship. 

.Before you begin

* Enable services and LIFs for each protocol on the ONTAP storage side. 
* Map SVM to aggregate for SVM user in the ASA r2 storage system. 
// https://jira.ngage.netapp.com/browse/OTVDOC-189 updates jani
* Configure the ESXi host if you're using the NVMe/TCP protocol:

. Review the https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc[VMware Compatibility Guide]
[NOTE] 
VMware vSphere 7.0 U3 and later versions support the NVMe/TCP protocol. However, VMware vSphere 8.0 and later versions are recommended. 
. Validate whether the Network Interface Card (NIC) vendor supports ESXi NIC with the NVMe/TCP protocol. 
. Configure the ESXi NIC for NVMe/TCP according to the NIC vendor specifications. 
. When using VMware vSphere 7 release, follow the instructions on the VMware site https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html[Configure VMkernel Binding for the NVMe over TCP Adapter] to configure NVMe/TCP port binding. When using VMware vSphere 8 release, follow https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html[Configuring NVMe over TCP on ESXi], to configure the NVMe/TCP port binding. 
. For VMware vSphere 7 release, follow the instructions on page https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html[Enable NVMe over RDMA or NVMe over TCP Software Adapters] to configure NVMe/TCP software adapters. For the VMware vSphere 8 release, follow https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html[Add Software NVMe over RDMA or NVMe over TCP Adapters] to configure the NVMe/TCP software adapters.
. Run link:../configure/discover-storage-systems-and-hosts.html[Discover storage systems and hosts] action on the ESXi host.
For more information, refer to https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429[How to Configure NVMe/TCP with vSphere 8.0 Update 1 and ONTAP 9.13.1 for VMFS Datastores].

* If you are using the NVME/FC protocol, perform the following steps to configure the ESXi host:
. Enable NVMe over Fabrics(NVMe-oF) on your ESXi host(s). 
. Complete SCSI zoning. 
. Ensure that ESXi hosts and the ONTAP system are connected at a physical and logical layer.

To configure an ONTAP SVM for FC protocol, refer to https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html[Configure an SVM for FC].

For more information on using NVMe/FC protocol with VMware vSphere 8.0, refer to https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[NVMe-oF Host Configuration for ESXi 8.x with ONTAP].

For more information on using NVMe/FC with VMware vSphere 7.0, refer to https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html[ONTAP NVMe/FC Host Configuration guide] and http://www.netapp.com/us/media/tr-4684.pdf[TR-4684].

.Steps
. Log in to the vSphere client.
. Right-click a host system, host cluster, or data center and select *NetApp ONTAP tools* > *Create Datastore*.
. Select VMFS datastore type.
. Enter the datastore name, size, and protocol information in the *Name and Protocol* pane.
If you choose to add the new datastore to an existing VMFS datastore cluster, select the datastore cluster selector under Advanced Options. 
. Select storage VM in the *Storage* pane. Provide the *Custom initiator group name* in the *Advanced options* section as required. You can choose an existing igroup for the datastore or create a new igroup with a custom name.
+
When NVMe/FC or NVMe/TCP protocol is selected, a new namespace subsystem is created and is used for namespace mapping. The namespace subsystem is created using the auto-generated name that includes the datastore name. You can rename the namespace subsystem in the *custom namespace subsystem name* field in the advanced options of the *Storage* pane. 
. From the *storage attributes* pane:
.. Select *Aggregate* from the drop-down options.
[NOTE]
For ASA r2 storage systems, the *Aggregate* option is not shown as the ASA r2 storage is a disaggregated storage. When you choose ASA r2 storage system type SVM, the storage attributes page shows the options to enable QoS.
// updated for 10.3 ASA r2
.. As per the selected protocol, a storage unit(LUN/Namespace) is created with a space reserve of type thin.
+
[NOTE]
Beginning in ONTAP 9.16.1, ASA r2 storage systems support up to 12 nodes per cluster.
.. Select the *Performance service level* for ASA r2 storage systems with 12 nodes SVM that is a heterogeneous cluster. This option is unavailable if the selected SVM is a homogeneous cluster or uses an SVM user.
+
'Any' is the default performance service level (PSL) value. This setting creates the storage unit using the ONTAP balanced placement algorithm. However, you can select the performance or extreme option as required.
// updated for 10.4
.. Select *Use existing volume*, *Enable QoS* options as required, and provide the details as required.
+
[NOTE]
In the ASA r2 storage type, volume creation or selection does not apply to storage unit creation(LUN/Namespace). Therefore, these options are not shown.
+
[NOTE]
You cannot use the existing volume to create a VMFS datastore with NVMe/FC or NVMe/TCP protocol; you should create a new volume.

. Review the datastore details in the *Summary* pane and select *Finish*.

[NOTE]
If you create the datastore on a protected cluster, you can see a read-only message "The datastore is being mounted on a protected Cluster."

.Result
The VMFS datastore is created and mounted on all the hosts.

--

====