---
permalink: configure/ip_whitelisting.html
sidebar: sidebar
keywords:
summary: 'This feature enables you to specify specific ESXi host address to be allowed for datastore mount operation.'
---
= Manage network access
:icons: font
:imagesdir: ../media/

[.lead]
// Need to add procedure with vCenter UI and ontap tools shortcut. move the API to API section. Setting> Manage network Access.


This feature enables you to specify specific ESXi host address to be allowed for datastore mount operation.

When you have multiple IP addresses for ESXi hosts, all the discovered IP addresses from the host are added to an Export policy. If you do not want to add all IP addresses to export policy, provide a setting for whitelisted IP addresses in a comma separated list or range or CIDR, or combination of all three for each vCenter.

If the setting is not provided, export policy adds all IP addresses discovered in the pre-mount step. If the setting is provided, ONTAP tools adds only the ones which fall within the whitelisted IPs or range. If none of the IPs of a host belong to the whitelisted IPs, the mount on that host fails.

By default all host IP's are added to the export policy.

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Settings* > *Manage Network Access* > *Edit*. 
+
Use coma(,) to separate the IP addresses. You can specify a specific IP address, or a range of IP addresses or IPv6 addresses.
. Click *SAVE*. 