---
permalink: configure/ontap_tools_manager_ui.html
sidebar: sidebar
keywords: ontap tools manager, managerui
summary: 'ONTAP tools Manager provides more control and power to ONTAP tools administrator, which helps in overall management of the appliance, tenants, and storage backends.'
---
= ONTAP tools Manager user interface
:icons: font
:imagesdir: ../media/

[.lead]

ONTAP tools for VMware vSphere is a Multi-tenant system, which manages multiple vCenters. ONTAP tools Manager provides more control to ONTAP tools administrator over the managed vCenters and onboarded storage backends. 

ONTAP tools Manager helps in:

* vCenter management - Register and unregister vCenters to ONTAP tools.
* Storage backend management - Register and unregister ONTAP storage clusters to ONTAP tools and map them to onboarded vCenters globally.
* Log bundle downloads - Collect log files for ONTAP tools for VMware vSphere.
* Certificate management - Change the self-signed certificate to custom CA certificate and renew
or refresh all certificates.

To access ONTAP tools Manager UI, launch `\https://loadBalanceIP:8443/virtualization/ui/` from the browser and login with ONTAP tools administrator credentials provided during deployment.



