---
permalink: configure/reference_delete_vvols.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'Delete datastore action deletes the datastore. In case of NFS or VMFS datastore a dialog box appears with the list of VMs that are using the datastore.'
---
= Delete datastores
:icons: font
:imagesdir: ../media/

[.lead]
Delete datastore action deletes the datastore.

Remove storage from datastore action is supported on all ONTAP tools discovered or managed vVols datastores in the vCenter. This action allows the removal of volumes from the vVols datastore.

Remove option is disabled when there are vVols residing on a particular volume. In addition to removal of volumes from datastore, you can choose to delete the selected volume on ONTAP storage as well.

Delete datastore task from ONTAP tools in the VCenter does the following: 

* Unmounts the vVol container.
* Cleans up Igroup. If igroup is not in use, removes iqn from igroup. 
* Deletes Vvol container.
* Leaves the Flex volumes on the storage array. 

Follow the steps below to delete NFS, VMFS, or vVOL datastore from ONTAP tools from the vCenter:

Steps:

. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment. 
. Right-click a Host System or a Host Cluster or a Datastore, and then select *NetApp ONTAP tools* > *Delete datastore*.
.. In case of NFS or VMFS datastore a dialog box appears with the list of VMs that are using the datastore.
.. In case of vVols datastore, Delete datastore action deletes the datastore only when there are no vVols associated with it. The Delete datastore dialog box provides an option to delete volumes from ONTAP cluster.
