---
permalink: configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html
sidebar: sidebar
keywords:
summary: 'You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools sets are based on internal NetApp testing.'
---
= Set ESXi host values
:icons: font
:imagesdir: ../media/

[.lead]
You can set timeouts and other values on the ESXi hosts using ONTAP tools for VMware vSphere to ensure best performance and successful failover. The values that ONTAP tools sets are based on internal NetApp testing.

You can set the following values on an ESXi host:

== ESXi advanced configuration

* *VMFS3.HardwareAcceleratedLocking*
+
You should set this value to 1.

* *VMFS3.EnableBlockDelete*
+
You should set this value to 0.

== NFS settings

* *Net.TcpipHeapSize*
+
Set this value to 32.
* *Net.TcpipHeapMax*
+
Set this value to 1024MB.
* *NFS.MaxVolumes*
+
Set this value to 256.
* *NFS41.MaxVolumes*
+
Set this value to 256.
* *NFS.MaxQueueDepth*
+
Set this value to 128 or higher to avoid queuing bottlenecks.
* *NFS.HeartbeatMaxFailures*
+
Set this value to 10 for all NFS configurations.
* *NFS.HeartbeatFrequency*
+
Set this value to 12 for all NFS configurations.
* *NFS.HeartbeatTimeout*
+
Set this value to 5 for all NFS configurations.

== iSCSI settings

* *Path selection policy*
+
Set this value to "`RR`" for all iSCSI paths.
+
Setting this value to "`RR`" helps to provide load balancing across all of the active/optimized paths.
