---
permalink: configure/registration-process.html
sidebar: sidebar
keywords:
summary: 'You can register the VASA Provider with a vCenter Server instance using ONTAP tools for VMware vSphere remote plugin interface.'
---
= Register the VASA Provider with a vCenter Server instance
:icons: font
:imagesdir: ../media/

[.lead]
You can register the VASA Provider with a vCenter Server instance using ONTAP tools for VMware vSphere. The VASA Provider settings section displays the VASA Provider registration status for the selected vCenter Server.

.Steps

. Log in to the vSphere client using `\https://<vcenterip>/<ui>`
. Select *Shortcuts* > *NetApp ONTAP tools* under the plug-ins section.
. Select *Settings* > *VASA Provider settings*. The VASA Provider registration status will be displayed as not registered.
. Select the *Register* button to register the VASA Provider.
. Enter a name for the VASA Provider and provide ONTAP tools for VMware vSphere application user credentials and select *Register*.
. After a successful registration and page refresh, the registered VASA Provider's status, name, and version is displayed.  After registration, the unregister action is activated.

*After you finish*

Verify that the onboarded VASA Provider is listed under VASA Provider from the vCenter client:

.Steps

. Navigate to the vCenter Server instance.
. Log in with the administrator credentials.
. Select *Storage Providers* > *Configure*. Verify that the onboarded VASA Provider is listed correctly.
