---
permalink: configure/task_configure_esx_server_multipathing_and_timeout_settings.html
sidebar: sidebar
keywords:
summary: 'ONTAP® tools for VMware vSphere checks and sets the ESXi host multipathing settings and HBA timeout settings that work best with NetApp storage systems.'
---
= Configure ESXi server multipath and timeout settings
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere checks and sets the ESXi host multipath settings and HBA timeout settings that work best with NetApp storage systems.

*About this task*

This process might take a long time, depending on your configuration and system load. The task progress is displayed in the Recent Tasks panel. As the tasks are completed, the host status Alert icon is replaced by the Normal icon or the Pending Reboot icon.

*Steps*

. From the VMware vSphere Web Client Home page, click *Hosts and Clusters*.
. Right-click a host, and then select *Actions* > *NetApp ONTAP tools* > *Update host data*.
. In the NetApp Recommended Settings dialog box, select the values that work best with your system.
+
The standard, recommended values are set by default.
. Click *OK*.
. To set the values to the recommended values, navigate to the ESXi Host Compliance portlet in the overview panel of the VMware vSphere Web Client home page.
. Select *Apply Recommended Settings* link.
. In the *Apply recommended host settings* window, select the hosts that you want to comply with NetApp recommended host settings and click *NEXT*
[NOTE]
You can expand the ESXi host to see the current values 
. In the settings page, select the recommended values as required.
. In the summary pane, check the values and click *Finish*
You can track the progress in the Recent task panel.
