---
permalink: configure/task_provision_vvols_datastores.html
sidebar: sidebar
keywords:
summary: 'You can provision a vVols datastore using the Provision Datastore wizard only if VASA Provider is enabled in your ONTAP tools.'
---
= Provision vVols datastores
:icons: font
:imagesdir: ../media/

[.lead]
You can provision a vVols datastore using the Provision Datastore wizard only if VASA Provider is enabled in your ONTAP tools.

*What you will need*

* You should configure similar replication policy and schedule on the datastores at both the source and target sites for reverse replication to be successful.

FlexVol volumes that are used as backing storage are displayed on the vVols dashboard only if they are running ONTAP 9.5 or later. You should not use the vCenter Server New Datastore wizard to provision vVols datastores.

* You should use cluster credentials to create vVols datastores.
+
You cannot use SVM credentials to create vVols datastores.

* VASA Provider does not support the cloning of a virtual machine that is hosted on the vVols datastore of one protocol to another datastore with a different protocol.
* You should have completed cluster pairing and SVM pairing both on the source and destination sites.

*Steps*

. From the vSphere Client home page, click *Hosts and Clusters*.
. In the navigation pane, select the datacenter on which you want to provision the datastore.
. Specify the hosts on which you want to mount the datastore.
+
|===
| *To make the datastore available to...*| *Do this...*
a|
All of the hosts in a datacenter
a|
Right-click a datacenter, and then select *NetApp ONTAP tools* > *Provision Datastore*.
a|
All of the hosts in a cluster
a|
Right-click a cluster, and then select *NetApp ONTAP tools* > *Provision Datastore*.
a|
A single host
a|
Right-click a host, and then select *NetApp ONTAP tools* > *Provision Datastore*.
|===

. Complete the fields in the New Datastore dialog box to create the datastore.
+
Most of the fields in the dialog box are self-explanatory. The following table describes some of the fields for which you might require guidance.
+
|===
| *Section*| *Description*
a|
General
a|
The General section of the New Datastore dialog box provides options to enter the location, name, description, type, and protocol for the new datastore. The vVols datastore type is used to configure a vVols datastore.

You can provision the vVols datastore if VASA provider capability is enabled. See, link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html[Enable VASA Provider for configuring virtual datastores] for details. The
vVols datastore supports NFS and iSCSI protocols.

NOTE: If you are provisioning iSCSI vVols datastore for vVols replication, then before creating vVols datastore at the target site, you need to perform SnapMirror update and cluster rediscovery.

a|
Storage system
a|
This section enables you to select whether you want the vVols datastore to have either replication enabled or disabled. Only asynchronous type replication profile is allowed for this release. The system recommended values of paired *Storage system* and *Storage VM* are populated automatically. The recommended values are populated only if they are paired in ONTAP. You can modify these values if required.

After FlexVol volumes are created and SnapMirror is initialized in ONTAP, you should run a storage rediscovery in ONTAP tools to be able to see the new volumes.
a|
Storage attributes
a|
You should select the schedule for SnapMirror and the required FlexVol volume from the existing list. This schedule should be similar to the one selected in the VM Storage Policies page. The user should have created FlexVol volumes on ONTAP with SnapMirror that are listed. By default all the volumes are set to maximum Autogrow size to 120 % and default Snapshots are enabled on these volumes.

*Note:*

* A FlexVol volume that is part of a vVols datastore cannot shrink below the existing size but can grow by 120% maximum. Default snapshots are enabled on this FlexVol volume.
* The minimum size of FlexVol volume that you should create is 5GB.
|===
+
. In the Summary section, click *Finish*.

*Result*

A Replication group is created in the backend when a vVols datastore is configured.


*Related information*

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html[Analyze performance data using the vVols dashboard]
