---
permalink: release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html
sidebar: sidebar
keywords: release notes, feature, comparison
summary: "Learn about the ONTAP tools for VMware vSphere 9 and ONTAP tools for VMware vSphere 10 feature comparison"
---
= ONTAP tools for VMware vSphere 9 and 10 feature comparison
:icons: font
:imagesdir: ../media/

[.lead]

Learn whether migrating from ONTAP tools for VMware vSphere 9 to ONTAP tools for VMware vSphere 10.2 or later versions is right for you.

[NOTE]
For the most up-to-date compatibility information, refer to https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].

[cols="20%,25%,30%",options="header"]
|===
| Feature | ONTAP tools 9.13 | ONTAP tools 10.2 onwards
|
Key value proposition
|
Streamline and simplify day-0 to day-2 operations with enhanced security, compliance and automation capabilities
|
Expanded support to include FC for VMFS and NVMe-oF for VMFS only. Ease of use for NetApp SnapMirror, simple setup for vSphere metro storage clusters, and three-site VMware Live Site Recovery support
|
ONTAP release qualification
|
ONTAP 9.9.1 to ONTAP 9.16.1
|
ONTAP 9.12.1 to 9.15.1 for ONTAP tools 10.2.

ONTAP 9.14.1, 9.15.1, 9.16.0, and 9.16.1 for ONTAP tools 10.3.

ONTAP 9.14.1, 9.15.1, 9.16.0, and 9.16.1 for ONTAP tools 10.4.

ONTAP 9.16.1P3 and later is required for ONTAP tools 10.4 when using ASA r2 systems.

ONTAP 9.15.1, 9.16.1, and 9.17.0 for ONTAP tools 10.5
|
VMware release support
|
vSphere 7.x-8.x

VMware Site Recovery Manager (SRM) 8.5 to VMware Live Site Recovery 9.0
|
vSphere 7.x-8.x
vSphere 9.0 from ONTAP tools 10.5 onwards
VMware Site Recovery Manager (SRM) 8.7 to VMware Live Site Recovery 9.0 

*NOTE:*
In ONTAP tools 10.x, SRM supports shared sites, enabling enhanced scalability and improved performance.
|
Protocol support
|
NFS and VMFS datastores: NFS (v3 and v4.1), VMFS (iSCSI and FCP)
|
NFS and VMFS datastores: NFS (v3 and v4.1), VMFS (iSCSI/FCP/NVMe-oF)
|
Scalability
|
Hosts and VMs: 300 Hosts, up to 10K VMs 

Datastores: 600 NFS, up to 50 VMFS
|
Hosts and VMs: 600 Hosts
|
Observability
|
Performance, capacity, and host compliance dashboards

Dynamic VM and datastore reports
|
Updated performance, capacity, and host compliance dashboards

Dynamic VM and datastore reports
|
Data protection
|
SRA replication for VMFS and NFS.
SCV integration and interoperable for backup.
|
SRA replication for iSCSI VMFS and NFS v3 datastores three-site protection combining SMAS and VMware Live Site Recovery.
SRA support for FCP with VMFS.
|
VASA Provider support
|
VASA 4.0
|
VASA 3.0
|===