---
permalink: release-notes/whats-new.html
sidebar: sidebar
keywords: what's new, release notes, 10.5, ONTAP tools for VMware vSphere
summary: "Learn about the new capabilities available in ONTAP tools for VMware vSphere 10.5."
---
= What's new in ONTAP tools for VMware vSphere 10.5
:icons: font
:imagesdir: ../media/

[.lead]
Learn about the new capabilities available in ONTAP tools for VMware vSphere 10.5.

* *Platform qualification*

ONTAP tools for VMware vSphere 10.5 adds support for ASA.r2 platforms, providing compatibility with the latest hardware and software configurations. This release also includes integration with ONTAP 9.16.1 and 9.17.1, expanding the supported environments.

* *VMware qualification and certifications*

ONTAP tools for VMware vSphere 10.5 complies with current VMware interoperability certification standards, supporting both ESXi host and vCenter Server.

* *MetroCluster support*

This release introduces support for MetroCluster (MCC) configurations, enhancing high availability and disaster recovery capabilities.

* *Security and certificate management*

This release introduces streamlined management of self-signed certificates, enhancing both user experience and adherence to security standards. It provides improved certificate validation workflows to secure ONTAP and ONTAP tools for VMware vSphere communications.

* *Replication enhancements*

This release supports VMFS replication with hierarchical consistency group including SRA and SnapMirror active sync in ASA r2 systems. It supports zero RPO backups to improve data protection and recovery.

* *Upgrade and migration*

The upgrade and migration process from previous versions of ONTAP tools for VMware vSphere to ONTAP tools for VMware vSphere 10.5 is designed to be seamless and efficient, minimizing downtime and ensuring a smooth transition.

.Related information

For the latest details on version compatibility, refer to https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].
