---
permalink: release-notes/whats-new.html
sidebar: sidebar
keywords: what's new, release notes, otv, 10.2, ONTAP tools for VMware vSphere
summary: "Learn about the new capabilities available in ONTAP tools for VMware vSphere 10.3."
---

= What's new in ONTAP tools for VMware vSphere 10.3

[.lead]
Learn about the new capabilities available in ONTAP tools for VMware vSphere 10.3.

[cols="30%,70%",options="header"]
|===
| Update | Description
a|Platform qualification
a|ONTAP tools for VMware vSphere 10.3 release supports the ONTAP version 9.16.0 along with VMware vSphere 8.0.u3 version. This release supports VMware Live Site Recovery 9.0, which provides the latest security capabilities that ONTAP and VMware vSphere have to offer.

a|
Ease of deployment
a|
ONTAP tools for VMware vSphere 10.3 release introduces easy deployment for first time installations. You can now deploy with a single node topology with minimum requirement and then  choose to update to a HA or a large deployment as required. 

a|
Dynamic storage provisioner
a|
ONTAP tools for VMware vSphere 10.3 release removes dependencies associated with Trident and provides ease of deployment. This release uses dynamic storage provisioner that enables seamless provisioning and configuration.
 
a|
CA signed certificates 
a|
ONTAP tools for VMware vSphere 10.3 release adopts CA signed certificates for ONTAP tools REST APIs and user interface to provide higher security measures.

a|
//xref:../protect/enable-storage-replication-adapter.html[Storage Replication Adapter (SRA) enhancements] 
a|
//SRA implements the VMware Site Recovery Manager (SRM) specification-based disaster recovery (DR) solution. SnapMirror active sync through SRM integration supports the disaster recovery planning and orchestrating solution to provide transparent application failover.
|===


