---
permalink: manage/attach-detach-disk.html
sidebar: sidebar
keywords: attach data disk VM, detach VM disk, ONTAP tools virtual machine disk, VMware VM storage expansion
summary: "Attach or detach virtual machine data disks to manage storage capacity."
---
= Attach or detach a data disk from a VM in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Attach or detach data disks from virtual machines in vSphere to manage storage capacity.

== Attach a data disk to a virtual machine
Attach a data disk to a virtual machine to add more storage.

.Steps

. Log in to the vSphere client.
. Right-click a virtual machine in the inventory and select *Edit Settings*.
. On the *Virtual Hardware* tab, select *Existing hard disk*.
. Select the virtual machine that contains the disk.
. Select the disk you want to attach and select *OK*.

.Result
The hard disk appears in the Virtual Hardware devices list.

== Detach a data disk from the virtual machine

Detach a data disk from a virtual machine when you no longer need it. The disk is not deleted and remains on the ONTAP storage system.

.Steps

. Log in to the vSphere client.
. Right-click on a virtual machine in the inventory and select *Edit Settings*.
. Move your pointer over the disk and select *Remove*.
[NOTE]
The disk is removed from the virtual machine. If other virtual machines share the disk, the disk files aren't deleted.

.Related information

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html[Add a New Hard Disk to a Virtual Machine]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html[Add an Existing Hard Disk to a Virtual Machine]