---
permalink: manage/backup-settings.html
sidebar: sidebar
keywords:
summary: 'Enter the NTP server details to synchronize the time clocks of ONTAP tools appliance.'
---
= Edit Backup settings
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP tools for VMware vSphere 10.5, the backup feature is enabled by default and a backup is created every 10 minutes. You can disable the backup feature or edit the frequency of the backup. 

It is not recommended to disable the backup because it prevents ONTAP tools from maintaining low RPO. Disabling the backup feature will not delete the existing backup files.
You can change the frequency of the backup to a value between 10 and 60 minutes.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the *Settings* > *Backup* > *Edit* option.
. In the edit window, you can disable the backup or edit the backup frequency.

