---
permalink: manage/backup-settings.html
sidebar: sidebar
keywords: ONTAP tools backup settings, configure backup schedule, appliance backup configuration, ONTAP tools data protection
summary: "Enable or disable ONTAP tools backup and configure backup frequency between 10 and 60 minutes."
---
= Edit ONTAP tools backup settings
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP tools for VMware vSphere 10.5, backups are enabled by default and run every 10 minutes. You can disable backups or change the backup frequency.

Do not disable backup because it prevents ONTAP tools from maintaining a low recovery point objective (RPO). Disabling backup does not delete the existing backup files.
You can change the frequency of the backup to a value between 10 and 60 minutes.
// OTVDOC-256 jira updated note removed for JIRA OTVDOC-290

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the *Settings* > *Backup* > *Edit* option.
. In the Edit window, disable backup or change the backup frequency.

