---
permalink: manage/certificate_manage.html
sidebar: sidebar
keywords:
summary: 'Single instance of ONTAP tools can manage multiple vCenters. When ONTAP tools is deployed, self signed certificate is assigned to all vCenters by default. '
---
= Manage certificates
:icons: font
:imagesdir: ../media/

[.lead]
Single instance of ONTAP tools can manage multiple vCenters. When ONTAP tools is deployed, self signed certificate is assigned to all vCenters by default.
When you're managing multiple vCenters and you want to enable vVols capability on multiple vCenters then you need to change the self signed certificate to custom CA certificate using the ONTAP tools Manger interface. You can use the same interface to renew or refresh all certificates.

*Steps*

. Launch `\https://loadBalanceIP:8443/virtualization/ui/` from browser with ONTAP tools administrator credentials provided during deployment. 
. Select *Certificates* > *VASA provider* > *Renew* option to renew the certificates.
[NOTE]
System will be offline until the certificate is renewed.
. To upgrade the self signed certificate to custom CA certificate, select *Certificates* > *VASA provider* > *UPGRADE TO CA* option.
.. In the upgrade certificate to custom CA pop-up, upload the Server certificate, Server certificate private key, and Root CA certificate and Intermediate certificate files. The tool tip provides description of the certificates.
.. Enter the Domain name for which you had generated this certificate.
.. Click *UPGRADE*
+
[NOTE]
System will be offline until the upgrade is complete.

