---
permalink: manage/certificate-manage.html
sidebar: sidebar
keywords:
summary: 'A single instance of ONTAP tools for VMware vSphere can manage multiple vCenter Server instances. ONTAP tools for VMware vSphere is deployed with a self-signed certificate for VASA Provider. With this, only one vCenter Server instance can be managed for vVols datastores.'
---
= Manage certificates
:icons: font
:imagesdir: ../media/

[.lead]
A single instance of ONTAP tools for VMware vSphere can manage multiple vCenter Server instances.

Ensure that domain name on which the certificate is issued is mapped to  the virtual IP address in a multi-vCenter deployment where custom CA certificates are mandatory. _nslookup_ check on the domain name is performed to check whether the domain is getting resolved to the intended IP address. The certificates should be created with domain name and IP address of the load balancer IP address.

[NOTE]
A different load balancer IP address mapped to different domains is not supported when you upgrade self-signed to custom CA.

[role="tabbed-block"]
====

.ONTAP tools certificate
--
ONTAP tools tab shows details like certificate type (self-signed/CA signed) and domain name. 
During deployment, self-signed certificate is generated by default. You can renew the certificate or upgrade the certificate to CA.

*Steps*

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment.
. Select *Certificates* > *ONTAP tools* > *Renew* option to renew the certificates.
[NOTE]
You can renew the certificate if it has expired or is nearing the expiration date. The system will be offline till the certificate is renewed and you will be logged out of the user interface.
+
*Renew*  is the only option available when the certificate type is CA signed. For CA signed certificate, a dialog box appears where you can provide the server certificate, private key, root CA, and intermediate certificate details.
. To upgrade the self-signed certificate to custom CA certificate, select *Certificates* > *ONTAP tools* > *Upgrade to CA* option.
.. In the *Upgrade certificate to custom CA* pop-up, upload the server certificate, server certificate private key, root CA certificate, and intermediate certificate files. The tool tip provides description of the certificates.
.. Enter the domain name for which you generated this certificate.
.. Click *Upgrade*.
+
[NOTE]
The system will be offline till the upgrade is complete and you will be logged out of the user interface. Switching from CA signed to self-signed certificate is not allowed.

--
.VASA provider certificate
--

ONTAP tools for VMware vSphere is deployed with a self-signed certificate for VASA Provider. With this, only one vCenter Server instance can be managed for vVols datastores. When you're managing multiple vCenter Server instances and you want to enable vVols capability on multiple vCenter Server instances, you need to change the self-signed certificate to custom CA certificate using ONTAP tools Manager interface.

*Steps*

. Launch ONTAP tools Manager from a web browser: `\https://loadBalanceIP:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment.
. Select *Certificates* > *VASA Provider* or *ONTAP tools* > *Renew* option to renew the certificates.
[NOTE]
The system will be offline till the certificate is renewed and you will be logged out of the user interface.
. To upgrade the self-signed certificate to custom CA certificate, select *Certificates* > *VASA Provider* or *ONTAP tools* > *Upgrade to CA* option.
.. In the *Upgrade certificate to custom CA* pop-up, upload the server certificate, server certificate private key, root CA certificate, and intermediate certificate files. The tool tip provides description of the certificates.
.. Enter the domain name for which you generated this certificate.
.. Click *Upgrade*.
+
[NOTE]
The system will be offline till the upgrade is complete and you will be logged out of the user interface. Switching from CA signed to self-signed certificate is not allowed.
--

====
//10.3 updates - added ONTAP tools.
