---
permalink: manage/config-proximity.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'You can edit the SnapMirror relationships of the protected host cluster. You can add, modify, and delete the relationships. However, you cannot edit consistency group name. '
---
= Configure proximity/access for host cluster protection in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Learn how to configure proximity and access settings in ONTAP tools for VMware vSphere to assign hosts and storage resources to specific sites, optimizing data access and storage efficiency for your protected host clusters.

.Steps

. Log in to the vSphere client.
. To configure proximity/access settings for a protected cluster, right-click on a host cluster and select *NetApp ONTAP tools* > *Configure proximity/access*.
. In the *Configuration type* window, select how you want to configure storage connections in the cluster:
.. To allow hosts from both Site A and Site B to access storage from both sites, select *Uniform*.
.. To restrict hosts at each site to access storage only at their own site, select *Non-uniform*.
. Select the source and target fault domains, then select *Next*.
. In the *Hosts* window, assign the hosts listed in the middle column to either Site A or Site B, then select *Next*.
. In the *Storage VM Peer* window, assign the required storage VM peer from the list in the middle column to Site A or Site B so it is proximal to the hosts assigned to that site. The other peer is automatically assigned to the other site. Select *Next*.
. Review your selections in the *Summary* window, then select *Finish*.

After completing these steps, your host cluster will access storage according to the selected proximity policy.

// 10.6 new topic