---
permalink: manage/configure-remote-diagnostic-access.html
sidebar: sidebar
keywords: remote diagnostic access, ONTAP tools SSH diag user, enable SSH diagnostics, appliance troubleshooting access
summary: "Enable SSH access for the diag user in ONTAP tools for VMware vSphere."
---
= Configure remote diagnostic access for ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can enable SSH access for the diag user in ONTAP tools for VMware vSphere.

.Before you begin

Enable the VASA Provider extension for your vCenter Server instance.

.About this task

Using SSH to access the diag user account has the following limitations:

* You can use only one login account each time you enable SSH.
* SSH access to the diag user account is disabled in either of these cases:
 ** The time expires.
+
The login session expires at midnight the next day.

 ** You log in as a diag user again using SSH.

.Steps

. Log in to the vCenter Server.
. Locate the ONTAP tools VM and launch the web console.
. Log in using the `maint` credentials.
. Enter `4` to select *Support and Diagnostics*.
. Enter `2` to select *Enable remote diagnostics access*.
. Enter `y` in the confirmation dialog box to enable remote diagnostic access.
. Enter a password for remote diagnostic access.

// NADIAA checked