---
permalink: manage/delete-active-relationship.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'You need to consider the following points before you delete host cluster protection.'
---
= Delete an active relationship
:icons: font
:imagesdir: ../media/
// new topic for 10.2 content
[.lead]
You need to consider the following points before you delete host cluster protection: 

* To delete an async relationship, you need to onboard the destination site Cluster/SVM as storage backend in ONTAP tools for VMware vSphere.
* To delete an automated_failover_duplex type relationship, you do not need to onboard the destination site Cluster/SVM as storage backend in ONTAP tools for VMware vSphere.
* You cannot delete the last SnapMirror relationship.
* To delete the entire protection-settings call the DELETE /protection-settings API. 
* When you delete a relationship respective relationship on ONTAP is also deleted.
* When you delete an automated_failover_duplex type relationship, it results in unmapping the destination side datastores and removal of consistency group, LUNs, Volumes, and igroup from the destination ONTAP Cluster.
* Deleting the relationship triggers rescan on site B to remove the unmapped LUN as active path from hosts.

.Steps

. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a host cluster, and then select *NetApp ONTAP tools* > *Protect Cluster*.
. In the *Protect Cluster* window, select the kebab menu under the SnapMirror settings and select *Delete*.
