---
permalink: manage/delete-deployment.html
sidebar: sidebar
keywords: ONTAP tools,Storage Replication Adapter
summary: 'After deleting ONTAP tools for VMware vSphere deployment, you should clean up the FlexVolumes created during the deployment. If you have used a dedicated ONTAP cluster for deployments, you should clean up the FlexVolumes as the deployment creates lot of FlexVolumes which are unused resulting in lowered performance.'
---
= Clean up volumes
:icons: font
:imagesdir: ../media/

[.lead]
After deleting ONTAP tools for VMware vSphere deployment, you should clean up the FlexVolumes created during the deployment. If you have used a dedicated ONTAP cluster for deployments, you should clean up the FlexVolumes as the deployment creates lot of FlexVolumes which are unused resulting in lowered performance.

Use the following guidelines to clean up the FlexVolumes post removal of ONTAP tools for VMware vSphere deployment.

.Steps

. From the primary node VM of ONTAP tools for VMware vSphere, run the following command to identify the type of deployment. 
+
_cat /opt/netapp/meta/ansible_vars.yaml | grep -i protocol_
+
If it is an iSCSI deployment, then you need to delete igroups as well. 
. Fetch the list of FlexVolumes created in ONTAP during the deployment using the following command.
+
_kubectl describe persistentvolumes | grep internalName | awk -F'=' '{print $2}'_
. Delete VMs from vCenter Server, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en[Remove and Reregister VMs and VM Templates].
. Delete volumes from ONTAP system manager, refer to https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html[Delete a FlexVol volume]. Give the exact name of the FlexVolume in the cli command to delete the volume.
. In case of iSCSI deployment, delete SAN igroups from ONTAP, refer to https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html[View and manage SAN initiators and igroups].


