---
permalink: manage/edit-hostcluster-protection.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'You can edit the SnapMirror relationships of the protected host cluster. You can add, modify, and delete the relationships. However, you cannot edit consistency group name. '
---
= Edit or delete host cluster protection
:icons: font
:imagesdir: ../media/
// new topic for 10.2 content
[.lead]

You can edit the SnapMirror relationships of the protected host cluster. You can add, modify, and delete the relationships. However, you cannot edit consistency group name. 

When new hosts are added to the host cluster, you need to configure their proximity or access to source/target in order to ensure seamless protection.

You need to consider the following points before you delete host cluster protection:

* You cannot delete the last SnapMirror relationship.
* You can delete/unprotect the cluster using the protection settings UI kebab menu. 
* When you delete a relationship respective relationship on ONTAP is also deleted.
* When you delete an automated_failover_duplex type relationship, it results in unmapping the destination side datastores and removal of consistency group, LUNs, Volumes, and igroup from the destination ONTAP Cluster.
* Deleting the relationship triggers rescan on site B to remove the unmapped LUN as active path from hosts.

NOTE: You can add up to two SnapMirror relationships. You can have one failover duplex type target relationship and/or one asynchronous type target relationship.

.Steps

. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a host cluster, and then select *NetApp ONTAP tools* > *Protect Cluster*.
+
You can click on the datastore count link to view all of the source SVM datastores that are mounted on the host cluster along with their protection status.
. In the *Protect Cluster* window, select the kebab menu under the SnapMirror settings and select *Edit* to edit the SnapMirror relationship or *Delete* to delete the cluster protection.
. In the *Edit SnapMirror relationship* window, add the proximity or the access needs of the new hosts.
+
[NOTE]
In case of Asynchronous type relationship, edit action is not supported as you cannot add the target SVM for tertiary site to the same ONTAP tools instance. However, you can use the system manager or CLI of the target SVM to change the relationship configuration.
. Click *Save* after making the necessary changes.
. You can see the changes in the *Protect Cluster* window.