---
permalink: manage/edit-autosupport.html
sidebar: sidebar
keywords:
summary: 'When configuring ONTAP tools for VMware vSphere for the first time, AutoSupport is enabled by default. It sends messages to technical support 24 hours after it is enabled.'
---
= Edit AutoSupport settings
:icons: font
:imagesdir: ../media/

[.lead]
When configuring ONTAP tools for VMware vSphere for the first time, AutoSupport is enabled by default. It sends messages to technical support 24 hours after it is enabled. 

== Disable AutoSupport

When you disable AutoSupport, you will no longer receive proactive support and monitoring.

[NOTE]
It is recommended to keep AutoSupport enabled, as it helps accelerate problem detection and resolution. Even when AutoSupport is disabled, the system continues to collect and store information locally, but it does not send reports over the network.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the *Settings* > *Telemetry* > *Edit* option.
. Deselect the *AutoSupport* option and save the changes.

== Update AutoSupport proxy URL

Update the AutoSupport proxy URL to ensure the proper functioning of the AutoSupport feature in scenarios where a proxy server is used for network access control or security measures. It allows the AutoSupport data to be routed through the appropriate proxy, enabling secure transmission and compliance.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *Settings* from the sidebar.
. Select the *Settings* > *Telemetry* > *Edit* option.
. Enter a valid *Proxy URL* and save the changes.
+
If you disable AutoSupport, the proxy URL is also disabled.

