---
permalink: manage/edit-esxi-host-settings.html
sidebar: sidebar
keywords: modify ESXi host settings, ONTAP tools host configuration, VMware host tuning, ESXi settings dashboard
summary: "Edit ESXi host settings from the ONTAP tools dashboard."
---
= Modify ESXi host settings using ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Use the ONTAP tools dashboard in VMware vSphere to identify configuration issues, review NetApp recommended settings for selected ESXi hosts, and apply them.

.Before you begin

The ESXi host systems portlet displays issues with ESXi host settings. Select an issue to view the host name or IP address.

.Steps

. Log in to the vSphere Client.
. On the Shortcuts page, select *NetApp ONTAP tools* under the Plug-ins section.
. Go to the *ESXi Host compliance* portlet on the Overview dashboard of the ONTAP tools for VMware vSphere plug-in.
. Select the *Apply Recommended Settings* link.
. In the *Apply recommended host settings* window, select the hosts for which you want to apply NetApp recommended host settings, and then select *Next*.
[NOTE]
You can expand the ESXi host to see the current values.
. On the Settings page, select the recommended values as needed.
. In the summary pane, check the values and select *Finish*.
You can track progress in the Recent Tasks panel.

.Related information

link:../configure/configure-esx-server-multipath-and-timeout-settings.html[Configure ESXi host settings]
// updated for https://github.com/NetAppDocs/ontap-tools-vmware-vsphere-10/issues/45 - jani
