---
permalink: manage/edit-hostcluster-protection.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'You can edit the SnapMirror relationships of the protected host cluster. You can add, modify, and delete the relationships. However, you cannot edit consistency group name. '
---
= Modify protected host cluster
:icons: font
:imagesdir: ../media/

[.lead]

You can change protection settings for a host cluster in a single workflow. The following changes are supported:

* Add new datastores or hosts to the protected cluster.
* Add new SnapMirror relationships to the protection settings.
* Delete existing SnapMirror relationships from the protection settings.
* Modify an existing SnapMirror relationship.

== Monitor host cluster protection
Monitor the protection status, SnapMirror relationships, datastores, and SnapMirror status for each protected host cluster.

.Steps

. Log in to the vSphere client.
. Go to *NetApp ONTAP tools* > *Protection* > *Host cluster relationships*. 
+
The protection column displays an icon that shows the protection status.
. Hover over the icon to see more details.


== Add new datastores or hosts

Add hosts or create datastores on the protected cluster using the vCenter user interface.

.Steps

. Log in to the vSphere client.
. To edit the properties of a protected cluster, you can either
.. Go to *NetApp ONTAP tools* > *Protection* > *Host cluster relationships*, select the ellipsis  menu next to the cluster and select *Edit* or
.. Right-click on a host cluster and select *NetApp ONTAP tools* > *Protect Cluster*.
. If you create a datastore in the vCenter user interface, it appears as unprotected. You can view all datastores in the cluster and their protection status in a dialog box. Select the *Protect* button to enable protection.
. If you add a new ESXi host, the protection status is shown as partially protected. Select the ellipsis menu under the SnapMirror settings and select *Edit* to set the proximity of the newly added ESXi host.
+
[NOTE]
For Asynchronous relationships, editing is not supported in ONTAP tools because the target SVM for a tertiary site cannot be added to the same instance. To modify the relationship configuration, use System Manager or the CLI on the target SVM.
. After making changes, select *Save*.
. You can see the changes in the *Protect Cluster* window.

ONTAP tools creates a vCenter task, and you can track its progress in the *Recent task* panel.

== Add a new SnapMirror relationship

.Steps

. Log in to the vSphere client.
. To edit the properties of a protected cluster, you can either
.. Go to *NetApp ONTAP tools* > *Protection* > *Host cluster relationships*, select the ellipsis  menu against the cluster and select *Edit* or
.. Right-click on a host cluster and select *NetApp ONTAP tools* > *Protect Cluster*.
. Select *Add relationship*. 
. Add new relationship as either *Asynchronous* or *AutomatedFailOverDuplex* policy type.
. Select *Protect*.
+
You can see the changes in the *Protect Cluster* window.

ONTAP tools creates a vCenter task, and you can track its progress in the *Recent task* panel.

== Delete an existing SnapMirror relationship
To delete an SnapMirror asynchronous relationship, ensure that the secondary site SVM or cluster is added as a storage backend in ONTAP tools for VMware vSphere.
You cannot delete all SnapMirror relationships at once. Deleting a relationship also removes the corresponding relationship from the ONTAP cluster.
When you delete an Automated Failover Duplex SnapMirror relationship, the system unmaps the destination datastores and deletes the consistency group, LUNs, volumes, and igroups from the destination ONTAP cluster.

When you delete the relationship, the system rescans the secondary site to remove the unmapped LUN as an active path from the hosts.

.Steps

. Log in to the vSphere client.
. To edit the properties of a protected cluster, you can either
.. Go to *NetApp ONTAP tools* > *Protection* > *Host cluster relationships*, select the ellipsis  menu against the cluster and select *Edit* or
.. Right-click on a host cluster and select *NetApp ONTAP tools* > *Protect Cluster*. 
. Select the ellipsis  menu under the SnapMirror settings and select *Delete*.
+
* If you delete an asynchronous policy type-based relationship of a protected host cluster, you must manually remove the storage elements from the tertiary storage cluster. Storage elements include consistency groups, volumes (for ONTAP systems), storage units (LUNs/Namespaces), and snapshots.
* If you delete an Automated Failover Duplex (AFD) policy-based relationship of a protected host cluster, you can choose to remove the associated storage elements on the secondary storage directly from the interface.
* If you delete an Automated Failover Duplex (AFD) policy-based relationship and the consistency group is now hierarchical for application-level backups, a warning appears about backup impact. Confirm to proceed. After confirmation, delete the associated storage elements on the secondary storage. If you do not remove them, they remain on the secondary site.

// 10.5 update for hierarchical CG
ONTAP tools creates a vCenter task, and you can track its progress in the *Recent task* panel.

== Modify an existing SnapMirror relationship
To modify an SnapMirror asynchronous relationship, ensure the secondary site SVM or cluster is added as a storage backend in ONTAP tools for VMware vSphere.
For Automated Failover Duplex SnapMirror relationships, you can update host proximity for uniform configurations or host access for non-uniform configurations.
Changing between Asynchronous and Automated Failover Duplex policy types is not supported.
You can configure proximity or access settings for newly discovered hosts in the cluster.

[NOTE]
You cannot edit an existing SnapMirror asynchronous relationship.

.Steps

. Log in to the vSphere client.
. To edit the properties of a protected cluster, you can either
.. Go to *NetApp ONTAP tools* > *Protection* > *Host cluster relationships*, select the ellipsis  menu against the cluster and select *Edit* or
.. Right-click on a host cluster and select *NetApp ONTAP tools* > *Protect Cluster*.
. If the AutomatedFailOverDuplex policy type is selected, add host proximity or host access details.
. Select *Protect* button.

ONTAP tools create a vCenter task. Track its progress in the *Recent task* panel.