---
permalink: manage/expand-storage-of-vvol-datastore.html
sidebar: sidebar
keywords: expand vVols datastore, increase vVol datastore capacity, ONTAP tools vVol storage expansion, VMware virtual volumes scaling
summary: "Expand vVols datastore storage from the vCenter object view by using ONTAP tools actions."
---
= Expand a vVols datastore in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]

When you right-click the datastore object in the vCenter object view, the plug-in section shows the supported actions for ONTAP tools for VMware vSphere. The available actions depend on the datastore type and the current user privileges.

[NOTE]
This procedure does not apply to ASA r2 system-based vVols datastores.

.Steps

. From the vSphere Client home page, select *Hosts and Clusters*.
. In the navigation pane, select the data center that contains the datastore.
. Right-click the datastore and select *NetApp ONTAP tools* > *Add storage to datastore*.
. In the *create or Select Volumes* window, you can either create new volumes or choose from the existing volumes. Follow the on-screen instructions to make your selection.
. In the *Summary* window, review the selections and select *Expand*.
You can track the progress in the recent tasks panel.

//NADIAA checked