---
permalink: manage/expand_storage_of_vvol_datastore.html
sidebar: sidebar
keywords: virtual volume datastores
summary: 'When you right click on datastore object in the vCenter object view, ONTAP tools supported actions are shown under the plug-in section.'
---
= Resize vVol Datastore
:icons: font
:imagesdir: ../media/

[.lead]

When you right click on datastore object in the vCenter object view, ONTAP tools supported actions are shown under the plug-in section. Specific actions are enabled depending on the type of datastore and the current user privileges.

*Steps*

. From the vSphere Client Home page, click *Hosts and Clusters*.
. In the navigation pane, select the datacenter that contains the datastore.
. Right-click the datastore and select *NetApp ONTAP tools* > *Resize datastore*.
. In the Resize dialog box, specify a new size for the datastore, and then click *OK*.
+
You can run the *REDISCOVER ALL* option in the Storage Systems menu to manually update the storage listing under Storage Systems and dashboard, or wait for the next scheduled refresh.
