---
permalink: manage/manage-vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.'
---
= Manage vCenter Server instances in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
vCenter Server instances are central management platforms that allow you to control hosts, virtual machines, and storage backends.

== Dissociate storage backends with the vCenter Server instance

The vCenter Server listing page shows the associated number of storage backends. Each vCenter Server instance has the option to associate or disassociate with a storage backend.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the required vCenter Server instance from the sidebar.
. Select the vertical ellipses against the vCenter Server that you want to associate or dissociate with storage backends.
. Select *Dissociate storage backend*.

== Modify a vCenter Server instance
Follow the steps below to modify a vCenter Server instances.

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instance from the sidebar
. Select the vertical ellipses against the vCenter Server that you want to modify and select *Modify*.
. In the *Modify vCenter* window, enter the username, password, and port details. 
. Upload the certificate  and select *Modify*.
// 10.5 updates -Jani - need to add details like when you need to add the certificate and update it. How to get this certificate. 

== Remove a vCenter Server instance
Remove all storage backends from the vCenter Server before removing it.

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instances from the sidebar
. Select the vertical ellipses against the vCenter Server that you want to remove and select *Remove*.
+
[NOTE]
After you remove vCenter Server instances, they will no longer be maintained by the application.

When you remove vCenter Server instances in ONTAP tools, the following actions are performed automatically: 

* Plug-in is unregistered.
* Plug-in privileges and plug-in roles are removed.
