---
permalink: manage/manage-protection-groups.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'You can edit the SnapMirror relationships of the protected host cluster. You can add, modify, and delete the relationships. However, you cannot edit consistency group name. '
---
= Manage protection groups in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can view, edit, and remove protection groups and their relationships directly from the cluster configuration page in ONTAP tools.

.Before you begin

Ensure you have administrative privileges in vSphere.

.Steps

. In the ONTAP tools plugin, navigate to *Protection* > *Protection groups*.
+
The protection groups are listed with their associated relationships, including consistency groups, SnapMirror policies, and protected datastores. 
. Select the vertical ellipsis (three dots) next to the protection group you want to manage:
.. To edit, select *Edit* and update relationships as needed.
.. To delete, select *Delete* and confirm the deletion in the dialog box.

.Related topics

link:../protect/config-proximity.html[Configure proximity/access for host cluster protection]
link:../manage/protect-ds.html[Protect a VMFS Datastore]
link:../protect/protect-multiple-ds.html[Protect multiple datastores]

// 10.6 updates