---
permalink: manage/manage-protection-groups.html
sidebar: sidebar
keywords: protection groups, SnapMirror relationships, disaster recovery, protected datastores
summary: 'View, edit, and delete protection groups and their relationships in ONTAP tools.'
---
= Manage protection groups in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Use this task to view, edit, and delete protection groups and their relationships from the *Protection groups* page in ONTAP tools.

.Before you begin

* Ensure you have administrative privileges in vSphere.
* Ensure your ONTAP tools user account has permissions to manage protection groups.

.Steps

. In the ONTAP tools plug-in, navigate to *Protection* > *Protection groups*.
+
The protection groups are listed with their associated relationships, including consistency groups, SnapMirror policies, and protected datastores.
. Select the vertical ellipsis (three dots) next to the protection group you want to manage.
.. To edit a protection group, select *Edit* and update the relationship settings.
.. To delete a protection group, select *Delete* and confirm the deletion in the dialog box.

[NOTE]
Edit operations are limited to supported relationship settings. Refer to your protection policy and workflow requirements before saving changes.

.Related topics

* link:../manage/protect-ds.html[Protect a VMFS Datastore]
* link:../protect/protect-multiple-ds.html[Protect multiple datastores]
* link:../protect/config-proximity.html[Configure cluster configuration for host cluster protection]

// 10.6 updates