---
permalink: manage/manage_vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.'
---
= Manage vCenter
:icons: font
:imagesdir: ../media/

[.lead]
vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.

== Associate or Dissociate storage backend with vCenter

vCenter listing page shows the associated number of storage backends. Each vCenter has option to Associate or Disassociate a storage backend 
This task help you to create mapping between storage backend and onboarded vCenter globally.

*Steps*

. Launch `\https://loadBalanceIP:8443/virtualization/ui/` from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar.
. Click on the vertical ellipsis against the vCenter that you want to associate or dissociate with storage backends.
. Select *Associate or Dissociate storage backend* depending on what action you want to perform.
+
See link:../configure/task_configure_user_role_and_privileges.html[List of minimum privileges required for non-admin global scoped cluster user].

== Modify vCenter
Follow the steps below to modify the vCenters.

. Launch `\https://loadBalanceIP:8443/virtualization/ui/` from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Click on the vertical ellipsis against the vCenter that you want modify and select *Modify*.
. Modify the vCenter details and select *Modify*.

== Remove vCenter
You need to remove all the storage backends attached to the vCenter before removing it. 

. Launch `\https://loadBalanceIP:8443/virtualization/ui/` from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Click on the vertical ellipsis against the vCenter that you want remove and select *Remove*.
+
[NOTE]
Once you remove the vCenter, it will no longer be maintained by the application.

== Manage Storage threshold
// Need to add procedure from ontap tools shortcut Settings> Threshold Settings > Modify. Move this API to API section
You can set the threshold to receive notifications in vCenter when the volume and the aggregate capacity reaches certain levels.

.Steps:
. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment.
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Settings* >*Threshold Settings* > *Edit*
. In the Edit Threshold window, provide the desired values in the Nearly Full and Full fields and click Save.
You can reset the numbers to recommended values, which is 80 for Nearly full and 90 for full.