---
permalink: manage/manage_vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.'
---
= Manage vCenter
:icons: font
:imagesdir: ../media/

[.lead]
vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.

== Add vCenter

You can add and manage multiple vCenters with one instance of ONTAP tools for VMware vCenter 10.0.

*Steps*

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Select *ADD* to onboard vCenters with vCenter IP Address/Hostname, username, password, and port. 
. Navigate to *Storage Backend* page and select *Add to onboard storage backend* (ONTAP Cluster) with Hostname, username, password, and port. 

See link:../configure/task_configure_user_role_and_privileges.html[List of minimum privileges required for non-admin global scoped cluster user].

== Associate or Dissociate storage backend with vCenter

vCenter listing page shows the associated number of storage backends. Each vCenter has option to Associate or Disassociate a storage backend 
This task help you to create mapping between storage backend and onboarded vCenter globally.

*Steps*

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar.
. Click on the vertical ellipsis against the vCenter that you want to associate or dissociate with storage backends.
. Select *Associate or Dissociate storage backend* depending on what action you want to perform.
+
See link:../configure/task_configure_user_role_and_privileges.html[List of minimum privileges required for non-admin global scoped cluster user].

== Modify vCenter
Follow the steps below to modify the vCenters.

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Click on the vertical ellipsis against the vCenter that you want modify and select *Modify*.
. Modify the vCenter details and select *Modify*.

== Remove vCenter
You need to remove all the storage backends attached to the vCenter before removing it. 

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select vCenters from the sidebar
. Click on the vertical ellipsis against the vCenter that you want remove and select *Remove*.
+
[NOTE]
Once you remove the vCenter, it will no longer be maintained by the application.
