---
permalink: manage/manage-vcenter.html
sidebar: sidebar
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management
summary: "Manage vCenter instances in ONTAP tools to control hosts, virtual machines, and storage backends."
---
= Manage vCenter Server instances in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Use ONTAP tools to dissociate storage backends, modify vCenter Server instance details, remove instances, and renew vCenter Server certificates.

== Dissociate storage backends from a vCenter Server instance

The vCenter Server listing page shows the number of associated storage backends. Each vCenter Server instance can associate with or dissociate from a storage backend.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *vCenters* from the sidebar.
. Select the vertical ellipsis for the vCenter Server that you want to associate or dissociate with storage backends.
. Select *Dissociate storage backend*.

== Modify a vCenter Server instance
To modify a vCenter Server instance, complete the following steps.

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select *vCenters* from the sidebar.
. Select the vertical ellipsis for the vCenter Server that you want to modify and select *Modify*.
. In the *Modify vCenter* window, enter the username, password, and port details. 
. Upload the certificate and select *Modify*.


== Remove a vCenter Server instance

You can remove a vCenter Server instance even when datastores and storage backends are still associated. The *Remove vCenter* dialog guides you through any required actions based on the current state of the vCenter Server.

[NOTE]
Force delete removes only ONTAP tools metadata. It does not remove ONTAP storage objects (volumes or LUNs), vSphere datastores, or virtual machines.

.Before you begin
Force delete is blocked if the vCenter Server has vVols datastores or protected datastores. Before proceeding:

* Remove or migrate all vVols datastores.
* Unprotect all protected datastores.
* Ensure that no discovery jobs are running. The force delete operation will not proceed if discovery jobs are in progress.

[NOTE]
Global storage backends shared with other vCenter Server instances are retained. Only the association with the deleted vCenter Server is removed.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment.
. Select *vCenters* from the sidebar.
. Select the vertical ellipsis for the required vCenter Server and select *Remove*.
. In the *Remove vCenter* dialog, review the state of the vCenter Server and complete any required actions.
+
The dialog behavior depends on the state of the vCenter Server:
+
[cols="2,2,3",options="header"]
|===
| Condition | Dialog behavior | Required action

| No vVols or protected datastores, but storage backends are associated
| The dialog displays the number of associated storage backends and datastores.
| Select *Remove all storage artifacts from this vCenter Server* and *I understand that the associated datastores will no longer be managed by ONTAP tools*.

| No vVols datastores, protected datastores, or storage backends
| The dialog confirms removal.
| No additional action required.

|===
. Select *Force delete*.
. Confirm the action.

.Result

ONTAP tools performs the following actions automatically:

* Plug-in is unregistered.
* Plug-in privileges and plug-in roles are removed.

The vCenter Server instance is no longer managed by ONTAP tools.

If the vCenter Server is unreachable during deletion:

* ONTAP tools removes the vCenter Server record.
* Plug-in unregistration does not occur.
* A warning is displayed.
* You must manually unregister the plugin from VMware vCenter Server.

== Renew vCenter Server certificate
// OTVDOC-342 updates
ONTAP tools notifies you when the vCenter certificate is nearing expiration or has expired. After renewing the vCenter certificate, upload the new certificate to ONTAP tools using the following steps:

. Log in to the ONTAP tools remote diagnostics shell.
. Obtain the renewed vCenter certificate from the diagnostics shell:
+
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p' 
----
. Verify the certificate is in Base 64 ASCII format and includes the beginning and ending lines, for example:
+
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copy the output and save it as a `.pem` file on your desktop.
. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment.
. Select the applicable vCenter Server instance from the sidebar
. Select the vertical ellipsis for the vCenter Server that you want to modify and select *Modify*.
. In the *Modify vCenter* window, enter the username, password, and port details. 
. Upload the certificate and select *Modify*.

.Related information

link:../manage/configure-remote-diagnostic-access.html[Configure remote diagnostic access]