---
permalink: manage/manage-vcenter.html
sidebar: sidebar
keywords:
summary: 'vCenters are central management platforms that allow you to control hosts, virtual machines, and storage backends.'
---
= Manage vCenter Server instances in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
vCenter Server instances are central management platforms that allow you to control hosts, virtual machines, and storage backends.

== Dissociate storage backends with the vCenter Server instance

The vCenter Server listing page shows the associated number of storage backends. Each vCenter Server instance has the option to associate or disassociate with a storage backend.

.Steps

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the required vCenter Server instance from the sidebar.
. Select the vertical ellipses against the vCenter Server that you want to associate or dissociate with storage backends.
. Select *Dissociate storage backend*.

== Modify a vCenter Server instance
Follow the steps below to modify a vCenter Server instances.

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instance from the sidebar
. Select the vertical ellipses against the vCenter Server that you want to modify and select *Modify*.
. In the *Modify vCenter* window, enter the username, password, and port details. 
. Upload the certificate  and select *Modify*.


== Remove a vCenter Server instance
Remove all storage backends from the vCenter Server before removing it.

. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment. 
. Select the applicable vCenter Server instances from the sidebar
. Select the vertical ellipses against the vCenter Server that you want to remove and select *Remove*.
+
[NOTE]
After you remove vCenter Server instances, they will no longer be maintained by the application.

When you remove vCenter Server instances in ONTAP tools, the following actions are performed automatically: 

* Plug-in is unregistered.
* Plug-in privileges and plug-in roles are removed.

== Renew vCenter Server certificate
// OTVDOC-342 updates
ONTAP tools notifies you when the vCenter certificate is nearing expiration or has expired. After renewing the vCenter certificate, upload the new certificate to ONTAP tools using the following steps:

. Log in to the ONTAP tools remote diagnostics shell.
. Obtain the renewed vCenter certificate from the diagnostics shell:
+
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p' 
----
. Ensure the certificate is in Base 64 ASCII format and includes the beginning and ending lines, for example:
+
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copy the output and save it as a text file with a `.pem` extension on your desktop.
. Launch ONTAP tools Manager from a web browser: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/` 
. Log in with the ONTAP tools for VMware vSphere administrator credentials you provided during deployment.
. Select the applicable vCenter Server instance from the sidebar
. Select the vertical ellipses against the vCenter Server that you want to modify and select *Modify*.
. In the *Modify vCenter* window, enter the username, password, and port details. 
. Upload the certificate  and select *Modify*.

.Related information

link:../manage/configure-remote-diagnostic-access.html[Configure remote diagnostic access]