---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html
sidebar: sidebar
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage
summary: "Migrate virtual machines from NFS and VMFS datastores to vVols datastores for policy-based management."
---
= Migrate virtual machines to vVols datastores in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate virtual machines from NFS or VMFS datastores to Virtual Volumes (vVols) datastores to use policy-based VM management and other vVols capabilities.

.Before you begin

Verify that VASA Provider is not running on any of the virtual machines that you plan to migrate. If you migrate a virtual machine that is running VASA Provider to a vVols datastore, you cannot perform any management operations, including powering on the virtual machines that are on vVols datastores.

.About this task

When you migrate from an NFS or VMFS datastore to a vVols datastore, vCenter Server uses vStorage APIs for Array Integration (VAAI) offloads for data moved from VMFS datastores, but not from NFS VMDK files. VAAI offloads usually reduce host load.

.Steps

. Right-click the virtual machine that you want to migrate and select *Migrate*.
. Select *Change storage only* and then select *Next*.
. Select a virtual disk format, a VM Storage Policy, and a vVol datastore that matches the features of the datastore that you're migrating. 
. Review the settings and select *Finish*.

//NADIAA checked
