---
permalink: manage/migrate-virtual-machines.html
sidebar: sidebar
keywords:
summary: 'You should be aware of some considerations when migrating existing virtual machines in your data center.'
---
= Virtual machine migration and cloning considerations for ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP tools for VMware vSphere support all major types of virtual machine migration, including compute-only (vMotion), storage-only (Storage vMotion), and combined compute and storage migration across all datastores. This topic outlines key considerations and best practices to ensure successful migration and cloning of virtual machines, regardless of the underlying datastore type.

// OTVDOC-351 updates
== Migrate protected virtual machines


You can migrate protected virtual machines to:

* The same datastore on a different ESXi host
* A different compatible datastore on the same ESXi host
* A different compatible datastore on a different ESXi host

If you migrate the virtual machine to a different FlexVol volume, the system updates the metadata file for that volume with the virtual machine information. If a virtual machine is migrated to a different ESXi host but the same storage, the underlying FlexVol volume metadata file will not be modified.

For information on migrating virtual machines, refer to the Broadcom documentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html[vSphere Virtual Machines Migration]

== Clone protected virtual machines


You can clone protected virtual machines to the following:

* The same container of the same FlexVol volume using a replication group
+
The same FlexVol volume's metadata file is updated with the cloned virtual machine details.

* The same container of a different FlexVol volume using a replication group
+
In the FlexVol volume where the cloned virtual machine is placed, the metadata file gets updated with the cloned virtual machine details.

* A different container or vVols datastore
+
In the FlexVol volume where the cloned virtual machine is placed, the metadata file gets updated with the virtual machine details.

VMware presently does not support virtual machines cloned to a VM template.


A clone of a clone of a protected virtual machine is supported.

Refer to the Broadcom documentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html[Creating a Virtual Machine for Cloning] for more details.

// 10.3 updates


== Virtual machine snapshots

ONTAP tools supports virtual machine snapshots through standard VMware workflows. Snapshots are short-term rollback points intended for use cases such as testing and patch preparation. They are not a substitute for backup or replication-based data protection. Running a virtual machine on a snapshot for extended periods can cause instability and data loss.

You can take crash-consistent snapshots (snapshots without memory state, which can be used to restart the virtual machine to a consistent state) on all supported datastore types. Quiesced snapshots, which use VMware Tools to flush in-memory data to disk before capturing, are also supported. For an overview of snapshot types and behavior, refer to https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html[Overview of virtual machine snapshots in vSphere].

[NOTE]
Memory snapshots capture the running memory state and temporarily stun the virtual machine. They are not supported in ONTAP tools workflows. If a virtual machine has a memory snapshot, you must delete it before the virtual machine can be included in a consistency group or host cluster relationship managed by ONTAP tools.

On ASA r2 storage systems, virtual machine snapshot behavior differs from other storage types. Snapshots are read-only. When you power on the virtual machine, VASA Provider creates a LUN from the read-only snapshot and enables IOPS. When you power off the virtual machine, VASA Provider deletes the LUN and disables IOPS.

For information on managing virtual machine snapshots, refer to the Broadcom documentation https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html[Manage Virtual Machines With Snapshots].

// Added for 10.3, inputs received from Rajiv