---
permalink: manage/migrate-virtual-machines.html
sidebar: sidebar
keywords:
summary: 'You should be aware of some of the considerations while migrating exisitng virtual machines in your data center.'
---
= Virtual machine migration and cloning considerations for ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can migrate and clone virtual machines using the native vCenter Server interface. Be aware of the following considerations when migrating existing virtual machines in your data center.
// OTVDOC-351 updates
== Migrate protected virtual machines

You can migrate the protected virtual machines to:

* Same datastore in a different ESXi host
* Different compatible datastore in same ESXi host
* Different compatible datastore in a different ESXi host

If you migrate the virtual machine to a different FlexVol volume, the system updates the metadata file for that volume with the virtual machine information. If a virtual machine is migrated to a different ESXi host but same storage, then underlying FlexVol volume metadata file will not be modified.

For information on migrating virtual machines, refer to the Broadcom documentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html[vSphere Virtual Machines Migration]

== Clone protected virtual machines

You can clone protected virtual machines to the following:

* Same container of same FlexVol volume using replication group
+
Same FlexVol volume's metadata file is updated with the cloned virtual machine details.

* Same container of a different FlexVol volume using replication group
+
The FlexVol volume where the cloned virtual machine is placed, the metadata file gets updated with the cloned virtual machine details.

* Different container or vVols datastore
+
The FlexVol volume where the cloned virtual machine is placed, the metadata file gets updated virtual machine details.

VMware presently doesn't support virtual machines cloned to a VM template.

Clone-of-Clone of a protected virtual machine is supported.

refer to the Broadcom documentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html[Creating a Virtual Machine for Cloning] for more details.

// 10.3 updates

== Virtual machine snapshots

Presently only virtual machine Snapshots without memory are supported. If virtual machine has Snapshot with memory, then the virtual machine is not considered for protection.

You also cannot protect unprotected virtual machines that have memory Snapshot. For this release, you're expected to delete memory snapshot before enabling protection for the virtual machine.

For a Windows VM with the ASA r2 storage type, a snapshot of the virtual machine is read-only.
When you power on the VM, VASA Provider creates a LUN from the read-only snapshot and enables IOPS. When you power off the VM, VASA Provider deletes the LUN and disables IOPS.

For information on managing the virtual machine snapshots, refer to the Broadcom documentation: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html[Manage Virtual Machines With Snapshots]

// Added for 10.3, inputs received from Rajiv