---
permalink: manage/mount-datastores-on-host.html
sidebar: sidebar
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host
summary: "Mount datastores on additional hosts after adding hosts to your VMware environment."
---
= Mount NFS and VMFS datastores in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Mounting a datastore provides storage access to additional hosts. You can mount the datastore on the additional hosts after you add the hosts to your VMware environment. 
[NOTE]
After adding the host, wait for the scheduled host discovery to complete before it shows up in ONTAP tools. Alternatively, you can manually run discovery from the NetApp ONTAP tools overview screen. For information on how to add an ESXi host to your vSphere cluster, refer to [Broadcom Technical Documentation](https://techdocs.broadcom.com/).

// OTVDOC-325 updates
.About this task 

* Some right-click actions are disabled or unavailable depending on the vSphere client version and the type of datastore selected. 
** If you're using vSphere client 8.0 or later versions, some of the right-click options are hidden. 
** From vSphere 7.0U3 to vSphere 8.0 versions, even though the options appear, the action will be disabled.
* vSphere disables the mount datastore option when the host cluster is protected with uniform configurations.
* When a datastore with nconnect is mounted on a new host, ONTAP tools applies the datastore's nconnect value if it exceeds the host's setting. 

.Steps

. From the vSphere Client home page, select *Hosts and Clusters*.
. In the left navigation pane, select the data centers containing the hosts.
. To mount NFS/VMFS datastores on a host or a host cluster, right-click and select *NetApp ONTAP tools* > *Mount Datastores*.
. Select the datastores that you want to mount and select *Mount*.


.What's next?
You can track the progress in the recent task panel.

.Related topic

link:../manage/add-vsphere-host.html[Add new VMware vSphere hosts]

// NADIAA checked