---
permalink: manage/mount-a-vvols-datastore.html
sidebar: sidebar
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount
summary: "Mount a vVols datastore to additional hosts to provide storage access across your virtual environment."
---
= Mount a vVols datastore in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can mount a VMware Virtual Volumes (vVols) datastore to one or more additional hosts to provide storage access to additional hosts. You can unmount a vVols datastore only through host-level APIs. Cluster-level datastore unmount is not supported.
// Unsupported parameter combinations for datastore unmount are not available in the REST API schema.

[NOTE]
After adding the host, wait for the scheduled host discovery to complete before it shows up in ONTAP tools. Alternatively, you can manually run discovery from the NetApp ONTAP tools overview screen. For information on how to add an ESXi host to your vSphere cluster, refer to [Broadcom Technical Documentation](https://techdocs.broadcom.com/).

// OTVDOC-325 updates
.Steps

. From the vSphere Client home page, select *Hosts and Clusters*.
. In the navigation pane, select the data center that contains the datastore.
. Right-click the datastore and select *NetApp ONTAP tools* > *Mount datastore*.
. In the *Mount datastores on Hosts* dialog box, select the hosts on which you want to mount the datastore, and then select *Mount*.

The recent task panel displays the progress.

.Related topic

link:../manage/add-vsphere-host.html[Add new VMware vSphere hosts]

//NADIAA checked