---
permalink: manage/nconnect-change-default.html
sidebar: sidebar
keywords:
summary: 'You can change the default number of connections (nconnect) applied to ESXi hosts in a vCenter Server. This setting applies to all hosts in the vCenter Server for NFS 3 and NFS 4 protocols.'
---
= Change the default nconnect value for ESXi hosts in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can change the default number of connections (nconnect) applied to ESXi hosts in a vCenter Server. This setting applies to all ESXi hosts in the selected vCenter Server for NFS 3 and NFS 4 protocols.

.About this task

The nconnect value set on this page is the host-level default. It applies to all ESXi hosts in the vCenter Server and determines the number of TCP connections used per NFS mount for NFS 3 and NFS 4 protocols. When you create an NFS datastore and select a higher nconnect value than the current host-level setting, ONTAP tools updates the host-level setting to match.
// 10.6 nconnect update.
.Steps

. Log in to the vSphere client.
. Select *Shortcuts* > *NetApp ONTAP tools* under the plug-ins section.
. Select *Settings* > *Default nconnect value*.
. Select *Edit*, change the default nconnect value for ESXi hosts and select *Save*.

The updated nconnect value is applied to all ESXi hosts in the vCenter Server for NFS 3 and NFS 4 protocols.
