---
permalink: manage/protect-cluster.html
sidebar: sidebar
keywords: vVols datastore,delete vVol
summary: 'ONTAP tools for VMware vSphere manages protection of host clusters.'
---
= Create host cluster protection
:icons: font
:imagesdir: ../media/
// new topic for 10.2 content
[.lead]

ONTAP tools for VMware vSphere manages protection of host clusters. 
All the datastores belonging to the selected SVM and mounted on one or more hosts of the cluster are protected under a host cluster.

.Prerequisites
Ensure the following conditions are met before you protect the host cluster:

. The host cluster has Datastores only from one SVM. 
. Any datastore mounted on the host cluster should not be mounted on any host outside of the cluster.
. All Datastores mounted on the host cluster must be VMFS datastores.
. Any FlexVol/LUN forming Datastores mounted on the host cluster should not be part of any existing consistency group (CG).
. Any FlexVol/LUN forming Datastores mounted on the host cluster should not be part of any existing SnapMirror relationship.
. The host cluster should have at least one VMFS datastore.

.Steps

. Log in to the vSphere client using `\https://vcenterip/ui`
. Right-click a host cluster, and then select *NetApp ONTAP tools* > *Protect Cluster*.
. In the protect cluster window, the datastore type and source storage VM are auto populated. Select the datastores link to view the datastores that are protected.
. Enter the *consistency group name*.
. Select *Add Relationship*.
. In the Add SnapMirror Relationship window, select the *Target storage VM* and the *Policy* type.
+
The policy type can be asynchronous or AutomatedFailOverDuplex. 
+
When you add SnapMirror relationship as AutomatedFailOverDuplex type policy, it is mandatory to add the target Storage VM as Storage backend to the same vCenter where ONTAP tools for VMware vSphere is deployed.
+
In AutomatedFailOverDuplex policy type, there is uniform and non-uniform host configuration. 
When you select the *uniform host configuration* toggle button, the host initiator group configuration is implicitly replicated on the target site. 
. select the host access (source/target) for each host inside that cluster if you choose to have a non-uniform host configuration.
. Select *Add*.
. In the *Protect cluster* window you can edit or delete the relationships using the kebab menu options.
.  Select *Protect* button.
+
A job is created in vCenter server and the cluster is protected. Use the generated JobID to monitor the task. 
+
If there are errors in creating protection for the cluster a pop-up window appears to show the errors.
. To view the protected host clusters, navigate to *NetApp ONTAP tools* > *Protection* > *Host cluster relationship*.