---
permalink: manage/recover-backup.html
sidebar: sidebar
keywords: recover ONTAP tools setup, appliance recovery workflow, near zero RPO recovery, restore ONTAP tools configuration
summary: "Recover ONTAP tools from backup and understand zero-RPO and near zero-RPO behavior by release."
---
= Recover ONTAP tools for VMware vSphere from backup
:icons: font
:imagesdir: ../media/

[.lead]
Recover ONTAP tools for VMware vSphere by restoring a backup file stored on the datastore. Beginning with ONTAP tools for VMware vSphere 10.5, backup is enabled by default, so a recent backup is usually available if you need to redeploy or recover the appliance.

The datastore where you deploy ONTAP tools for VMware vSphere virtual machines stores the backup files. A folder named after the ONTAP tools IP address stores the two most recent backup files (_OTV_backup_1.tar.enc_ and _OTV_backup_2.tar.enc_) and the info file (_OTV_backup_info.txt_), which identifies the latest backup.

Ensure that the new virtual machine uses the same ONTAP tools IP address and matches the initial system configuration, including enabled services, node size, and HA mode.

.Steps

. Download the backup files from the datastore of the original virtual machine to your local system.
.. Go to the storage section and choose the datastore that contains the backup files for the virtual machine.
.. Select the *Files* section.
.. Download the required backup directory.
. Power off the existing virtual machine. Then, deploy a new virtual machine using the same OVA file as the original deployment.
. Log in to the vCenter Server.
. Locate the newly deployed ONTAP tools VM and launch the web console.
. Log in using the `maint` credentials.
. Enter `4` to select *Support and Diagnostics*.
. Enter `2` to select *Enable remote diagnostic access* option and create a new password for the diagnostic access.
. Choose a backup file from the downloaded directory. Refer to the _OTV_backup_info.txt_ file to identify the latest backup.
. Use the following command to transfer the backup file to the new virtual machine. When prompted, enter the diagnostic password.
+
----
scp <OTV_backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+
[NOTE]
Do not alter the destination path and file name (/home/diag/system_recovery.tar.enc) mentioned in the command.
. After the backup file is transferred, log in to the diagnostic shell and run the following command:
+
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
The logs are recorded in the _/var/log/otvng/post-deploy-upgrade.log_ file.

After you complete the recovery, ONTAP tools restores services and vCenter objects.