---
permalink: manage/remove-storage-from-a-vvols-datastore.html
sidebar: sidebar
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down
summary: "Delete a vVols datastore only when no vVols remain on the selected datastore."
---
= Shrink a vVols datastore in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Remove volumes from a vVols datastore in ONTAP tools to reduce capacity when you no longer need the additional storage.

Use the remove storage from datastore action on any vVols datastore managed by ONTAP tools in vCenter Server.

You cannot remove storage from a volume if it contains vVols; the remove option is disabled for such volumes. When removing volumes from the datastore, you also have the option to delete the selected volumes from ONTAP storage.

[NOTE]
The shrink vVols datastore operation is not supported for vVols datastores based on ASA r2 systems.

.Steps

. From the vSphere Client home page, select *Hosts and Clusters*.
. In the navigation pane, select the data center that contains the datastore.
. Right-click the vVol datastore and select *NetApp ONTAP tools* > *Remove storage from datastore*. 
. Select volumes that don't have vVols and select *Remove*.
+
[NOTE]
The option to select the volume on which vVols reside is disabled.
. In the *Remove storage* pop-up, select the *Delete volumes from ONTAP cluster* check box to delete the volumes from the datastore and ONTAP storage, and then select *Delete*.

//NADIAA checked.
