---
permalink: manage/reports.html
sidebar: sidebar
keywords:
summary: 'ONTAP tools for VMware vSphere plug-in provides reports for virtual machines and datastores.'
---
= ONTAP tools for VMware vSphere reports
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere plug-in provides reports that help you monitor virtual machines and datastores backed by ONTAP storage. To view these reports, select the ONTAP tools for VMware vSphere plug-in icon in the shortcuts section of the vCenter client, and then select the Reports tab.

The Virtual Machines report lists discovered virtual machines that have at least one disk on an ONTAP storage-based datastore, along with performance metrics.
When you expand the VM record, the interface displays all the disk-related datastore information.

The datastores report lists datastores that ONTAP tools for VMware vSphere discovers and that use ONTAP storage, along with performance metrics.

You can use the Manage Columns option to hide or show different columns.

// NADIAA checked