---
permalink: manage/reports.html
sidebar: sidebar
keywords: ONTAP tools reports, virtual machine reports, datastore reports, VMware storage reporting
summary: "View virtual machine and datastore reports in the ONTAP tools plug-in."
---
= ONTAP tools for VMware vSphere reports
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere plug-in provides reports that help you monitor virtual machines and datastores backed by ONTAP storage. To view the reports, select the ONTAP tools for VMware vSphere plug-in icon in the shortcuts section of the vSphere Client, and then select the *Reports* tab.

The Virtual Machines report lists discovered virtual machines that have at least one disk on an ONTAP storage-based datastore, along with performance metrics.
When you expand a VM record, you can see all datastore information for its disks.

The datastores report lists datastores that ONTAP tools for VMware vSphere discovers and that use ONTAP storage, along with performance metrics.

You can use the *Manage Columns* option to hide or show columns.

// NADIAA checked