---
permalink: manage/reset-manager-password.html
sidebar: sidebar
keywords: reset ONTAP tools Manager password, manager admin credential recovery, token-based password reset, appliance administrator reset
summary: "Reset ONTAP tools Manager administrator credentials by using a maintenance console token."
---
= Reset the ONTAP tools Manager password
:icons: font
:imagesdir: ../media/

[.lead]
If you forget the ONTAP tools Manager password, you can restore administrator access by using a reset token generated from the ONTAP tools for VMware vSphere maintenance console.
// need to check this for 10.6 updates option 3 does not exist

.Steps

. Open a web browser and go to `https://<ONTAPtoolsIP>:8443/virtualization/ui/` to open ONTAP tools Manager.
. On the login page, select *Reset password*.
. Generate a password reset token using the ONTAP tools for VMware vSphere maintenance console:
.. Log in to the vCenter Server.
.. Locate the ONTAP tools VM and launch the web console.
.. Log in using the `maint` credentials.
.. Enter `2` to select *System Configuration*.
.. Enter `3` to select *Generate token to reset manager UI password*, and note the token.
. In the password reset dialog, enter the reset token, username, and new password.
. Select *Reset* to update the credentials.
. Log in to ONTAP tools Manager with the new password.