---
permalink: manage/reset-manager-password.html
sidebar: sidebar
keywords:
summary: 'If you have forgotten the ONTAP tools Manager password, you can reset the administrator credentials using the token generated by ONTAP tools for VMware vSphere maintenance console.'
---
= Reset ONTAP tools Manager password
:icons: font
:imagesdir: ../media/

[.lead]
If you forget the ONTAP tools Manager password, you can restore administrator access by using a reset token generated from the ONTAP tools for VMware vSphere maintenance console.

.Steps

. Open a web browser and navigate to `https://<ONTAPtoolsIP>:8443/virtualization/ui/` to access ONTAP tools Manager.
. On the login page, select *Reset password*.
. Generate a password reset token using the ONTAP tools for VMware vSphere maintenance console:
.. Log in to the vCenter Server and open the maintenance console.
.. Enter `2` to select *System Configuration*.
.. Enter `3` to select *Change 'maint' user password*.
. In the password reset dialog, enter the reset token, username, and new password.
. Select *Reset* to update the credentials.
. Log in to ONTAP tools Manager with the new password.