---
permalink: manage/reset-manager-password.html
sidebar: sidebar
keywords: reset ONTAP tools Manager password, manager admin credential recovery, token-based password reset, appliance administrator reset
summary: "Reset ONTAP tools Manager administrator credentials by using a maintenance console token."
---
= Reset ONTAP tools Manager password
:icons: font
:imagesdir: ../media/

[.lead]
If you forget the ONTAP tools Manager password, you can restore administrator access by using a reset token generated from the ONTAP tools for VMware vSphere maintenance console.
// need to check this for 10.6 updates option 3 does not exist

.Steps

. Open a web browser and navigate to `https://<ONTAPtoolsIP>:8443/virtualization/ui/` to access ONTAP tools Manager.
. On the login page, select *Reset password*.
. Generate a password reset token using the ONTAP tools for VMware vSphere maintenance console:
.. Log in to the vCenter Server and open the maintenance console.
.. Enter `2` to select *System Configuration*.
.. Enter `3` to select *Change 'maint' user password*.
. In the password reset dialog, enter the reset token, username, and new password.
. Select *Reset* to update the credentials.
. Log in to ONTAP tools Manager with the new password.