---
permalink: manage/storage-view-datastore.html
sidebar: sidebar
keywords: ONTAP storage view, datastore details, NFS datastore, VMFS datastore, vVol datastore
summary: 'View datastore and volume details from the ONTAP Storage page in ONTAP tools for VMware vSphere.'
---
= ONTAP storage views for datastores in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Use the ONTAP Storage page in the *Configure* tab to view datastore and volume information.

.Steps
. In the vSphere Client inventory, select the datastore.
. Select the *Configure* tab in the right pane.
. Select *NetApp ONTAP tools* > *ONTAP Storage*. The view changes by datastore type. See the table below:

|===
|*Datastore type* |*Information available*
|NFS datastores |The *Storage details* page contains storage backends, aggregates, and volume information.

The *NFS details* page contains data related to the NFS datastore.
// no change required for 10.6 nconnect feature as th sentence is generic.

|VMFS datastores |The *Storage details* page contains storage backend, aggregate, volume, and storage availability zone (SAZ) details.

The *Storage unit details* page contains storage unit details.
|vVols datastores |Lists all the volumes. You can expand or remove storage from the ONTAP storage pane.

ONTAP tools do not support this view for ASA r2 system-based vVols datastores.

|===

.Result

You can review ONTAP-side datastore details based on the selected datastore type.

// NADIAA checked