---
permalink: manage/storage-view-datastore.html
sidebar: sidebar
keywords: Remove vVol datastore
summary: 'ONTAP storage view under configure tab of an ONTAP tools for VMware vSphere provides data related to the datastore and its volume.'
---
= ONTAP storage views for datastores
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP storage view under configure tab of ONTAP tools for VMware vSphere provides data related to the datastores and their volume. This view provides the storage side view of the datastore.

== ONTAP storage views for NFS datastores

.Steps

. From the vSphere Client navigate to the NFS datastore.
. Select the *Configure* tab in the right pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. The *Storage details* and *NFS details* appear on the right pane.
+
* The storage details page contains information about storage backends, aggregate, and volume.
* The NFS details page contains data related to the NFS datastore.

== ONTAP storage views for VMFS datastores
.Steps

. From the vSphere Client navigate to the VMFS datastore.
. Select the *Configure* tab in the right pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. The *Storage details* and *LUN details* or *Namespace details* depending on the protocol appear on the right pane.
+
* The storage details page contains information about storage backends, aggregate, and volume.
* The LUN details page contains data related to the LUN.
* When using NVMe/TCP or NVMe/FC protocol for VMFS datastore, the Namespace details page contains data related to Namespace.
* Volume and aggregate details are not displayed for ASA r2 system based datastores.

// updated for 10.3 ASA r2
== ONTAP storage views for vVols datastores
[NOTE]
This view is not supported for ASA r2 based vVols datastore.

.Steps

. From the vSphere Client navigate to the vVols datastore.
. Select the *Configure* tab in the right pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. 
. The ONTAP storage view lists all the volumes. You can expand or remove storage from the ONTAP storage pane.
+
Follow the instructions in link:../manage/expand-storage-of-vvol-datastore.html[Expand vVols Datastore] section to add vVols datastore and link:../manage/remove-storage-from-a-vvols-datastore.html[Shrink vVols datastore] section to delete the datastore.