---
permalink: manage/storage-view-datastore.html
sidebar: sidebar
keywords: Remove vVol datastore
summary: 'ONTAP storage view under configure tab of an ONTAP tools for VMware vSphere provides data related to the datastore and its volume.'
---
= ONTAP storage views for datastores
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP storage view under configure tab of ONTAP tools for VMware vSphere provides data related to the datastores and their volume. This view provides the storage side view of the datastore.

== ONTAP storage views for NFS datastores

.Steps

. From the vSphere Client navigate to the NFS datastore.
. Click the *Configure* tab in the right side pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. The *Storage details* and *NFS details* appear on the right pane.
+
* The storage details page contains information about storage backends, aggregate, and  volume.
* The NFS details page contains data related to the NFS datastore.

== ONTAP storage views for VMFS datastores
.Steps

. From the vSphere Client navigate to the VMFS datastore.
. Click the *Configure* tab in the right side pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. The *Storage details* and *LUN details* appear on the right pane.
+
* The storage details page contains information about storage backends, aggregate, and  volume.
* The LUN details page contains data related to the LUN.

== ONTAP storage views for vVols datastores
.Steps

. From the vSphere Client navigate to the vVols datastore.
. Click the *Configure* tab in the right side pane. 
. Select *NetApp ONTAP tools* > *ONTAP Storage*. 
. The ONTAP storage view lists all the volumes. You can expand or remove storage from the ONTAP storage pane.
+
Expand storage is the same as link:../manage/expand_storage_of_vvol_datastore.html[Expand vVols Datastores] 
+
Remove storage is the same as link:../manage/task_remove_storage_from_a_vvols_datastore.html[Shrink vVols datastores]