---
permalink: manage/storage_backend.html
sidebar: sidebar
keywords:
summary: 'Storage backends are systems that the ESXi hosts use for data storage.'
---
= Manage storage backends
:icons: font
:imagesdir: ../media/

[.lead]
Storage backends are systems that the ESXi hosts use for data storage.

== Discover storage

You can run the discovery of a storage backend on demand without waiting for scheduled discovery to update the storage details.

Follow the steps below to discover the storage backends.

.Steps

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipsis menu and select *Discover storage*

You can track the progress in the Recent Tasks panel.

== Modify storage backend
Follow the steps in this section to modify the existing storage backend.

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipsis menu and select *Modify* to modify the credentials or the port name.
You can track the progress in the Recent Tasks panel.

You can perform the same operation using ONTAP tools Manager UI using the following steps:

. Launch ONTAP tools Manger UI using `\https://loadBalanceIP:8443/virtualization/ui/` from the browser. 
. Log in with ONTAP tools administrator credentials provided during deployment. 
. Select storage backends from the sidebar.
. Select the  *Storage Backend* you want to modify
. Click on the vertical ellipsis menu and select *Modify*. 
. You can modify the credentials or the port. Enter the *Username* and *Password* to modify the storage backend.

== Remove storage backend

You need to delete all the datastores attached to the storage backend before removing the storage backend. 
Follow the steps below to remove storage backend.

. Log in to the vSphere client using `\https://vcenterip/ui`
. In the shortcuts page, click on *NetApp ONTAP tools* under plug-ins section.
. In the left pane of ONTAP tools, navigate to *Storage Backends* and select a storage backend.
. Click on the vertical ellipsis menu and select *Remove*. Ensure that the storage backend does not contain any datastores.
You can track the progress in the Recent Tasks panel.

You can perform the same operation using ONTAP tools Manager UI:

. Launch ONTAP tools Manger UI using `\https://loadBalanceIP:8443/virtualization/ui/` from the browser. 
. Log in with ONTAP tools administrator credentials provided during deployment. 
. Select *Storage Backends* from the sidebar.
. Select the  storage backend you want to remove
. Click on the vertical ellipsis menu and select *Remove*. 
