---
permalink: manage/task_remove_storage_from_a_vvols_datastore.html
sidebar: sidebar
keywords: Remove vVol datastore
summary: 'A vVols datastore exists as long as at least one FlexVol volume is available on the datastore.'
---
= Shrink vVols datastore
:icons: font
:imagesdir: ../media/

[.lead]
This API deletes the VMware Virtual Volumes (vVols) datastore from storage.

*About this task*

A vVols datastore exists as long as at least one FlexVol volume is available on the datastore. If you want to delete a vVols datastore in a HA cluster, you should first unmount the datastore from all hosts within the HA cluster, and then delete the residing _.vsphere-HA_ folder manually using the vCenter server user interface. 

. Steps

. From the vSphere Client Home page, click *Hosts and Clusters*.
. In the navigation pane, select the datacenter that contains the datastore.
. Right click on the vVol datastore and select *NetApp Ontap tools* > *Remove storage from datastore*.
. Clean up the Flex volumes at the Storage array and the igroup.

[NOTE]
Delete vVols datastore and do not delete volumes from storage
