---
permalink: manage/task_collect_the_log_files.html
sidebar: sidebar
keywords:
summary: 'You can collect log files for ONTAP tools for VMware vSphere from the option available in ONTAP tools graphical user interface \(GUI\). Technical support might ask you to collect the log files to help troubleshoot a problem.'
---
= Collect the log files
:icons: font
:imagesdir: ../media/

[.lead]
You can collect log files for ONTAP tools for VMware vSphere from the option available in ONTAP tools Manager user interface. Technical support might ask you to collect the log files to help troubleshoot a problem.

[NOTE]
Generating logs from Manager UI includes all logs for all vCenters. Generating logs from vCenter client UI are scoped for the selected vCenter.

*Steps*

. Launch ONTAP tools Manager UI using `\https://loadBalanceIP:8443/virtualization/ui/` from the browser. 
. Log in with ONTAP tools administrator credentials provided during deployment. 
. Select *Log Bundles* from the sidebar.
+
This operation can take several minutes.
. Select *GENERATE* to generate the log files.
. Enter the label for the Log Bundle and select *GENERATE*.
+
Download the tar.gz file and send it to technical support. 

Follow the steps below to generate log bundle using the vCenter client UI:

.Steps
. Log in to the vSphere client using `\https://vcenterip/ui`
. From the vSphere Client Home page, go to *Support* > *Log bundle* > *Generate*.
. Provide the log bundle label and generate the log bundle.
You can see the download option when the files are generated. Downloading may take some time.

[NOTE]
The log bundle generated replaces the log bundle that was generated within the last 24hrs.
