---
permalink: manage/task_collect_the_log_files.html
sidebar: sidebar
keywords:
summary: 'You can collect log files for ONTAP tools for VMware vSphere from the option available in the ONTAP tools graphical user interface \(GUI\). Technical support might ask you to collect the log files to help troubleshoot a problem.'
---
= Collect the log files
:icons: font
:imagesdir: ../media/

[.lead]
You can collect log files for ONTAP tools for VMware vSphere from the option available in the ONTAP tools manager user interface. Technical support might ask you to collect the log files to help troubleshoot a problem.

*Steps*

. Launch https://loadBalanceIP:8443/virtualization/ui/ from browser with ONTAP tools administrator credentials provided during deployment. 
. Select *Log Bundles* from the sidebar.
+
This operation can take several minutes.
. Select *GENERATE* to generate the log files.
. Enter the label for the Log Bundle and select *GENERATE*.
+
Download the tar.gz file and send it to technical support. 

Follow the steps below to generate log bundle using the vCenter client UI:

.Steps
. Log in to the vSphere web client by using the vCenter IP that was provided during OVA ONTAP tools
deployment.
. From the vSphere Client Home page, go to *Support* > *Log bundle* > *Generate*.
. Provide the log bundle label and generate the log bundle.
You can see the download option when the files are generated. Downloading may take some time.

[NOTE]
The log bundle generated replaces the log bundle that was generated within the last 24hrs.
