---
permalink: manage/uninstall-deployment.html
sidebar: sidebar
keywords: uninstall ONTAP tools, remove ONTAP tools deployment, appliance decommission workflow, graceful deployment termination
summary: "Terminate your ONTAP tools for VMware vSphere deployment gracefully."
---
= Uninstall your ONTAP tools for VMware vSphere deployment
:icons: font
:imagesdir: ../media/

[.lead]
Uninstalling ONTAP tools for VMware vSphere deletes data in the appliance, so complete these steps to shut down the deployment gracefully and avoid unexpected data loss.

.Steps

. Remove or move all the virtual machines from the ONTAP tools for VMware vSphere managed datastores.
+
* To remove the virtual machines, refer to https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en[Remove and reregister VMs and VM templates]
* To move them to an unmanaged datastore, refer to https://techdocs.broadcom.com/[Broadcom Technical Documentation] for migrating virtual machines with Storage vMotion
// updated as per pull request from Chance.
. link:../manage/delete-ds.html[Delete datastores] created on ONTAP tools for VMware vSphere.
. If you have enabled the VASA Provider, select *Settings* > *VASA Provider settings* > *Unregister* in ONTAP tools to unregister the VASA Provider from all the vCenter Server instances. 
. Remove the SRA adapter from VMware Live Site Recovery:
.. Log in as admin to the VMware Live Site Recovery appliance management interface using port 5480.
.. Select *Storage Replication Adapters*.
.. Select the appropriate SRA card, and from the drop-down menu, select  *Delete*.
.. Confirm that you know the results of deleting the adapter and select *Delete*.
. Remove the vCenter Server instances onboarded to ONTAP tools for VMware vSphere. Refer to link:../manage/manage-vcenter.html[Manage vCenter Server instances].
+
When you remove a vCenter Server instance, ONTAP tools can guide you through the required cleanup. If prompted in the *Remove vCenter* dialog, select *Remove all storage artifacts from this vCenter Server* and *I understand that the associated datastores will no longer be managed by ONTAP tools*, and then select *Force delete*.
+
Before you use *Force delete*, ensure that all vVols datastores are removed or migrated, all protected datastores are unprotected, and no discovery jobs are running.
+
If the vCenter Server is unreachable during deletion, ONTAP tools removes only the vCenter Server record. You must manually unregister the plug-in from VMware vCenter Server.
. Power off the ONTAP tools for VMware vSphere VMs from the vCenter Server and delete the VMs. 

.What’s next?

link:../manage/delete-deployment.html[Remove FlexVol volumes]

// OTVDOC-359 updates