---
permalink: manage/unmount-datastores-on-host.html
sidebar: sidebar
keywords: unmount NFS VMFS datastore, remove datastore from host, ONTAP tools datastore unmount, ESXi host storage detach
summary: "Unmount NFS or VMFS datastores from ESXi hosts by using ONTAP tools."
---
= Unmount NFS and VMFS datastores in ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Use this task to unmount an NFS or VMFS datastore from ESXi hosts.

Beginning with ONTAP tools 10.6, unmount is blocked for protected VMFS datastores.
// 10.6 GDP feature
.Steps

. Log in to the vSphere client.
. Right-click an NFS or VMFS datastore object and select *Unmount datastore*.
+
The vSphere client opens a dialog box and lists the ESXi hosts that mount the datastore.
If the datastore is protected, ONTAP tools blocks the request and shows a message that the datastore is under protection and cannot be unmounted.
. Select one or more ESXi hosts to unmount the datastore.
+
You cannot unmount the datastore from all hosts. The user interface suggests that you use the delete datastore operation instead.
. Select the *Unmount* button.
+
The *Unmount datastore* option is available only when the host is moved outside the protected host cluster.

[NOTE]
If a datastore is protected, you must remove protection before you can unmount it.

.What's next?
You can track the progress in the recent tasks panel.