---
permalink: manage/unmount-datastores-on-host.html
sidebar: sidebar
keywords:
summary: 'Unmount datastore action unmounts a NFS or VMFS datastore from ESXi hosts. Unmount datastore action is enabled for NFS and VMFS datastores that are discovered or managed by the ONTAP tools for VMware vSphere.'
---
= Unmount NFS and VMFS datastores
:icons: font
:imagesdir: ../media/

[.lead]

The Unmount datastore action removes an NFS or VMFS datastore from ESXi hosts. It is available for datastores discovered or managed by ONTAP tools for VMware vSphere.

.Steps

. Log in to the vSphere client.
. Right-click on a NFS or VMFS datastore object and select *Unmount datastore*.
+
The vSphere client opens a dialog box and lists the ESXi hosts that mount the datastore. 
When the operation is performed on a protected datastore, a warning message is displayed on the screen.
. Select one or more ESXi hosts to unmount the datastore.
+
You cannot unmount the datastore from all hosts. The user interface suggests that you use the delete datastore operation instead.
. Select the *Unmount* button.
+
If the datastore is part of a protected host cluster, a warning message is displayed. 

[NOTE]
If the protected datastore is unmounted the exiting protection setting might result in partial protection. Refer to link:../manage/edit-hostcluster-protection.html[Modify protected host cluster] to enable complete protection.

.What's next?
You can track the progress in the recent tasks panel.