---
permalink: manage/unprotect-ds.html
sidebar: sidebar
keywords: VMFS datastore, unprotect datastore, protection group, SnapMirror, LUN cleanup
summary: 'Unprotect a VMFS datastore and optionally remove associated target-side storage elements.'
---

= Unprotect a VMFS datastore
:icons: font
:imagesdir: ../media/

[.lead]
Use this task to remove protection from a VMFS datastore and optionally remove associated target-side storage elements.

.Before you begin

* Ensure you have administrative privileges in vSphere.
* Ensure your ONTAP tools user account has permissions to manage protection settings.
* Review the impact of unprotecting the last datastore in a protection group.

.Steps

. Log in to the vSphere Client.
. Select a host cluster and select *Datastores*.
. Right-click the eligible VMFS datastore you want to unprotect and select *NetApp ONTAP tools* > *Unprotect*.
[NOTE]
Unprotecting the last datastore in a protection group deletes the protection group and associated storage elements.
. Optional: Select *Delete associated storage elements (LUNs) from the secondary storage* to delete replicated LUNs and consistency groups on the target.
. Select *Unprotect*.

.Result
The datastore is removed from protection. If it was the last datastore in the protection group, the protection group is deleted. If you selected the delete option, target-side replicated LUNs and consistency groups are also removed.

// 10.6 updates
